/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) SAM_equation_system_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s4[38] = {19, 19, 0, 0, 0, 0, 4, 8, 12, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6};
static const casadi_int casadi_s5[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[4] = {0, 1, 0, 0};
static const casadi_int casadi_s8[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

/* SAM_equation_system_cost_y_e_hess:(i0[19],i1[],i2[0],i3[19],i4[],i5[25])->(o0[19x19,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+16, *w2=w+35, *w3=w+54, w4, w6, *w7=w+60, w8, w9, w10, *w11=w+67, *w12=w+71, *w13=w+75, *w14=w+79, w15, w16, w17, w18, w19, *w20=w+109, *w21=w+113, *w22=w+117;
  /* #0: @0 = zeros(19x19,16nz) */
  casadi_clear(w0, 16);
  /* #1: @1 = zeros(19x1) */
  casadi_clear(w1, 19);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 19, w2);
  /* #3: @3 = @2[3:7] */
  for (rr=w3, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #4: @4 = 1 */
  w4 = 1.;
  /* #5: @5 = 00 */
  /* #6: @6 = vertcat(@4, @5, @5, @5) */
  rr=(&w6);
  *rr++ = w4;
  /* #7: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #8: @6 = (@6/@4) */
  w6 /= w4;
  /* #9: @7 = dense(@6) */
  casadi_densify((&w6), casadi_s0, w7, 0);
  /* #10: @6 = @2[3] */
  for (rr=(&w6), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #11: @8 = @2[4] */
  for (rr=(&w8), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #12: @8 = (-@8) */
  w8 = (- w8 );
  /* #13: @9 = @2[5] */
  for (rr=(&w9), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #14: @9 = (-@9) */
  w9 = (- w9 );
  /* #15: @10 = @2[6] */
  for (rr=(&w10), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #16: @10 = (-@10) */
  w10 = (- w10 );
  /* #17: @11 = vertcat(@6, @8, @9, @10) */
  rr=w11;
  *rr++ = w6;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #18: @11 = (@11/@4) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) /= w4;
  /* #19: @11 = (@11/@4) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) /= w4;
  /* #20: @6 = project(@3) */
  casadi_sparsify(w3, (&w6), casadi_s0, 0);
  /* #21: @8 = ones(4x1,1nz) */
  w8 = 1.;
  /* #22: @9 = dot(@6, @8) */
  w9 = casadi_dot(1, (&w6), (&w8));
  /* #23: @9 = (@9/@4) */
  w9 /= w4;
  /* #24: @12 = (@11*@9) */
  for (i=0, rr=w12, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #25: @7 = (@7-@12) */
  for (i=0, rr=w7, cs=w12; i<4; ++i) (*rr++) -= (*cs++);
  /* #26: @7 = (@7/@4) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) /= w4;
  /* #27: @12 = (@11/@4) */
  for (i=0, rr=w12, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)/w4);
  /* #28: @13 = (@12*@9) */
  for (i=0, rr=w13, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #29: @7 = (@7-@13) */
  for (i=0, rr=w7, cs=w13; i<4; ++i) (*rr++) -= (*cs++);
  /* #30: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<4; ++i) *rr++ = (- *cs++ );
  /* #31: @13 = zeros(4x1) */
  casadi_clear(w13, 4);
  /* #32: @14 = input[5][0] */
  casadi_copy(arg[5], 25, w14);
  /* #33: @6 = @14[6] */
  for (rr=(&w6), ss=w14+6; ss!=w14+7; ss+=1) *rr++ = *ss;
  /* #34: @2 = input[3][0] */
  casadi_copy(arg[3], 19, w2);
  /* #35: {NULL, @8, @10, @15, @16, NULL, NULL} = vertsplit(@2) */
  w8 = w2[3];
  w10 = w2[4];
  w15 = w2[5];
  w16 = w2[6];
  /* #36: @17 = (@6*@16) */
  w17  = (w6*w16);
  /* #37: (@13[0] += @17) */
  for (rr=w13+0, ss=(&w17); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #38: @17 = @14[5] */
  for (rr=(&w17), ss=w14+5; ss!=w14+6; ss+=1) *rr++ = *ss;
  /* #39: @18 = (@17*@16) */
  w18  = (w17*w16);
  /* #40: @18 = (-@18) */
  w18 = (- w18 );
  /* #41: (@13[1] += @18) */
  for (rr=w13+1, ss=(&w18); rr!=w13+2; rr+=1) *rr += *ss++;
  /* #42: @18 = @14[4] */
  for (rr=(&w18), ss=w14+4; ss!=w14+5; ss+=1) *rr++ = *ss;
  /* #43: @19 = (@18*@16) */
  w19  = (w18*w16);
  /* #44: (@13[2] += @19) */
  for (rr=w13+2, ss=(&w19); rr!=w13+3; rr+=1) *rr += *ss++;
  /* #45: @19 = @14[3] */
  for (rr=(&w19), ss=w14+3; ss!=w14+4; ss+=1) *rr++ = *ss;
  /* #46: @16 = (@19*@16) */
  w16  = (w19*w16);
  /* #47: (@13[3] += @16) */
  for (rr=w13+3, ss=(&w16); rr!=w13+4; rr+=1) *rr += *ss++;
  /* #48: @16 = (@6*@15) */
  w16  = (w6*w15);
  /* #49: (@13[1] += @16) */
  for (rr=w13+1, ss=(&w16); rr!=w13+2; rr+=1) *rr += *ss++;
  /* #50: @16 = (@17*@15) */
  w16  = (w17*w15);
  /* #51: (@13[0] += @16) */
  for (rr=w13+0, ss=(&w16); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #52: @16 = (@18*@15) */
  w16  = (w18*w15);
  /* #53: @16 = (-@16) */
  w16 = (- w16 );
  /* #54: (@13[3] += @16) */
  for (rr=w13+3, ss=(&w16); rr!=w13+4; rr+=1) *rr += *ss++;
  /* #55: @15 = (@19*@15) */
  w15  = (w19*w15);
  /* #56: (@13[2] += @15) */
  for (rr=w13+2, ss=(&w15); rr!=w13+3; rr+=1) *rr += *ss++;
  /* #57: @15 = (@6*@10) */
  w15  = (w6*w10);
  /* #58: @15 = (-@15) */
  w15 = (- w15 );
  /* #59: (@13[2] += @15) */
  for (rr=w13+2, ss=(&w15); rr!=w13+3; rr+=1) *rr += *ss++;
  /* #60: @15 = (@17*@10) */
  w15  = (w17*w10);
  /* #61: (@13[3] += @15) */
  for (rr=w13+3, ss=(&w15); rr!=w13+4; rr+=1) *rr += *ss++;
  /* #62: @15 = (@18*@10) */
  w15  = (w18*w10);
  /* #63: (@13[0] += @15) */
  for (rr=w13+0, ss=(&w15); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #64: @10 = (@19*@10) */
  w10  = (w19*w10);
  /* #65: (@13[1] += @10) */
  for (rr=w13+1, ss=(&w10); rr!=w13+2; rr+=1) *rr += *ss++;
  /* #66: @6 = (@6*@8) */
  w6 *= w8;
  /* #67: @6 = (-@6) */
  w6 = (- w6 );
  /* #68: (@13[3] += @6) */
  for (rr=w13+3, ss=(&w6); rr!=w13+4; rr+=1) *rr += *ss++;
  /* #69: @17 = (@17*@8) */
  w17 *= w8;
  /* #70: @17 = (-@17) */
  w17 = (- w17 );
  /* #71: (@13[2] += @17) */
  for (rr=w13+2, ss=(&w17); rr!=w13+3; rr+=1) *rr += *ss++;
  /* #72: @18 = (@18*@8) */
  w18 *= w8;
  /* #73: @18 = (-@18) */
  w18 = (- w18 );
  /* #74: (@13[1] += @18) */
  for (rr=w13+1, ss=(&w18); rr!=w13+2; rr+=1) *rr += *ss++;
  /* #75: @19 = (@19*@8) */
  w19 *= w8;
  /* #76: (@13[0] += @19) */
  for (rr=w13+0, ss=(&w19); rr!=w13+1; rr+=1) *rr += *ss++;
  /* #77: @19 = dot(@7, @13) */
  w19 = casadi_dot(4, w7, w13);
  /* #78: @19 = (@19/@4) */
  w19 /= w4;
  /* #79: @7 = (-@11) */
  for (i=0, rr=w7, cs=w11; i<4; ++i) *rr++ = (- *cs++ );
  /* #80: @8 = dot(@7, @13) */
  w8 = casadi_dot(4, w7, w13);
  /* #81: @8 = (@8/@4) */
  w8 /= w4;
  /* #82: @18 = (@8/@4) */
  w18  = (w8/w4);
  /* #83: @17 = (@18*@9) */
  w17  = (w18*w9);
  /* #84: @19 = (@19-@17) */
  w19 -= w17;
  /* #85: @7 = (@3*@19) */
  for (i=0, rr=w7, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w19);
  /* #86: @19 = sparsity_cast(@8) */
  casadi_copy((&w8), 1, (&w19));
  /* #87: @20 = dense(@19) */
  casadi_densify((&w19), casadi_s0, w20, 0);
  /* #88: @7 = (@7+@20) */
  for (i=0, rr=w7, cs=w20; i<4; ++i) (*rr++) += (*cs++);
  /* #89: @2 = @1; (@2[3:7] += @7) */
  casadi_copy(w1, 19, w2);
  for (rr=w2+3, ss=w7; rr!=w2+7; rr+=1) *rr += *ss++;
  /* #90: @7 = (@13/@4) */
  for (i=0, rr=w7, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)/w4);
  /* #91: @7 = (@7/@4) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) /= w4;
  /* #92: @20 = (@7*@9) */
  for (i=0, rr=w20, cr=w7; i<4; ++i) (*rr++)  = ((*cr++)*w9);
  /* #93: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #94: {@9, @19, @17, @6} = vertsplit(@20) */
  w9 = w20[0];
  w19 = w20[1];
  w17 = w20[2];
  w6 = w20[3];
  /* #95: @6 = (-@6) */
  w6 = (- w6 );
  /* #96: (@2[6] += @6) */
  for (rr=w2+6, ss=(&w6); rr!=w2+7; rr+=1) *rr += *ss++;
  /* #97: @17 = (-@17) */
  w17 = (- w17 );
  /* #98: (@2[5] += @17) */
  for (rr=w2+5, ss=(&w17); rr!=w2+6; rr+=1) *rr += *ss++;
  /* #99: @19 = (-@19) */
  w19 = (- w19 );
  /* #100: (@2[4] += @19) */
  for (rr=w2+4, ss=(&w19); rr!=w2+5; rr+=1) *rr += *ss++;
  /* #101: (@2[3] += @9) */
  for (rr=w2+3, ss=(&w9); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #102: @20 = @2[3:7] */
  for (rr=w20, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #103: (@0[:16:4] = @20) */
  for (rr=w0+0, ss=w20; rr!=w0+16; rr+=4) *rr = *ss++;
  /* #104: @9 = -1 */
  w9 = -1.;
  /* #105: @19 = vertcat(@5, @9, @5, @5) */
  rr=(&w19);
  *rr++ = w9;
  /* #106: @19 = (@19/@4) */
  w19 /= w4;
  /* #107: @20 = dense(@19) */
  casadi_densify((&w19), casadi_s1, w20, 0);
  /* #108: @19 = project(@3) */
  casadi_sparsify(w3, (&w19), casadi_s1, 0);
  /* #109: @17 = ones(4x1,1nz) */
  w17 = 1.;
  /* #110: @6 = dot(@19, @17) */
  w6 = casadi_dot(1, (&w19), (&w17));
  /* #111: @6 = (@6/@4) */
  w6 /= w4;
  /* #112: @21 = (@11*@6) */
  for (i=0, rr=w21, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #113: @20 = (@20-@21) */
  for (i=0, rr=w20, cs=w21; i<4; ++i) (*rr++) -= (*cs++);
  /* #114: @20 = (@20/@4) */
  for (i=0, rr=w20; i<4; ++i) (*rr++) /= w4;
  /* #115: @21 = (@12*@6) */
  for (i=0, rr=w21, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #116: @20 = (@20-@21) */
  for (i=0, rr=w20, cs=w21; i<4; ++i) (*rr++) -= (*cs++);
  /* #117: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #118: @19 = dot(@20, @13) */
  w19 = casadi_dot(4, w20, w13);
  /* #119: @19 = (@19/@4) */
  w19 /= w4;
  /* #120: @17 = (@18*@6) */
  w17  = (w18*w6);
  /* #121: @19 = (@19-@17) */
  w19 -= w17;
  /* #122: @20 = (@3*@19) */
  for (i=0, rr=w20, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w19);
  /* #123: @19 = sparsity_cast(@8) */
  casadi_copy((&w8), 1, (&w19));
  /* #124: @21 = dense(@19) */
  casadi_densify((&w19), casadi_s1, w21, 0);
  /* #125: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<4; ++i) (*rr++) += (*cs++);
  /* #126: @2 = @1; (@2[3:7] += @20) */
  casadi_copy(w1, 19, w2);
  for (rr=w2+3, ss=w20; rr!=w2+7; rr+=1) *rr += *ss++;
  /* #127: @20 = (@7*@6) */
  for (i=0, rr=w20, cr=w7; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #128: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #129: {@6, @19, @17, @10} = vertsplit(@20) */
  w6 = w20[0];
  w19 = w20[1];
  w17 = w20[2];
  w10 = w20[3];
  /* #130: @10 = (-@10) */
  w10 = (- w10 );
  /* #131: (@2[6] += @10) */
  for (rr=w2+6, ss=(&w10); rr!=w2+7; rr+=1) *rr += *ss++;
  /* #132: @17 = (-@17) */
  w17 = (- w17 );
  /* #133: (@2[5] += @17) */
  for (rr=w2+5, ss=(&w17); rr!=w2+6; rr+=1) *rr += *ss++;
  /* #134: @19 = (-@19) */
  w19 = (- w19 );
  /* #135: (@2[4] += @19) */
  for (rr=w2+4, ss=(&w19); rr!=w2+5; rr+=1) *rr += *ss++;
  /* #136: (@2[3] += @6) */
  for (rr=w2+3, ss=(&w6); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #137: @20 = @2[3:7] */
  for (rr=w20, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #138: (@0[1:17:4] = @20) */
  for (rr=w0+1, ss=w20; rr!=w0+17; rr+=4) *rr = *ss++;
  /* #139: @6 = vertcat(@5, @5, @9, @5) */
  rr=(&w6);
  *rr++ = w9;
  /* #140: @6 = (@6/@4) */
  w6 /= w4;
  /* #141: @20 = dense(@6) */
  casadi_densify((&w6), casadi_s2, w20, 0);
  /* #142: @6 = project(@3) */
  casadi_sparsify(w3, (&w6), casadi_s2, 0);
  /* #143: @19 = ones(4x1,1nz) */
  w19 = 1.;
  /* #144: @17 = dot(@6, @19) */
  w17 = casadi_dot(1, (&w6), (&w19));
  /* #145: @17 = (@17/@4) */
  w17 /= w4;
  /* #146: @21 = (@11*@17) */
  for (i=0, rr=w21, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #147: @20 = (@20-@21) */
  for (i=0, rr=w20, cs=w21; i<4; ++i) (*rr++) -= (*cs++);
  /* #148: @20 = (@20/@4) */
  for (i=0, rr=w20; i<4; ++i) (*rr++) /= w4;
  /* #149: @21 = (@12*@17) */
  for (i=0, rr=w21, cr=w12; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #150: @20 = (@20-@21) */
  for (i=0, rr=w20, cs=w21; i<4; ++i) (*rr++) -= (*cs++);
  /* #151: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #152: @6 = dot(@20, @13) */
  w6 = casadi_dot(4, w20, w13);
  /* #153: @6 = (@6/@4) */
  w6 /= w4;
  /* #154: @19 = (@18*@17) */
  w19  = (w18*w17);
  /* #155: @6 = (@6-@19) */
  w6 -= w19;
  /* #156: @20 = (@3*@6) */
  for (i=0, rr=w20, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w6);
  /* #157: @6 = sparsity_cast(@8) */
  casadi_copy((&w8), 1, (&w6));
  /* #158: @21 = dense(@6) */
  casadi_densify((&w6), casadi_s2, w21, 0);
  /* #159: @20 = (@20+@21) */
  for (i=0, rr=w20, cs=w21; i<4; ++i) (*rr++) += (*cs++);
  /* #160: @2 = @1; (@2[3:7] += @20) */
  casadi_copy(w1, 19, w2);
  for (rr=w2+3, ss=w20; rr!=w2+7; rr+=1) *rr += *ss++;
  /* #161: @20 = (@7*@17) */
  for (i=0, rr=w20, cr=w7; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #162: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #163: {@17, @6, @19, @10} = vertsplit(@20) */
  w17 = w20[0];
  w6 = w20[1];
  w19 = w20[2];
  w10 = w20[3];
  /* #164: @10 = (-@10) */
  w10 = (- w10 );
  /* #165: (@2[6] += @10) */
  for (rr=w2+6, ss=(&w10); rr!=w2+7; rr+=1) *rr += *ss++;
  /* #166: @19 = (-@19) */
  w19 = (- w19 );
  /* #167: (@2[5] += @19) */
  for (rr=w2+5, ss=(&w19); rr!=w2+6; rr+=1) *rr += *ss++;
  /* #168: @6 = (-@6) */
  w6 = (- w6 );
  /* #169: (@2[4] += @6) */
  for (rr=w2+4, ss=(&w6); rr!=w2+5; rr+=1) *rr += *ss++;
  /* #170: (@2[3] += @17) */
  for (rr=w2+3, ss=(&w17); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #171: @20 = @2[3:7] */
  for (rr=w20, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #172: (@0[2:18:4] = @20) */
  for (rr=w0+2, ss=w20; rr!=w0+18; rr+=4) *rr = *ss++;
  /* #173: @17 = vertcat(@5, @5, @5, @9) */
  rr=(&w17);
  *rr++ = w9;
  /* #174: @17 = (@17/@4) */
  w17 /= w4;
  /* #175: @20 = dense(@17) */
  casadi_densify((&w17), casadi_s3, w20, 0);
  /* #176: @17 = project(@3) */
  casadi_sparsify(w3, (&w17), casadi_s3, 0);
  /* #177: @9 = ones(4x1,1nz) */
  w9 = 1.;
  /* #178: @6 = dot(@17, @9) */
  w6 = casadi_dot(1, (&w17), (&w9));
  /* #179: @6 = (@6/@4) */
  w6 /= w4;
  /* #180: @11 = (@11*@6) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) *= w6;
  /* #181: @20 = (@20-@11) */
  for (i=0, rr=w20, cs=w11; i<4; ++i) (*rr++) -= (*cs++);
  /* #182: @20 = (@20/@4) */
  for (i=0, rr=w20; i<4; ++i) (*rr++) /= w4;
  /* #183: @12 = (@12*@6) */
  for (i=0, rr=w12; i<4; ++i) (*rr++) *= w6;
  /* #184: @20 = (@20-@12) */
  for (i=0, rr=w20, cs=w12; i<4; ++i) (*rr++) -= (*cs++);
  /* #185: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #186: @17 = dot(@20, @13) */
  w17 = casadi_dot(4, w20, w13);
  /* #187: @17 = (@17/@4) */
  w17 /= w4;
  /* #188: @18 = (@18*@6) */
  w18 *= w6;
  /* #189: @17 = (@17-@18) */
  w17 -= w18;
  /* #190: @3 = (@3*@17) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) *= w17;
  /* #191: @8 = sparsity_cast(@8) */
  /* #192: @20 = dense(@8) */
  casadi_densify((&w8), casadi_s3, w20, 0);
  /* #193: @3 = (@3+@20) */
  for (i=0, rr=w3, cs=w20; i<4; ++i) (*rr++) += (*cs++);
  /* #194: (@1[3:7] += @3) */
  for (rr=w1+3, ss=w3; rr!=w1+7; rr+=1) *rr += *ss++;
  /* #195: @7 = (@7*@6) */
  for (i=0, rr=w7; i<4; ++i) (*rr++) *= w6;
  /* #196: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<4; ++i) *rr++ = (- *cs++ );
  /* #197: {@6, @8, @17, @18} = vertsplit(@7) */
  w6 = w7[0];
  w8 = w7[1];
  w17 = w7[2];
  w18 = w7[3];
  /* #198: @18 = (-@18) */
  w18 = (- w18 );
  /* #199: (@1[6] += @18) */
  for (rr=w1+6, ss=(&w18); rr!=w1+7; rr+=1) *rr += *ss++;
  /* #200: @17 = (-@17) */
  w17 = (- w17 );
  /* #201: (@1[5] += @17) */
  for (rr=w1+5, ss=(&w17); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #202: @8 = (-@8) */
  w8 = (- w8 );
  /* #203: (@1[4] += @8) */
  for (rr=w1+4, ss=(&w8); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #204: (@1[3] += @6) */
  for (rr=w1+3, ss=(&w6); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #205: @7 = @1[3:7] */
  for (rr=w7, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #206: (@0[3:19:4] = @7) */
  for (rr=w0+3, ss=w7; rr!=w0+19; rr+=4) *rr = *ss++;
  /* #207: @22 = @0' */
  casadi_trans(w0,casadi_s4, w22, casadi_s4, iw);
  /* #208: output[0][0] = @22 */
  casadi_copy(w22, 16, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real SAM_equation_system_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    case 5: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 20;
  if (sz_w) *sz_w = 133;
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 20*sizeof(casadi_int);
  if (sz_w) *sz_w = 133*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
