/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) SAM_equation_system_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s4[44] = {25, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 8, 12, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12, 9, 10, 11, 12};
static const casadi_int casadi_s5[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[4] = {0, 1, 0, 0};
static const casadi_int casadi_s8[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s9[3] = {0, 0, 0};

/* SAM_equation_system_cost_y_hess:(i0[19],i1[6],i2[0],i3[25],i4[],i5[25])->(o0[25x25,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+16, *w2=w+35, *w3=w+54, *w4=w+58, *w5=w+80, w6, w8, *w9=w+98, w10, w11, w12, *w13=w+105, *w14=w+109, *w15=w+113, *w16=w+117, *w17=w+142, w18, w19, w20, w21, w22, w23, *w24=w+173, *w25=w+177;
  /* #0: @0 = zeros(25x25,16nz) */
  casadi_clear(w0, 16);
  /* #1: @1 = zeros(19x1) */
  casadi_clear(w1, 19);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 19, w2);
  /* #3: @3 = @2[3:7] */
  for (rr=w3, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #4: @4 = ones(25x1,22nz) */
  casadi_fill(w4, 22, 1.);
  /* #5: {NULL, @5} = vertsplit(@4) */
  casadi_copy(w4+6, 16, w5);
  /* #6: @6 = @5[3] */
  for (rr=(&w6), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #7: @7 = 00 */
  /* #8: @8 = vertcat(@6, @7, @7, @7) */
  rr=(&w8);
  *rr++ = w6;
  /* #9: @6 = ||@3||_F */
  w6 = sqrt(casadi_dot(4, w3, w3));
  /* #10: @8 = (@8/@6) */
  w8 /= w6;
  /* #11: @9 = dense(@8) */
  casadi_densify((&w8), casadi_s0, w9, 0);
  /* #12: @8 = @2[3] */
  for (rr=(&w8), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #13: @10 = @2[4] */
  for (rr=(&w10), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #14: @10 = (-@10) */
  w10 = (- w10 );
  /* #15: @11 = @2[5] */
  for (rr=(&w11), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #16: @11 = (-@11) */
  w11 = (- w11 );
  /* #17: @12 = @2[6] */
  for (rr=(&w12), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #18: @12 = (-@12) */
  w12 = (- w12 );
  /* #19: @13 = vertcat(@8, @10, @11, @12) */
  rr=w13;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #20: @13 = (@13/@6) */
  for (i=0, rr=w13; i<4; ++i) (*rr++) /= w6;
  /* #21: @13 = (@13/@6) */
  for (i=0, rr=w13; i<4; ++i) (*rr++) /= w6;
  /* #22: @8 = project(@3) */
  casadi_sparsify(w3, (&w8), casadi_s0, 0);
  /* #23: @10 = @5[3] */
  for (rr=(&w10), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #24: @11 = dot(@8, @10) */
  w11 = casadi_dot(1, (&w8), (&w10));
  /* #25: @11 = (@11/@6) */
  w11 /= w6;
  /* #26: @14 = (@13*@11) */
  for (i=0, rr=w14, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)*w11);
  /* #27: @9 = (@9-@14) */
  for (i=0, rr=w9, cs=w14; i<4; ++i) (*rr++) -= (*cs++);
  /* #28: @9 = (@9/@6) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w6;
  /* #29: @14 = (@13/@6) */
  for (i=0, rr=w14, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)/w6);
  /* #30: @15 = (@14*@11) */
  for (i=0, rr=w15, cr=w14; i<4; ++i) (*rr++)  = ((*cr++)*w11);
  /* #31: @9 = (@9-@15) */
  for (i=0, rr=w9, cs=w15; i<4; ++i) (*rr++) -= (*cs++);
  /* #32: @9 = (-@9) */
  for (i=0, rr=w9, cs=w9; i<4; ++i) *rr++ = (- *cs++ );
  /* #33: @15 = zeros(4x1) */
  casadi_clear(w15, 4);
  /* #34: @16 = input[5][0] */
  casadi_copy(arg[5], 25, w16);
  /* #35: @8 = @16[6] */
  for (rr=(&w8), ss=w16+6; ss!=w16+7; ss+=1) *rr++ = *ss;
  /* #36: @17 = input[3][0] */
  casadi_copy(arg[3], 25, w17);
  /* #37: {NULL, @12, @18, @19, @20, NULL, NULL, NULL} = vertsplit(@17) */
  w12 = w17[3];
  w18 = w17[4];
  w19 = w17[5];
  w20 = w17[6];
  /* #38: @21 = (@8*@20) */
  w21  = (w8*w20);
  /* #39: (@15[0] += @21) */
  for (rr=w15+0, ss=(&w21); rr!=w15+1; rr+=1) *rr += *ss++;
  /* #40: @21 = @16[5] */
  for (rr=(&w21), ss=w16+5; ss!=w16+6; ss+=1) *rr++ = *ss;
  /* #41: @22 = (@21*@20) */
  w22  = (w21*w20);
  /* #42: @22 = (-@22) */
  w22 = (- w22 );
  /* #43: (@15[1] += @22) */
  for (rr=w15+1, ss=(&w22); rr!=w15+2; rr+=1) *rr += *ss++;
  /* #44: @22 = @16[4] */
  for (rr=(&w22), ss=w16+4; ss!=w16+5; ss+=1) *rr++ = *ss;
  /* #45: @23 = (@22*@20) */
  w23  = (w22*w20);
  /* #46: (@15[2] += @23) */
  for (rr=w15+2, ss=(&w23); rr!=w15+3; rr+=1) *rr += *ss++;
  /* #47: @23 = @16[3] */
  for (rr=(&w23), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #48: @20 = (@23*@20) */
  w20  = (w23*w20);
  /* #49: (@15[3] += @20) */
  for (rr=w15+3, ss=(&w20); rr!=w15+4; rr+=1) *rr += *ss++;
  /* #50: @20 = (@8*@19) */
  w20  = (w8*w19);
  /* #51: (@15[1] += @20) */
  for (rr=w15+1, ss=(&w20); rr!=w15+2; rr+=1) *rr += *ss++;
  /* #52: @20 = (@21*@19) */
  w20  = (w21*w19);
  /* #53: (@15[0] += @20) */
  for (rr=w15+0, ss=(&w20); rr!=w15+1; rr+=1) *rr += *ss++;
  /* #54: @20 = (@22*@19) */
  w20  = (w22*w19);
  /* #55: @20 = (-@20) */
  w20 = (- w20 );
  /* #56: (@15[3] += @20) */
  for (rr=w15+3, ss=(&w20); rr!=w15+4; rr+=1) *rr += *ss++;
  /* #57: @19 = (@23*@19) */
  w19  = (w23*w19);
  /* #58: (@15[2] += @19) */
  for (rr=w15+2, ss=(&w19); rr!=w15+3; rr+=1) *rr += *ss++;
  /* #59: @19 = (@8*@18) */
  w19  = (w8*w18);
  /* #60: @19 = (-@19) */
  w19 = (- w19 );
  /* #61: (@15[2] += @19) */
  for (rr=w15+2, ss=(&w19); rr!=w15+3; rr+=1) *rr += *ss++;
  /* #62: @19 = (@21*@18) */
  w19  = (w21*w18);
  /* #63: (@15[3] += @19) */
  for (rr=w15+3, ss=(&w19); rr!=w15+4; rr+=1) *rr += *ss++;
  /* #64: @19 = (@22*@18) */
  w19  = (w22*w18);
  /* #65: (@15[0] += @19) */
  for (rr=w15+0, ss=(&w19); rr!=w15+1; rr+=1) *rr += *ss++;
  /* #66: @18 = (@23*@18) */
  w18  = (w23*w18);
  /* #67: (@15[1] += @18) */
  for (rr=w15+1, ss=(&w18); rr!=w15+2; rr+=1) *rr += *ss++;
  /* #68: @8 = (@8*@12) */
  w8 *= w12;
  /* #69: @8 = (-@8) */
  w8 = (- w8 );
  /* #70: (@15[3] += @8) */
  for (rr=w15+3, ss=(&w8); rr!=w15+4; rr+=1) *rr += *ss++;
  /* #71: @21 = (@21*@12) */
  w21 *= w12;
  /* #72: @21 = (-@21) */
  w21 = (- w21 );
  /* #73: (@15[2] += @21) */
  for (rr=w15+2, ss=(&w21); rr!=w15+3; rr+=1) *rr += *ss++;
  /* #74: @22 = (@22*@12) */
  w22 *= w12;
  /* #75: @22 = (-@22) */
  w22 = (- w22 );
  /* #76: (@15[1] += @22) */
  for (rr=w15+1, ss=(&w22); rr!=w15+2; rr+=1) *rr += *ss++;
  /* #77: @23 = (@23*@12) */
  w23 *= w12;
  /* #78: (@15[0] += @23) */
  for (rr=w15+0, ss=(&w23); rr!=w15+1; rr+=1) *rr += *ss++;
  /* #79: @23 = dot(@9, @15) */
  w23 = casadi_dot(4, w9, w15);
  /* #80: @23 = (@23/@6) */
  w23 /= w6;
  /* #81: @9 = (-@13) */
  for (i=0, rr=w9, cs=w13; i<4; ++i) *rr++ = (- *cs++ );
  /* #82: @12 = dot(@9, @15) */
  w12 = casadi_dot(4, w9, w15);
  /* #83: @12 = (@12/@6) */
  w12 /= w6;
  /* #84: @22 = (@12/@6) */
  w22  = (w12/w6);
  /* #85: @21 = (@22*@11) */
  w21  = (w22*w11);
  /* #86: @23 = (@23-@21) */
  w23 -= w21;
  /* #87: @9 = (@3*@23) */
  for (i=0, rr=w9, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #88: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #89: @24 = dense(@10) */
  casadi_densify((&w10), casadi_s0, w24, 0);
  /* #90: @9 = (@9+@24) */
  for (i=0, rr=w9, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #91: @2 = @1; (@2[3:7] += @9) */
  casadi_copy(w1, 19, w2);
  for (rr=w2+3, ss=w9; rr!=w2+7; rr+=1) *rr += *ss++;
  /* #92: @9 = (@15/@6) */
  for (i=0, rr=w9, cr=w15; i<4; ++i) (*rr++)  = ((*cr++)/w6);
  /* #93: @9 = (@9/@6) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w6;
  /* #94: @24 = (@9*@11) */
  for (i=0, rr=w24, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w11);
  /* #95: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #96: {@11, @10, @23, @21} = vertsplit(@24) */
  w11 = w24[0];
  w10 = w24[1];
  w23 = w24[2];
  w21 = w24[3];
  /* #97: @21 = (-@21) */
  w21 = (- w21 );
  /* #98: (@2[6] += @21) */
  for (rr=w2+6, ss=(&w21); rr!=w2+7; rr+=1) *rr += *ss++;
  /* #99: @23 = (-@23) */
  w23 = (- w23 );
  /* #100: (@2[5] += @23) */
  for (rr=w2+5, ss=(&w23); rr!=w2+6; rr+=1) *rr += *ss++;
  /* #101: @10 = (-@10) */
  w10 = (- w10 );
  /* #102: (@2[4] += @10) */
  for (rr=w2+4, ss=(&w10); rr!=w2+5; rr+=1) *rr += *ss++;
  /* #103: (@2[3] += @11) */
  for (rr=w2+3, ss=(&w11); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #104: @24 = @2[3:7] */
  for (rr=w24, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #105: (@0[:16:4] = @24) */
  for (rr=w0+0, ss=w24; rr!=w0+16; rr+=4) *rr = *ss++;
  /* #106: @11 = ones(25x1,1nz) */
  w11 = 1.;
  /* #107: {NULL, @10} = vertsplit(@11) */
  w10 = w11;
  /* #108: @11 = @10[0] */
  for (rr=(&w11), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #109: @11 = (-@11) */
  w11 = (- w11 );
  /* #110: @23 = vertcat(@7, @11, @7, @7) */
  rr=(&w23);
  *rr++ = w11;
  /* #111: @23 = (@23/@6) */
  w23 /= w6;
  /* #112: @24 = dense(@23) */
  casadi_densify((&w23), casadi_s1, w24, 0);
  /* #113: @23 = project(@3) */
  casadi_sparsify(w3, (&w23), casadi_s1, 0);
  /* #114: @11 = @10[0] */
  for (rr=(&w11), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #115: @10 = dot(@23, @11) */
  w10 = casadi_dot(1, (&w23), (&w11));
  /* #116: @10 = (@10/@6) */
  w10 /= w6;
  /* #117: @25 = (@13*@10) */
  for (i=0, rr=w25, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)*w10);
  /* #118: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #119: @24 = (@24/@6) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w6;
  /* #120: @25 = (@14*@10) */
  for (i=0, rr=w25, cr=w14; i<4; ++i) (*rr++)  = ((*cr++)*w10);
  /* #121: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #122: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #123: @23 = dot(@24, @15) */
  w23 = casadi_dot(4, w24, w15);
  /* #124: @23 = (@23/@6) */
  w23 /= w6;
  /* #125: @21 = (@22*@10) */
  w21  = (w22*w10);
  /* #126: @23 = (@23-@21) */
  w23 -= w21;
  /* #127: @24 = (@3*@23) */
  for (i=0, rr=w24, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #128: @11 = (@12*@11) */
  w11  = (w12*w11);
  /* #129: @25 = dense(@11) */
  casadi_densify((&w11), casadi_s1, w25, 0);
  /* #130: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #131: @2 = @1; (@2[3:7] += @24) */
  casadi_copy(w1, 19, w2);
  for (rr=w2+3, ss=w24; rr!=w2+7; rr+=1) *rr += *ss++;
  /* #132: @24 = (@9*@10) */
  for (i=0, rr=w24, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w10);
  /* #133: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #134: {@10, @11, @23, @21} = vertsplit(@24) */
  w10 = w24[0];
  w11 = w24[1];
  w23 = w24[2];
  w21 = w24[3];
  /* #135: @21 = (-@21) */
  w21 = (- w21 );
  /* #136: (@2[6] += @21) */
  for (rr=w2+6, ss=(&w21); rr!=w2+7; rr+=1) *rr += *ss++;
  /* #137: @23 = (-@23) */
  w23 = (- w23 );
  /* #138: (@2[5] += @23) */
  for (rr=w2+5, ss=(&w23); rr!=w2+6; rr+=1) *rr += *ss++;
  /* #139: @11 = (-@11) */
  w11 = (- w11 );
  /* #140: (@2[4] += @11) */
  for (rr=w2+4, ss=(&w11); rr!=w2+5; rr+=1) *rr += *ss++;
  /* #141: (@2[3] += @10) */
  for (rr=w2+3, ss=(&w10); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #142: @24 = @2[3:7] */
  for (rr=w24, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #143: (@0[1:17:4] = @24) */
  for (rr=w0+1, ss=w24; rr!=w0+17; rr+=4) *rr = *ss++;
  /* #144: @10 = ones(25x1,1nz) */
  w10 = 1.;
  /* #145: {NULL, @11} = vertsplit(@10) */
  w11 = w10;
  /* #146: @10 = @11[0] */
  for (rr=(&w10), ss=(&w11)+0; ss!=(&w11)+1; ss+=1) *rr++ = *ss;
  /* #147: @10 = (-@10) */
  w10 = (- w10 );
  /* #148: @23 = vertcat(@7, @7, @10, @7) */
  rr=(&w23);
  *rr++ = w10;
  /* #149: @23 = (@23/@6) */
  w23 /= w6;
  /* #150: @24 = dense(@23) */
  casadi_densify((&w23), casadi_s2, w24, 0);
  /* #151: @23 = project(@3) */
  casadi_sparsify(w3, (&w23), casadi_s2, 0);
  /* #152: @10 = @11[0] */
  for (rr=(&w10), ss=(&w11)+0; ss!=(&w11)+1; ss+=1) *rr++ = *ss;
  /* #153: @11 = dot(@23, @10) */
  w11 = casadi_dot(1, (&w23), (&w10));
  /* #154: @11 = (@11/@6) */
  w11 /= w6;
  /* #155: @25 = (@13*@11) */
  for (i=0, rr=w25, cr=w13; i<4; ++i) (*rr++)  = ((*cr++)*w11);
  /* #156: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #157: @24 = (@24/@6) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w6;
  /* #158: @25 = (@14*@11) */
  for (i=0, rr=w25, cr=w14; i<4; ++i) (*rr++)  = ((*cr++)*w11);
  /* #159: @24 = (@24-@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++) -= (*cs++);
  /* #160: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #161: @23 = dot(@24, @15) */
  w23 = casadi_dot(4, w24, w15);
  /* #162: @23 = (@23/@6) */
  w23 /= w6;
  /* #163: @21 = (@22*@11) */
  w21  = (w22*w11);
  /* #164: @23 = (@23-@21) */
  w23 -= w21;
  /* #165: @24 = (@3*@23) */
  for (i=0, rr=w24, cr=w3; i<4; ++i) (*rr++)  = ((*cr++)*w23);
  /* #166: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #167: @25 = dense(@10) */
  casadi_densify((&w10), casadi_s2, w25, 0);
  /* #168: @24 = (@24+@25) */
  for (i=0, rr=w24, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #169: @2 = @1; (@2[3:7] += @24) */
  casadi_copy(w1, 19, w2);
  for (rr=w2+3, ss=w24; rr!=w2+7; rr+=1) *rr += *ss++;
  /* #170: @24 = (@9*@11) */
  for (i=0, rr=w24, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w11);
  /* #171: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #172: {@11, @10, @23, @21} = vertsplit(@24) */
  w11 = w24[0];
  w10 = w24[1];
  w23 = w24[2];
  w21 = w24[3];
  /* #173: @21 = (-@21) */
  w21 = (- w21 );
  /* #174: (@2[6] += @21) */
  for (rr=w2+6, ss=(&w21); rr!=w2+7; rr+=1) *rr += *ss++;
  /* #175: @23 = (-@23) */
  w23 = (- w23 );
  /* #176: (@2[5] += @23) */
  for (rr=w2+5, ss=(&w23); rr!=w2+6; rr+=1) *rr += *ss++;
  /* #177: @10 = (-@10) */
  w10 = (- w10 );
  /* #178: (@2[4] += @10) */
  for (rr=w2+4, ss=(&w10); rr!=w2+5; rr+=1) *rr += *ss++;
  /* #179: (@2[3] += @11) */
  for (rr=w2+3, ss=(&w11); rr!=w2+4; rr+=1) *rr += *ss++;
  /* #180: @24 = @2[3:7] */
  for (rr=w24, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #181: (@0[2:18:4] = @24) */
  for (rr=w0+2, ss=w24; rr!=w0+18; rr+=4) *rr = *ss++;
  /* #182: @11 = ones(25x1,1nz) */
  w11 = 1.;
  /* #183: {NULL, @10} = vertsplit(@11) */
  w10 = w11;
  /* #184: @11 = @10[0] */
  for (rr=(&w11), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #185: @11 = (-@11) */
  w11 = (- w11 );
  /* #186: @23 = vertcat(@7, @7, @7, @11) */
  rr=(&w23);
  *rr++ = w11;
  /* #187: @23 = (@23/@6) */
  w23 /= w6;
  /* #188: @24 = dense(@23) */
  casadi_densify((&w23), casadi_s3, w24, 0);
  /* #189: @23 = project(@3) */
  casadi_sparsify(w3, (&w23), casadi_s3, 0);
  /* #190: @11 = @10[0] */
  for (rr=(&w11), ss=(&w10)+0; ss!=(&w10)+1; ss+=1) *rr++ = *ss;
  /* #191: @10 = dot(@23, @11) */
  w10 = casadi_dot(1, (&w23), (&w11));
  /* #192: @10 = (@10/@6) */
  w10 /= w6;
  /* #193: @13 = (@13*@10) */
  for (i=0, rr=w13; i<4; ++i) (*rr++) *= w10;
  /* #194: @24 = (@24-@13) */
  for (i=0, rr=w24, cs=w13; i<4; ++i) (*rr++) -= (*cs++);
  /* #195: @24 = (@24/@6) */
  for (i=0, rr=w24; i<4; ++i) (*rr++) /= w6;
  /* #196: @14 = (@14*@10) */
  for (i=0, rr=w14; i<4; ++i) (*rr++) *= w10;
  /* #197: @24 = (@24-@14) */
  for (i=0, rr=w24, cs=w14; i<4; ++i) (*rr++) -= (*cs++);
  /* #198: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) *rr++ = (- *cs++ );
  /* #199: @23 = dot(@24, @15) */
  w23 = casadi_dot(4, w24, w15);
  /* #200: @23 = (@23/@6) */
  w23 /= w6;
  /* #201: @22 = (@22*@10) */
  w22 *= w10;
  /* #202: @23 = (@23-@22) */
  w23 -= w22;
  /* #203: @3 = (@3*@23) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) *= w23;
  /* #204: @12 = (@12*@11) */
  w12 *= w11;
  /* #205: @24 = dense(@12) */
  casadi_densify((&w12), casadi_s3, w24, 0);
  /* #206: @3 = (@3+@24) */
  for (i=0, rr=w3, cs=w24; i<4; ++i) (*rr++) += (*cs++);
  /* #207: (@1[3:7] += @3) */
  for (rr=w1+3, ss=w3; rr!=w1+7; rr+=1) *rr += *ss++;
  /* #208: @9 = (@9*@10) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) *= w10;
  /* #209: @9 = (-@9) */
  for (i=0, rr=w9, cs=w9; i<4; ++i) *rr++ = (- *cs++ );
  /* #210: {@10, @12, @11, @23} = vertsplit(@9) */
  w10 = w9[0];
  w12 = w9[1];
  w11 = w9[2];
  w23 = w9[3];
  /* #211: @23 = (-@23) */
  w23 = (- w23 );
  /* #212: (@1[6] += @23) */
  for (rr=w1+6, ss=(&w23); rr!=w1+7; rr+=1) *rr += *ss++;
  /* #213: @11 = (-@11) */
  w11 = (- w11 );
  /* #214: (@1[5] += @11) */
  for (rr=w1+5, ss=(&w11); rr!=w1+6; rr+=1) *rr += *ss++;
  /* #215: @12 = (-@12) */
  w12 = (- w12 );
  /* #216: (@1[4] += @12) */
  for (rr=w1+4, ss=(&w12); rr!=w1+5; rr+=1) *rr += *ss++;
  /* #217: (@1[3] += @10) */
  for (rr=w1+3, ss=(&w10); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #218: @9 = @1[3:7] */
  for (rr=w9, ss=w1+3; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #219: (@0[3:19:4] = @9) */
  for (rr=w0+3, ss=w9; rr!=w0+19; rr+=4) *rr = *ss++;
  /* #220: @5 = @0' */
  casadi_trans(w0,casadi_s4, w5, casadi_s4, iw);
  /* #221: output[0][0] = @5 */
  casadi_copy(w5, 16, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real SAM_equation_system_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    case 5: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 26;
  if (sz_w) *sz_w = 181;
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 26*sizeof(casadi_int);
  if (sz_w) *sz_w = 181*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
