/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) SAM_equation_system_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[19] = {0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30};
static const casadi_int casadi_s2[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s3[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s4[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s5[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[4] = {0, 1, 0, 0};
static const casadi_int casadi_s8[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s9[53] = {19, 19, 0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 0, 1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s10[3] = {19, 0, 0};

/* SAM_equation_system_cost_y_e_fun_jac_ut_xt:(i0[19],i1[],i2[0],i3[],i4[25])->(o0[19],o1[19x19,31nz],o2[19x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+19, *w2=w+22, *w3=w+47, w4, w5, w6, w7, w8, *w9=w+55, *w10=w+59, w11, w12, w13, w14, w15, w16, *w17=w+69, *w18=w+75, *w19=w+81, *w21=w+112, *w22=w+116, w23, w24, w26;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 19, w0);
  /* #1: @1 = @0[:3] */
  for (rr=w1, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #2: @2 = input[4][0] */
  casadi_copy(arg[4], 25, w2);
  /* #3: @3 = @2[:3] */
  for (rr=w3, ss=w2+0; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #4: @1 = (@1-@3) */
  for (i=0, rr=w1, cs=w3; i<3; ++i) (*rr++) -= (*cs++);
  /* #5: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #6: @4 = @2[3] */
  for (rr=(&w4), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #7: @5 = @0[3] */
  for (rr=(&w5), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #8: @6 = @0[4] */
  for (rr=(&w6), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #9: @6 = (-@6) */
  w6 = (- w6 );
  /* #10: @7 = @0[5] */
  for (rr=(&w7), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #11: @7 = (-@7) */
  w7 = (- w7 );
  /* #12: @8 = @0[6] */
  for (rr=(&w8), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #13: @8 = (-@8) */
  w8 = (- w8 );
  /* #14: @9 = vertcat(@5, @6, @7, @8) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  /* #15: @10 = @0[3:7] */
  for (rr=w10, ss=w0+3; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #16: @5 = ||@10||_F */
  w5 = sqrt(casadi_dot(4, w10, w10));
  /* #17: @9 = (@9/@5) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w5;
  /* #18: @6 = @9[0] */
  for (rr=(&w6), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #19: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #20: @8 = @2[4] */
  for (rr=(&w8), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #21: @11 = @9[1] */
  for (rr=(&w11), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #22: @12 = (@8*@11) */
  w12  = (w8*w11);
  /* #23: @7 = (@7-@12) */
  w7 -= w12;
  /* #24: @12 = @2[5] */
  for (rr=(&w12), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #25: @13 = @9[2] */
  for (rr=(&w13), ss=w9+2; ss!=w9+3; ss+=1) *rr++ = *ss;
  /* #26: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #27: @7 = (@7-@14) */
  w7 -= w14;
  /* #28: @14 = @2[6] */
  for (rr=(&w14), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #29: @15 = @9[3] */
  for (rr=(&w15), ss=w9+3; ss!=w9+4; ss+=1) *rr++ = *ss;
  /* #30: @16 = (@14*@15) */
  w16  = (w14*w15);
  /* #31: @7 = (@7-@16) */
  w7 -= w16;
  /* #32: output[0][1] = @7 */
  if (res[0]) res[0][3] = w7;
  /* #33: @7 = (@4*@11) */
  w7  = (w4*w11);
  /* #34: @16 = (@8*@6) */
  w16  = (w8*w6);
  /* #35: @7 = (@7+@16) */
  w7 += w16;
  /* #36: @16 = (@12*@15) */
  w16  = (w12*w15);
  /* #37: @7 = (@7+@16) */
  w7 += w16;
  /* #38: @16 = (@14*@13) */
  w16  = (w14*w13);
  /* #39: @7 = (@7-@16) */
  w7 -= w16;
  /* #40: output[0][2] = @7 */
  if (res[0]) res[0][4] = w7;
  /* #41: @7 = (@4*@13) */
  w7  = (w4*w13);
  /* #42: @16 = (@8*@15) */
  w16  = (w8*w15);
  /* #43: @7 = (@7-@16) */
  w7 -= w16;
  /* #44: @16 = (@12*@6) */
  w16  = (w12*w6);
  /* #45: @7 = (@7+@16) */
  w7 += w16;
  /* #46: @16 = (@14*@11) */
  w16  = (w14*w11);
  /* #47: @7 = (@7+@16) */
  w7 += w16;
  /* #48: output[0][3] = @7 */
  if (res[0]) res[0][5] = w7;
  /* #49: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #50: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #51: @15 = (@15+@13) */
  w15 += w13;
  /* #52: @11 = (@12*@11) */
  w11  = (w12*w11);
  /* #53: @15 = (@15-@11) */
  w15 -= w11;
  /* #54: @6 = (@14*@6) */
  w6  = (w14*w6);
  /* #55: @15 = (@15+@6) */
  w15 += w6;
  /* #56: output[0][4] = @15 */
  if (res[0]) res[0][6] = w15;
  /* #57: @17 = @0[7:13] */
  for (rr=w17, ss=w0+7; ss!=w0+13; ss+=1) *rr++ = *ss;
  /* #58: @18 = @2[7:13] */
  for (rr=w18, ss=w2+7; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #59: @17 = (@17-@18) */
  for (i=0, rr=w17, cs=w18; i<6; ++i) (*rr++) -= (*cs++);
  /* #60: output[0][5] = @17 */
  if (res[0]) casadi_copy(w17, 6, res[0]+7);
  /* #61: @17 = @0[13:19] */
  for (rr=w17, ss=w0+13; ss!=w0+19; ss+=1) *rr++ = *ss;
  /* #62: @18 = @2[13:19] */
  for (rr=w18, ss=w2+13; ss!=w2+19; ss+=1) *rr++ = *ss;
  /* #63: @17 = (@17-@18) */
  for (i=0, rr=w17, cs=w18; i<6; ++i) (*rr++) -= (*cs++);
  /* #64: output[0][6] = @17 */
  if (res[0]) casadi_copy(w17, 6, res[0]+13);
  /* #65: @19 = zeros(19x19,31nz) */
  casadi_clear(w19, 31);
  /* #66: @1 = ones(3x1) */
  casadi_fill(w1, 3, 1.);
  /* #67: @15 = 1 */
  w15 = 1.;
  /* #68: @20 = 00 */
  /* #69: @6 = vertcat(@15, @20, @20, @20) */
  rr=(&w6);
  *rr++ = w15;
  /* #70: @6 = (@6/@5) */
  w6 /= w5;
  /* #71: @21 = dense(@6) */
  casadi_densify((&w6), casadi_s0, w21, 0);
  /* #72: @9 = (@9/@5) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) /= w5;
  /* #73: @6 = project(@10) */
  casadi_sparsify(w10, (&w6), casadi_s0, 0);
  /* #74: @15 = ones(4x1,1nz) */
  w15 = 1.;
  /* #75: @11 = dot(@6, @15) */
  w11 = casadi_dot(1, (&w6), (&w15));
  /* #76: @11 = (@11/@5) */
  w11 /= w5;
  /* #77: @22 = (@9*@11) */
  for (i=0, rr=w22, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w11);
  /* #78: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #79: @11 = @21[0] */
  for (rr=(&w11), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #80: @6 = (@4*@11) */
  w6  = (w4*w11);
  /* #81: @15 = @21[1] */
  for (rr=(&w15), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #82: @13 = (@8*@15) */
  w13  = (w8*w15);
  /* #83: @6 = (@6-@13) */
  w6 -= w13;
  /* #84: @13 = @21[2] */
  for (rr=(&w13), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #85: @7 = (@12*@13) */
  w7  = (w12*w13);
  /* #86: @6 = (@6-@7) */
  w6 -= w7;
  /* #87: @7 = @21[3] */
  for (rr=(&w7), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #88: @16 = (@14*@7) */
  w16  = (w14*w7);
  /* #89: @6 = (@6-@16) */
  w6 -= w16;
  /* #90: @16 = (@4*@15) */
  w16  = (w4*w15);
  /* #91: @23 = (@8*@11) */
  w23  = (w8*w11);
  /* #92: @16 = (@16+@23) */
  w16 += w23;
  /* #93: @23 = (@12*@7) */
  w23  = (w12*w7);
  /* #94: @16 = (@16+@23) */
  w16 += w23;
  /* #95: @23 = (@14*@13) */
  w23  = (w14*w13);
  /* #96: @16 = (@16-@23) */
  w16 -= w23;
  /* #97: @23 = (@4*@13) */
  w23  = (w4*w13);
  /* #98: @24 = (@8*@7) */
  w24  = (w8*w7);
  /* #99: @23 = (@23-@24) */
  w23 -= w24;
  /* #100: @24 = (@12*@11) */
  w24  = (w12*w11);
  /* #101: @23 = (@23+@24) */
  w23 += w24;
  /* #102: @24 = (@14*@15) */
  w24  = (w14*w15);
  /* #103: @23 = (@23+@24) */
  w23 += w24;
  /* #104: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #105: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #106: @7 = (@7+@13) */
  w7 += w13;
  /* #107: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #108: @7 = (@7-@15) */
  w7 -= w15;
  /* #109: @11 = (@14*@11) */
  w11  = (w14*w11);
  /* #110: @7 = (@7+@11) */
  w7 += w11;
  /* #111: @17 = ones(6x1) */
  casadi_fill(w17, 6, 1.);
  /* #112: @0 = vertcat(@1, @6, @16, @23, @7, @17, @17) */
  rr=w0;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  *rr++ = w6;
  *rr++ = w16;
  *rr++ = w23;
  *rr++ = w7;
  for (i=0, cs=w17; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<6; ++i) *rr++ = *cs++;
  /* #113: (@19[0, 1, 2, 3, 7, 11, 15, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30] = @0) */
  for (cii=casadi_s1, rr=w19, ss=w0; cii!=casadi_s1+19; ++cii, ++ss) rr[*cii] = *ss;
  /* #114: @25 = zeros(3x1,0nz) */
  /* #115: @6 = -1 */
  w6 = -1.;
  /* #116: @16 = vertcat(@20, @6, @20, @20) */
  rr=(&w16);
  *rr++ = w6;
  /* #117: @16 = (@16/@5) */
  w16 /= w5;
  /* #118: @21 = dense(@16) */
  casadi_densify((&w16), casadi_s2, w21, 0);
  /* #119: @16 = project(@10) */
  casadi_sparsify(w10, (&w16), casadi_s2, 0);
  /* #120: @23 = ones(4x1,1nz) */
  w23 = 1.;
  /* #121: @7 = dot(@16, @23) */
  w7 = casadi_dot(1, (&w16), (&w23));
  /* #122: @7 = (@7/@5) */
  w7 /= w5;
  /* #123: @22 = (@9*@7) */
  for (i=0, rr=w22, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w7);
  /* #124: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #125: @7 = @21[0] */
  for (rr=(&w7), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #126: @16 = (@4*@7) */
  w16  = (w4*w7);
  /* #127: @23 = @21[1] */
  for (rr=(&w23), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #128: @11 = (@8*@23) */
  w11  = (w8*w23);
  /* #129: @16 = (@16-@11) */
  w16 -= w11;
  /* #130: @11 = @21[2] */
  for (rr=(&w11), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #131: @15 = (@12*@11) */
  w15  = (w12*w11);
  /* #132: @16 = (@16-@15) */
  w16 -= w15;
  /* #133: @15 = @21[3] */
  for (rr=(&w15), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #134: @13 = (@14*@15) */
  w13  = (w14*w15);
  /* #135: @16 = (@16-@13) */
  w16 -= w13;
  /* #136: @13 = (@4*@23) */
  w13  = (w4*w23);
  /* #137: @24 = (@8*@7) */
  w24  = (w8*w7);
  /* #138: @13 = (@13+@24) */
  w13 += w24;
  /* #139: @24 = (@12*@15) */
  w24  = (w12*w15);
  /* #140: @13 = (@13+@24) */
  w13 += w24;
  /* #141: @24 = (@14*@11) */
  w24  = (w14*w11);
  /* #142: @13 = (@13-@24) */
  w13 -= w24;
  /* #143: @24 = (@4*@11) */
  w24  = (w4*w11);
  /* #144: @26 = (@8*@15) */
  w26  = (w8*w15);
  /* #145: @24 = (@24-@26) */
  w24 -= w26;
  /* #146: @26 = (@12*@7) */
  w26  = (w12*w7);
  /* #147: @24 = (@24+@26) */
  w24 += w26;
  /* #148: @26 = (@14*@23) */
  w26  = (w14*w23);
  /* #149: @24 = (@24+@26) */
  w24 += w26;
  /* #150: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #151: @11 = (@8*@11) */
  w11  = (w8*w11);
  /* #152: @15 = (@15+@11) */
  w15 += w11;
  /* #153: @23 = (@12*@23) */
  w23  = (w12*w23);
  /* #154: @15 = (@15-@23) */
  w15 -= w23;
  /* #155: @7 = (@14*@7) */
  w7  = (w14*w7);
  /* #156: @15 = (@15+@7) */
  w15 += w7;
  /* #157: @27 = zeros(6x1,0nz) */
  /* #158: @21 = vertcat(@25, @16, @13, @24, @15, @27, @27) */
  rr=w21;
  *rr++ = w16;
  *rr++ = w13;
  *rr++ = w24;
  *rr++ = w15;
  /* #159: @22 = @21[:4] */
  for (rr=w22, ss=w21+0; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #160: (@19[4:20:4] = @22) */
  for (rr=w19+4, ss=w22; rr!=w19+20; rr+=4) *rr = *ss++;
  /* #161: @16 = vertcat(@20, @20, @6, @20) */
  rr=(&w16);
  *rr++ = w6;
  /* #162: @16 = (@16/@5) */
  w16 /= w5;
  /* #163: @22 = dense(@16) */
  casadi_densify((&w16), casadi_s3, w22, 0);
  /* #164: @16 = project(@10) */
  casadi_sparsify(w10, (&w16), casadi_s3, 0);
  /* #165: @13 = ones(4x1,1nz) */
  w13 = 1.;
  /* #166: @24 = dot(@16, @13) */
  w24 = casadi_dot(1, (&w16), (&w13));
  /* #167: @24 = (@24/@5) */
  w24 /= w5;
  /* #168: @21 = (@9*@24) */
  for (i=0, rr=w21, cr=w9; i<4; ++i) (*rr++)  = ((*cr++)*w24);
  /* #169: @22 = (@22-@21) */
  for (i=0, rr=w22, cs=w21; i<4; ++i) (*rr++) -= (*cs++);
  /* #170: @24 = @22[0] */
  for (rr=(&w24), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #171: @16 = (@4*@24) */
  w16  = (w4*w24);
  /* #172: @13 = @22[1] */
  for (rr=(&w13), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #173: @15 = (@8*@13) */
  w15  = (w8*w13);
  /* #174: @16 = (@16-@15) */
  w16 -= w15;
  /* #175: @15 = @22[2] */
  for (rr=(&w15), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #176: @7 = (@12*@15) */
  w7  = (w12*w15);
  /* #177: @16 = (@16-@7) */
  w16 -= w7;
  /* #178: @7 = @22[3] */
  for (rr=(&w7), ss=w22+3; ss!=w22+4; ss+=1) *rr++ = *ss;
  /* #179: @23 = (@14*@7) */
  w23  = (w14*w7);
  /* #180: @16 = (@16-@23) */
  w16 -= w23;
  /* #181: @23 = (@4*@13) */
  w23  = (w4*w13);
  /* #182: @11 = (@8*@24) */
  w11  = (w8*w24);
  /* #183: @23 = (@23+@11) */
  w23 += w11;
  /* #184: @11 = (@12*@7) */
  w11  = (w12*w7);
  /* #185: @23 = (@23+@11) */
  w23 += w11;
  /* #186: @11 = (@14*@15) */
  w11  = (w14*w15);
  /* #187: @23 = (@23-@11) */
  w23 -= w11;
  /* #188: @11 = (@4*@15) */
  w11  = (w4*w15);
  /* #189: @26 = (@8*@7) */
  w26  = (w8*w7);
  /* #190: @11 = (@11-@26) */
  w11 -= w26;
  /* #191: @26 = (@12*@24) */
  w26  = (w12*w24);
  /* #192: @11 = (@11+@26) */
  w11 += w26;
  /* #193: @26 = (@14*@13) */
  w26  = (w14*w13);
  /* #194: @11 = (@11+@26) */
  w11 += w26;
  /* #195: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #196: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #197: @7 = (@7+@15) */
  w7 += w15;
  /* #198: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #199: @7 = (@7-@13) */
  w7 -= w13;
  /* #200: @24 = (@14*@24) */
  w24  = (w14*w24);
  /* #201: @7 = (@7+@24) */
  w7 += w24;
  /* #202: @22 = vertcat(@25, @16, @23, @11, @7, @27, @27) */
  rr=w22;
  *rr++ = w16;
  *rr++ = w23;
  *rr++ = w11;
  *rr++ = w7;
  /* #203: @21 = @22[:4] */
  for (rr=w21, ss=w22+0; ss!=w22+4; ss+=1) *rr++ = *ss;
  /* #204: (@19[5:21:4] = @21) */
  for (rr=w19+5, ss=w21; rr!=w19+21; rr+=4) *rr = *ss++;
  /* #205: @16 = vertcat(@20, @20, @20, @6) */
  rr=(&w16);
  *rr++ = w6;
  /* #206: @16 = (@16/@5) */
  w16 /= w5;
  /* #207: @21 = dense(@16) */
  casadi_densify((&w16), casadi_s4, w21, 0);
  /* #208: @16 = project(@10) */
  casadi_sparsify(w10, (&w16), casadi_s4, 0);
  /* #209: @6 = ones(4x1,1nz) */
  w6 = 1.;
  /* #210: @23 = dot(@16, @6) */
  w23 = casadi_dot(1, (&w16), (&w6));
  /* #211: @23 = (@23/@5) */
  w23 /= w5;
  /* #212: @9 = (@9*@23) */
  for (i=0, rr=w9; i<4; ++i) (*rr++) *= w23;
  /* #213: @21 = (@21-@9) */
  for (i=0, rr=w21, cs=w9; i<4; ++i) (*rr++) -= (*cs++);
  /* #214: @23 = @21[0] */
  for (rr=(&w23), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #215: @5 = (@4*@23) */
  w5  = (w4*w23);
  /* #216: @16 = @21[1] */
  for (rr=(&w16), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #217: @6 = (@8*@16) */
  w6  = (w8*w16);
  /* #218: @5 = (@5-@6) */
  w5 -= w6;
  /* #219: @6 = @21[2] */
  for (rr=(&w6), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #220: @11 = (@12*@6) */
  w11  = (w12*w6);
  /* #221: @5 = (@5-@11) */
  w5 -= w11;
  /* #222: @11 = @21[3] */
  for (rr=(&w11), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #223: @7 = (@14*@11) */
  w7  = (w14*w11);
  /* #224: @5 = (@5-@7) */
  w5 -= w7;
  /* #225: @7 = (@4*@16) */
  w7  = (w4*w16);
  /* #226: @24 = (@8*@23) */
  w24  = (w8*w23);
  /* #227: @7 = (@7+@24) */
  w7 += w24;
  /* #228: @24 = (@12*@11) */
  w24  = (w12*w11);
  /* #229: @7 = (@7+@24) */
  w7 += w24;
  /* #230: @24 = (@14*@6) */
  w24  = (w14*w6);
  /* #231: @7 = (@7-@24) */
  w7 -= w24;
  /* #232: @24 = (@4*@6) */
  w24  = (w4*w6);
  /* #233: @13 = (@8*@11) */
  w13  = (w8*w11);
  /* #234: @24 = (@24-@13) */
  w24 -= w13;
  /* #235: @13 = (@12*@23) */
  w13  = (w12*w23);
  /* #236: @24 = (@24+@13) */
  w24 += w13;
  /* #237: @13 = (@14*@16) */
  w13  = (w14*w16);
  /* #238: @24 = (@24+@13) */
  w24 += w13;
  /* #239: @4 = (@4*@11) */
  w4 *= w11;
  /* #240: @8 = (@8*@6) */
  w8 *= w6;
  /* #241: @4 = (@4+@8) */
  w4 += w8;
  /* #242: @12 = (@12*@16) */
  w12 *= w16;
  /* #243: @4 = (@4-@12) */
  w4 -= w12;
  /* #244: @14 = (@14*@23) */
  w14 *= w23;
  /* #245: @4 = (@4+@14) */
  w4 += w14;
  /* #246: @21 = vertcat(@25, @5, @7, @24, @4, @27, @27) */
  rr=w21;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w24;
  *rr++ = w4;
  /* #247: @9 = @21[:4] */
  for (rr=w9, ss=w21+0; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #248: (@19[6:22:4] = @9) */
  for (rr=w19+6, ss=w9; rr!=w19+22; rr+=4) *rr = *ss++;
  /* #249: output[1][0] = @19 */
  casadi_copy(w19, 31, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real SAM_equation_system_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s6;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 123;
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 123*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
