/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) SAM_equation_system_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[15] = {19, 4, 0, 1, 2, 3, 8, 0, 1, 2, 2, 3, 4, 5, 6};
static const casadi_int casadi_s4[3] = {4, 0, 0};

static const casadi_real casadi_c0[3] = {1., 0., 0.};

/* SAM_equation_system_constr_h_e_fun_jac_uxt_zt:(i0[19],i1[],i2[],i3[])->(o0[4],o1[19x4,8nz],o2[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, w1, w2, w3, *w4=w+25, *w5=w+28, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, *w23=w+48, *w24=w+51, *w25=w+54, *w26=w+57, *w27=w+66, *w28=w+75, *w29=w+78, *w30=w+86, *w31=w+105, *w32=w+114, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 19, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @2 = @0[1] */
  for (rr=(&w2), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @2 */
  if (res[0]) res[0][1] = w2;
  /* #5: @3 = @0[2] */
  for (rr=(&w3), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @3 */
  if (res[0]) res[0][2] = w3;
  /* #7: @4 = vertcat(@1, @2, @3) */
  rr=w4;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #8: @1 = 0.655 */
  w1 = 6.5500000000000003e-01;
  /* #9: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #10: @2 = 1 */
  w2 = 1.;
  /* #11: @3 = @0[5] */
  for (rr=(&w3), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #12: @6 = @0[3] */
  for (rr=(&w6), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #13: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #14: @8 = @0[4] */
  for (rr=(&w8), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #15: @9 = sq(@8) */
  w9 = casadi_sq( w8 );
  /* #16: @7 = (@7+@9) */
  w7 += w9;
  /* #17: @9 = sq(@3) */
  w9 = casadi_sq( w3 );
  /* #18: @7 = (@7+@9) */
  w7 += w9;
  /* #19: @9 = @0[6] */
  for (rr=(&w9), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #20: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #21: @7 = (@7+@10) */
  w7 += w10;
  /* #22: @7 = sqrt(@7) */
  w7 = sqrt( w7 );
  /* #23: @10 = (@3/@7) */
  w10  = (w3/w7);
  /* #24: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #25: @12 = (@9/@7) */
  w12  = (w9/w7);
  /* #26: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #27: @14 = (@11+@13) */
  w14  = (w11+w13);
  /* #28: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #29: @14 = (@2-@14) */
  w14  = (w2-w14);
  /* #30: @15 = (@8/@7) */
  w15  = (w8/w7);
  /* #31: @16 = (@15*@10) */
  w16  = (w15*w10);
  /* #32: @17 = (@6/@7) */
  w17  = (w6/w7);
  /* #33: @18 = (@17*@12) */
  w18  = (w17*w12);
  /* #34: @19 = (@16-@18) */
  w19  = (w16-w18);
  /* #35: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #36: @20 = (@15*@12) */
  w20  = (w15*w12);
  /* #37: @21 = (@17*@10) */
  w21  = (w17*w10);
  /* #38: @22 = (@20+@21) */
  w22  = (w20+w21);
  /* #39: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #40: @23 = horzcat(@14, @19, @22) */
  rr=w23;
  *rr++ = w14;
  *rr++ = w19;
  *rr++ = w22;
  /* #41: @23 = @23' */
  /* #42: @16 = (@16+@18) */
  w16 += w18;
  /* #43: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #44: @18 = sq(@15) */
  w18 = casadi_sq( w15 );
  /* #45: @13 = (@18+@13) */
  w13  = (w18+w13);
  /* #46: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #47: @13 = (@2-@13) */
  w13  = (w2-w13);
  /* #48: @14 = (@10*@12) */
  w14  = (w10*w12);
  /* #49: @19 = (@17*@15) */
  w19  = (w17*w15);
  /* #50: @22 = (@14-@19) */
  w22  = (w14-w19);
  /* #51: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #52: @24 = horzcat(@16, @13, @22) */
  rr=w24;
  *rr++ = w16;
  *rr++ = w13;
  *rr++ = w22;
  /* #53: @24 = @24' */
  /* #54: @20 = (@20-@21) */
  w20 -= w21;
  /* #55: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #56: @14 = (@14+@19) */
  w14 += w19;
  /* #57: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #58: @18 = (@18+@11) */
  w18 += w11;
  /* #59: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #60: @2 = (@2-@18) */
  w2 -= w18;
  /* #61: @25 = horzcat(@20, @14, @2) */
  rr=w25;
  *rr++ = w20;
  *rr++ = w14;
  *rr++ = w2;
  /* #62: @25 = @25' */
  /* #63: @26 = horzcat(@23, @24, @25) */
  rr=w26;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #64: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #65: @23 = [1, 0, 0] */
  casadi_copy(casadi_c0, 3, w23);
  /* #66: @24 = mac(@27,@23,@5) */
  casadi_copy(w5, 3, w24);
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #67: @20 = @24[0] */
  for (rr=(&w20), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #68: @14 = sq(@20) */
  w14 = casadi_sq( w20 );
  /* #69: @2 = @24[1] */
  for (rr=(&w2), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #70: @18 = sq(@2) */
  w18 = casadi_sq( w2 );
  /* #71: @14 = (@14+@18) */
  w14 += w18;
  /* #72: @18 = @24[2] */
  for (rr=(&w18), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #73: @11 = sq(@18) */
  w11 = casadi_sq( w18 );
  /* #74: @14 = (@14+@11) */
  w14 += w11;
  /* #75: @14 = sqrt(@14) */
  w14 = sqrt( w14 );
  /* #76: @24 = (@24/@14) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) /= w14;
  /* #77: @25 = (@1*@24) */
  for (i=0, rr=w25, cs=w24; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #78: @28 = (@4+@25) */
  for (i=0, rr=w28, cr=w4, cs=w25; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #79: @11 = @28[2] */
  for (rr=(&w11), ss=w28+2; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #80: @4 = (@4-@25) */
  for (i=0, rr=w4, cs=w25; i<3; ++i) (*rr++) -= (*cs++);
  /* #81: @19 = @4[2] */
  for (rr=(&w19), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #82: @11 = (@11-@19) */
  w11 -= w19;
  /* #83: output[0][3] = @11 */
  if (res[0]) res[0][3] = w11;
  /* #84: @29 = zeros(19x4,8nz) */
  casadi_clear(w29, 8);
  /* #85: @0 = zeros(19x1) */
  casadi_clear(w0, 19);
  /* #86: @4 = ones(4x1,3nz) */
  casadi_fill(w4, 3, 1.);
  /* #87: {@11, @19, @21, NULL} = vertsplit(@4) */
  w11 = w4[0];
  w19 = w4[1];
  w21 = w4[2];
  /* #88: @30 = @0; (@30[2] += @21) */
  casadi_copy(w0, 19, w30);
  for (rr=w30+2, ss=(&w21); rr!=w30+3; rr+=1) *rr += *ss++;
  /* #89: (@30[1] += @19) */
  for (rr=w30+1, ss=(&w19); rr!=w30+2; rr+=1) *rr += *ss++;
  /* #90: (@30[0] += @11) */
  for (rr=w30+0, ss=(&w11); rr!=w30+1; rr+=1) *rr += *ss++;
  /* #91: @11 = @30[0] */
  for (rr=(&w11), ss=w30+0; ss!=w30+1; ss+=1) *rr++ = *ss;
  /* #92: (@29[0] = @11) */
  for (rr=w29+0, ss=(&w11); rr!=w29+1; rr+=1) *rr = *ss++;
  /* #93: @11 = @30[1] */
  for (rr=(&w11), ss=w30+1; ss!=w30+2; ss+=1) *rr++ = *ss;
  /* #94: (@29[1] = @11) */
  for (rr=w29+1, ss=(&w11); rr!=w29+2; rr+=1) *rr = *ss++;
  /* #95: @11 = @30[2] */
  for (rr=(&w11), ss=w30+2; ss!=w30+3; ss+=1) *rr++ = *ss;
  /* #96: (@29[2] = @11) */
  for (rr=w29+2, ss=(&w11); rr!=w29+3; rr+=1) *rr = *ss++;
  /* #97: @27 = zeros(3x3) */
  casadi_clear(w27, 9);
  /* #98: @11 = ones(4x1,1nz) */
  w11 = 1.;
  /* #99: {NULL, NULL, NULL, @19} = vertsplit(@11) */
  w19 = w11;
  /* #100: @11 = (-@19) */
  w11 = (- w19 );
  /* #101: @4 = @5; (@4[2] += @11) */
  casadi_copy(w5, 3, w4);
  for (rr=w4+2, ss=(&w11); rr!=w4+3; rr+=1) *rr += *ss++;
  /* #102: @25 = (@1*@4) */
  for (i=0, rr=w25, cs=w4; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #103: @28 = (@25/@14) */
  for (i=0, rr=w28, cr=w25; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #104: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<3; ++i) *rr++ = (- *cs++ );
  /* #105: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #106: @24 = (@24/@14) */
  for (i=0, rr=w24; i<3; ++i) (*rr++) /= w14;
  /* #107: @24 = (-@24) */
  for (i=0, rr=w24, cs=w24; i<3; ++i) *rr++ = (- *cs++ );
  /* #108: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #109: @11 = dot(@24, @25) */
  w11 = casadi_dot(3, w24, w25);
  /* #110: @21 = (2.*@14) */
  w21 = (2.* w14 );
  /* #111: @11 = (@11/@21) */
  w11 /= w21;
  /* #112: @16 = (@18*@11) */
  w16  = (w18*w11);
  /* #113: (@28[2] += @16) */
  for (rr=w28+2, ss=(&w16); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #114: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #115: @16 = (@2*@11) */
  w16  = (w2*w11);
  /* #116: (@28[1] += @16) */
  for (rr=w28+1, ss=(&w16); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #117: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #118: @11 = (@20*@11) */
  w11  = (w20*w11);
  /* #119: (@28[0] += @11) */
  for (rr=w28+0, ss=(&w11); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #120: @23 = @23' */
  /* #121: @26 = mac(@28,@23,@27) */
  casadi_copy(w27, 9, w26);
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w23+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #122: @31 = @26' */
  for (i=0, rr=w31, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #123: {@28, @25, @32} = horzsplit(@31) */
  casadi_copy(w31, 3, w28);
  casadi_copy(w31+3, 3, w25);
  casadi_copy(w31+6, 3, w32);
  /* #124: @32 = @32' */
  /* #125: {@11, @16, @13} = horzsplit(@32) */
  w11 = w32[0];
  w16 = w32[1];
  w13 = w32[2];
  /* #126: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #127: @22 = (@10*@16) */
  w22  = (w10*w16);
  /* #128: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #129: @33 = (@15*@11) */
  w33  = (w15*w11);
  /* #130: @22 = (@22+@33) */
  w22 += w33;
  /* #131: @25 = @25' */
  /* #132: {@33, @34, @35} = horzsplit(@25) */
  w33 = w25[0];
  w34 = w25[1];
  w35 = w25[2];
  /* #133: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #134: @36 = (@10*@35) */
  w36  = (w10*w35);
  /* #135: @22 = (@22+@36) */
  w22 += w36;
  /* #136: @36 = (2.*@12) */
  w36 = (2.* w12 );
  /* #137: @34 = (-@34) */
  w34 = (- w34 );
  /* #138: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #139: @37 = (@36*@34) */
  w37  = (w36*w34);
  /* #140: @22 = (@22+@37) */
  w22 += w37;
  /* #141: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #142: @37 = (@17*@33) */
  w37  = (w17*w33);
  /* #143: @22 = (@22+@37) */
  w22 += w37;
  /* #144: @28 = @28' */
  /* #145: {@37, @38, @39} = horzsplit(@28) */
  w37 = w28[0];
  w38 = w28[1];
  w39 = w28[2];
  /* #146: @39 = (2.*@39) */
  w39 = (2.* w39 );
  /* #147: @40 = (@15*@39) */
  w40  = (w15*w39);
  /* #148: @22 = (@22+@40) */
  w22 += w40;
  /* #149: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #150: @40 = (@17*@38) */
  w40  = (w17*w38);
  /* #151: @22 = (@22-@40) */
  w22 -= w40;
  /* #152: @37 = (-@37) */
  w37 = (- w37 );
  /* #153: @37 = (2.*@37) */
  w37 = (2.* w37 );
  /* #154: @40 = (@36*@37) */
  w40  = (w36*w37);
  /* #155: @22 = (@22+@40) */
  w22 += w40;
  /* #156: @40 = (@22/@7) */
  w40  = (w22/w7);
  /* #157: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #158: @41 = (@15/@7) */
  w41  = (w15/w7);
  /* #159: @42 = (2.*@15) */
  w42 = (2.* w15 );
  /* #160: @13 = (-@13) */
  w13 = (- w13 );
  /* #161: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #162: @43 = (@42*@13) */
  w43  = (w42*w13);
  /* #163: @44 = (@17*@16) */
  w44  = (w17*w16);
  /* #164: @43 = (@43+@44) */
  w43 += w44;
  /* #165: @44 = (@12*@11) */
  w44  = (w12*w11);
  /* #166: @43 = (@43+@44) */
  w43 += w44;
  /* #167: @44 = (@17*@35) */
  w44  = (w17*w35);
  /* #168: @43 = (@43-@44) */
  w43 -= w44;
  /* #169: @34 = (@42*@34) */
  w34  = (w42*w34);
  /* #170: @43 = (@43+@34) */
  w43 += w34;
  /* #171: @34 = (@10*@33) */
  w34  = (w10*w33);
  /* #172: @43 = (@43+@34) */
  w43 += w34;
  /* #173: @34 = (@12*@39) */
  w34  = (w12*w39);
  /* #174: @43 = (@43+@34) */
  w43 += w34;
  /* #175: @34 = (@10*@38) */
  w34  = (w10*w38);
  /* #176: @43 = (@43+@34) */
  w43 += w34;
  /* #177: @34 = (@41*@43) */
  w34  = (w41*w43);
  /* #178: @34 = (-@34) */
  w34 = (- w34 );
  /* #179: @44 = (@17/@7) */
  w44  = (w17/w7);
  /* #180: @45 = (@15*@16) */
  w45  = (w15*w16);
  /* #181: @46 = (@10*@11) */
  w46  = (w10*w11);
  /* #182: @45 = (@45-@46) */
  w45 -= w46;
  /* #183: @46 = (@15*@35) */
  w46  = (w15*w35);
  /* #184: @45 = (@45-@46) */
  w45 -= w46;
  /* #185: @46 = (@12*@33) */
  w46  = (w12*w33);
  /* #186: @45 = (@45+@46) */
  w45 += w46;
  /* #187: @46 = (@10*@39) */
  w46  = (w10*w39);
  /* #188: @45 = (@45+@46) */
  w45 += w46;
  /* #189: @46 = (@12*@38) */
  w46  = (w12*w38);
  /* #190: @45 = (@45-@46) */
  w45 -= w46;
  /* #191: @46 = (@44*@45) */
  w46  = (w44*w45);
  /* #192: @34 = (@34-@46) */
  w34 -= w46;
  /* #193: @46 = (@12/@7) */
  w46  = (w12/w7);
  /* #194: @22 = (@46*@22) */
  w22  = (w46*w22);
  /* #195: @34 = (@34-@22) */
  w34 -= w22;
  /* #196: @22 = (@10/@7) */
  w22  = (w10/w7);
  /* #197: @47 = (2.*@10) */
  w47 = (2.* w10 );
  /* #198: @13 = (@47*@13) */
  w13  = (w47*w13);
  /* #199: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #200: @13 = (@13+@16) */
  w13 += w16;
  /* #201: @11 = (@17*@11) */
  w11  = (w17*w11);
  /* #202: @13 = (@13-@11) */
  w13 -= w11;
  /* #203: @35 = (@12*@35) */
  w35  = (w12*w35);
  /* #204: @13 = (@13+@35) */
  w13 += w35;
  /* #205: @33 = (@15*@33) */
  w33  = (w15*w33);
  /* #206: @13 = (@13+@33) */
  w13 += w33;
  /* #207: @39 = (@17*@39) */
  w39  = (w17*w39);
  /* #208: @13 = (@13+@39) */
  w13 += w39;
  /* #209: @38 = (@15*@38) */
  w38  = (w15*w38);
  /* #210: @13 = (@13+@38) */
  w13 += w38;
  /* #211: @37 = (@47*@37) */
  w37  = (w47*w37);
  /* #212: @13 = (@13+@37) */
  w13 += w37;
  /* #213: @37 = (@22*@13) */
  w37  = (w22*w13);
  /* #214: @34 = (@34-@37) */
  w34 -= w37;
  /* #215: @37 = (2.*@7) */
  w37 = (2.* w7 );
  /* #216: @34 = (@34/@37) */
  w34 /= w37;
  /* #217: @38 = (@9*@34) */
  w38  = (w9*w34);
  /* #218: @40 = (@40+@38) */
  w40 += w38;
  /* #219: (@0[6] += @40) */
  for (rr=w0+6, ss=(&w40); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #220: @43 = (@43/@7) */
  w43 /= w7;
  /* #221: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #222: @40 = (@8*@34) */
  w40  = (w8*w34);
  /* #223: @43 = (@43+@40) */
  w43 += w40;
  /* #224: (@0[4] += @43) */
  for (rr=w0+4, ss=(&w43); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #225: @45 = (@45/@7) */
  w45 /= w7;
  /* #226: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #227: @43 = (@6*@34) */
  w43  = (w6*w34);
  /* #228: @45 = (@45+@43) */
  w45 += w43;
  /* #229: (@0[3] += @45) */
  for (rr=w0+3, ss=(&w45); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #230: @13 = (@13/@7) */
  w13 /= w7;
  /* #231: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #232: @34 = (@3*@34) */
  w34  = (w3*w34);
  /* #233: @13 = (@13+@34) */
  w13 += w34;
  /* #234: (@0[5] += @13) */
  for (rr=w0+5, ss=(&w13); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #235: {@13, @34, @45} = vertsplit(@4) */
  w13 = w4[0];
  w34 = w4[1];
  w45 = w4[2];
  /* #236: (@0[2] += @45) */
  for (rr=w0+2, ss=(&w45); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #237: (@0[1] += @34) */
  for (rr=w0+1, ss=(&w34); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #238: (@0[0] += @13) */
  for (rr=w0+0, ss=(&w13); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #239: (@5[2] += @19) */
  for (rr=w5+2, ss=(&w19); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #240: @4 = (@1*@5) */
  for (i=0, rr=w4, cs=w5; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #241: @28 = (@4/@14) */
  for (i=0, rr=w28, cr=w4; i<3; ++i) (*rr++)  = ((*cr++)/w14);
  /* #242: @14 = dot(@24, @4) */
  w14 = casadi_dot(3, w24, w4);
  /* #243: @14 = (@14/@21) */
  w14 /= w21;
  /* #244: @18 = (@18*@14) */
  w18 *= w14;
  /* #245: (@28[2] += @18) */
  for (rr=w28+2, ss=(&w18); rr!=w28+3; rr+=1) *rr += *ss++;
  /* #246: @2 = (@2*@14) */
  w2 *= w14;
  /* #247: (@28[1] += @2) */
  for (rr=w28+1, ss=(&w2); rr!=w28+2; rr+=1) *rr += *ss++;
  /* #248: @20 = (@20*@14) */
  w20 *= w14;
  /* #249: (@28[0] += @20) */
  for (rr=w28+0, ss=(&w20); rr!=w28+1; rr+=1) *rr += *ss++;
  /* #250: @27 = mac(@28,@23,@27) */
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w23+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #251: @31 = @27' */
  for (i=0, rr=w31, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #252: {@28, @23, @24} = horzsplit(@31) */
  casadi_copy(w31, 3, w28);
  casadi_copy(w31+3, 3, w23);
  casadi_copy(w31+6, 3, w24);
  /* #253: @24 = @24' */
  /* #254: {@20, @14, @2} = horzsplit(@24) */
  w20 = w24[0];
  w14 = w24[1];
  w2 = w24[2];
  /* #255: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #256: @18 = (@10*@14) */
  w18  = (w10*w14);
  /* #257: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #258: @21 = (@15*@20) */
  w21  = (w15*w20);
  /* #259: @18 = (@18+@21) */
  w18 += w21;
  /* #260: @23 = @23' */
  /* #261: {@21, @1, @19} = horzsplit(@23) */
  w21 = w23[0];
  w1 = w23[1];
  w19 = w23[2];
  /* #262: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #263: @13 = (@10*@19) */
  w13  = (w10*w19);
  /* #264: @18 = (@18+@13) */
  w18 += w13;
  /* #265: @1 = (-@1) */
  w1 = (- w1 );
  /* #266: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #267: @13 = (@36*@1) */
  w13  = (w36*w1);
  /* #268: @18 = (@18+@13) */
  w18 += w13;
  /* #269: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #270: @13 = (@17*@21) */
  w13  = (w17*w21);
  /* #271: @18 = (@18+@13) */
  w18 += w13;
  /* #272: @28 = @28' */
  /* #273: {@13, @34, @45} = horzsplit(@28) */
  w13 = w28[0];
  w34 = w28[1];
  w45 = w28[2];
  /* #274: @45 = (2.*@45) */
  w45 = (2.* w45 );
  /* #275: @43 = (@15*@45) */
  w43  = (w15*w45);
  /* #276: @18 = (@18+@43) */
  w18 += w43;
  /* #277: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #278: @43 = (@17*@34) */
  w43  = (w17*w34);
  /* #279: @18 = (@18-@43) */
  w18 -= w43;
  /* #280: @13 = (-@13) */
  w13 = (- w13 );
  /* #281: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #282: @36 = (@36*@13) */
  w36 *= w13;
  /* #283: @18 = (@18+@36) */
  w18 += w36;
  /* #284: @36 = (@18/@7) */
  w36  = (w18/w7);
  /* #285: @2 = (-@2) */
  w2 = (- w2 );
  /* #286: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #287: @43 = (@42*@2) */
  w43  = (w42*w2);
  /* #288: @40 = (@17*@14) */
  w40  = (w17*w14);
  /* #289: @43 = (@43+@40) */
  w43 += w40;
  /* #290: @40 = (@12*@20) */
  w40  = (w12*w20);
  /* #291: @43 = (@43+@40) */
  w43 += w40;
  /* #292: @40 = (@17*@19) */
  w40  = (w17*w19);
  /* #293: @43 = (@43-@40) */
  w43 -= w40;
  /* #294: @42 = (@42*@1) */
  w42 *= w1;
  /* #295: @43 = (@43+@42) */
  w43 += w42;
  /* #296: @42 = (@10*@21) */
  w42  = (w10*w21);
  /* #297: @43 = (@43+@42) */
  w43 += w42;
  /* #298: @42 = (@12*@45) */
  w42  = (w12*w45);
  /* #299: @43 = (@43+@42) */
  w43 += w42;
  /* #300: @42 = (@10*@34) */
  w42  = (w10*w34);
  /* #301: @43 = (@43+@42) */
  w43 += w42;
  /* #302: @41 = (@41*@43) */
  w41 *= w43;
  /* #303: @41 = (-@41) */
  w41 = (- w41 );
  /* #304: @42 = (@15*@14) */
  w42  = (w15*w14);
  /* #305: @1 = (@10*@20) */
  w1  = (w10*w20);
  /* #306: @42 = (@42-@1) */
  w42 -= w1;
  /* #307: @1 = (@15*@19) */
  w1  = (w15*w19);
  /* #308: @42 = (@42-@1) */
  w42 -= w1;
  /* #309: @1 = (@12*@21) */
  w1  = (w12*w21);
  /* #310: @42 = (@42+@1) */
  w42 += w1;
  /* #311: @10 = (@10*@45) */
  w10 *= w45;
  /* #312: @42 = (@42+@10) */
  w42 += w10;
  /* #313: @10 = (@12*@34) */
  w10  = (w12*w34);
  /* #314: @42 = (@42-@10) */
  w42 -= w10;
  /* #315: @44 = (@44*@42) */
  w44 *= w42;
  /* #316: @41 = (@41-@44) */
  w41 -= w44;
  /* #317: @46 = (@46*@18) */
  w46 *= w18;
  /* #318: @41 = (@41-@46) */
  w41 -= w46;
  /* #319: @2 = (@47*@2) */
  w2  = (w47*w2);
  /* #320: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #321: @2 = (@2+@14) */
  w2 += w14;
  /* #322: @20 = (@17*@20) */
  w20  = (w17*w20);
  /* #323: @2 = (@2-@20) */
  w2 -= w20;
  /* #324: @12 = (@12*@19) */
  w12 *= w19;
  /* #325: @2 = (@2+@12) */
  w2 += w12;
  /* #326: @21 = (@15*@21) */
  w21  = (w15*w21);
  /* #327: @2 = (@2+@21) */
  w2 += w21;
  /* #328: @17 = (@17*@45) */
  w17 *= w45;
  /* #329: @2 = (@2+@17) */
  w2 += w17;
  /* #330: @15 = (@15*@34) */
  w15 *= w34;
  /* #331: @2 = (@2+@15) */
  w2 += w15;
  /* #332: @47 = (@47*@13) */
  w47 *= w13;
  /* #333: @2 = (@2+@47) */
  w2 += w47;
  /* #334: @22 = (@22*@2) */
  w22 *= w2;
  /* #335: @41 = (@41-@22) */
  w41 -= w22;
  /* #336: @41 = (@41/@37) */
  w41 /= w37;
  /* #337: @9 = (@9*@41) */
  w9 *= w41;
  /* #338: @36 = (@36+@9) */
  w36 += w9;
  /* #339: (@0[6] += @36) */
  for (rr=w0+6, ss=(&w36); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #340: @43 = (@43/@7) */
  w43 /= w7;
  /* #341: @8 = (@8*@41) */
  w8 *= w41;
  /* #342: @43 = (@43+@8) */
  w43 += w8;
  /* #343: (@0[4] += @43) */
  for (rr=w0+4, ss=(&w43); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #344: @42 = (@42/@7) */
  w42 /= w7;
  /* #345: @6 = (@6*@41) */
  w6 *= w41;
  /* #346: @42 = (@42+@6) */
  w42 += w6;
  /* #347: (@0[3] += @42) */
  for (rr=w0+3, ss=(&w42); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #348: @2 = (@2/@7) */
  w2 /= w7;
  /* #349: @3 = (@3*@41) */
  w3 *= w41;
  /* #350: @2 = (@2+@3) */
  w2 += w3;
  /* #351: (@0[5] += @2) */
  for (rr=w0+5, ss=(&w2); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #352: {@2, @3, @41} = vertsplit(@5) */
  w2 = w5[0];
  w3 = w5[1];
  w41 = w5[2];
  /* #353: (@0[2] += @41) */
  for (rr=w0+2, ss=(&w41); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #354: (@0[1] += @3) */
  for (rr=w0+1, ss=(&w3); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #355: (@0[0] += @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #356: @2 = @0[2] */
  for (rr=(&w2), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #357: (@29[3] = @2) */
  for (rr=w29+3, ss=(&w2); rr!=w29+4; rr+=1) *rr = *ss++;
  /* #358: @2 = @0[3] */
  for (rr=(&w2), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #359: (@29[4] = @2) */
  for (rr=w29+4, ss=(&w2); rr!=w29+5; rr+=1) *rr = *ss++;
  /* #360: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #361: (@29[5] = @2) */
  for (rr=w29+5, ss=(&w2); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #362: @2 = @0[5] */
  for (rr=(&w2), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #363: (@29[6] = @2) */
  for (rr=w29+6, ss=(&w2); rr!=w29+7; rr+=1) *rr = *ss++;
  /* #364: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #365: (@29[7] = @2) */
  for (rr=w29+7, ss=(&w2); rr!=w29+8; rr+=1) *rr = *ss++;
  /* #366: output[1][0] = @29 */
  casadi_copy(w29, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real SAM_equation_system_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 132;
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_constr_h_e_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 132*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
