/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) SAM_equation_system_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_project CASADI_PREFIX(project)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[21] = {6, 6, 0, 1, 2, 3, 6, 9, 12, 0, 1, 2, 3, 4, 5, 3, 4, 5, 3, 4, 5};
static const casadi_int casadi_s3[6] = {0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[18] = {6, 6, 0, 1, 2, 3, 6, 8, 9, 0, 1, 2, 3, 4, 5, 4, 5, 5};
static const casadi_int casadi_s5[18] = {6, 6, 0, 1, 2, 3, 4, 6, 9, 0, 1, 2, 3, 3, 4, 3, 4, 5};
static const casadi_int casadi_s6[9] = {18, 19, 20, 24, 25, 26, 30, 31, 32};
static const casadi_int casadi_s7[9] = {21, 22, 23, 27, 28, 29, 33, 34, 35};
static const casadi_int casadi_s8[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s9[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s10[4] = {0, 1, 0, 0};

static const casadi_real casadi_c0[36] = {1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.};
static const casadi_real casadi_c1[3] = {5.3789000000000010e-02, 1.7031445000000001e+00, 1.7031445000000001e+00};
static const casadi_real casadi_c2[3] = {-7.5000000000000000e-01, 0., 5.9999999999999998e-02};
static const casadi_real casadi_c3[3] = {7.3999999999999999e-01, 0., 5.9999999999999998e-02};
static const casadi_real casadi_c4[3] = {4.0400000000000003e-01, 0., 1.2500000000000001e-02};
static const casadi_real casadi_c5[3] = {2.0800000000000003e-03, 1.1814616666666668e-02, 1.1814616666666668e-02};
static const casadi_real casadi_c6[3] = {7.1950000000000003e-01, 0., 1.3000000000000000e-01};
static const casadi_real casadi_c7[3] = {0., 0., 1.};
static const casadi_real casadi_c8[3] = {0., 1., 0.};
static const casadi_real casadi_c9[3] = {2.9999999999999999e-02, 0., 0.};
static const casadi_real casadi_c10[3] = {4.0000000000000001e-02, 0., 0.};

/* x_dot:(i0[19],i1[6])->(o0[19]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+6, w1, *w2=w+10, *w3=w+29, w4, w5, w6, w7, w8, w9, w10, *w11=w+40, *w12=w+43, *w13=w+46, *w14=w+49, *w15=w+58, *w16=w+67, *w17=w+71, *w18=w+83, *w19=w+95, *w20=w+99, *w21=w+105, *w22=w+141, *w23=w+144, *w24=w+147, *w25=w+156, *w26=w+165, *w27=w+174, *w28=w+177, *w29=w+186, w30, *w31=w+190, *w32=w+196, w33, *w34=w+199, *w35=w+205, *w36=w+211, *w37=w+247, *w38=w+283, w39;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = 1 */
  w1 = 1.;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 19, w2);
  /* #3: @3 = @2[3:7] */
  for (rr=w3, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #4: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #5: @3 = (@3/@4) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) /= w4;
  /* #6: @4 = @3[2] */
  for (rr=(&w4), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #7: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #8: @6 = @3[3] */
  for (rr=(&w6), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #9: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #12: @1 = (@1-@5) */
  w1 -= w5;
  /* #13: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #14: @7 = (@5*@4) */
  w7  = (w5*w4);
  /* #15: @8 = @3[0] */
  for (rr=(&w8), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@8*@6) */
  w9  = (w8*w6);
  /* #17: @7 = (@7-@9) */
  w7 -= w9;
  /* #18: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #19: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #20: @10 = (@8*@4) */
  w10  = (w8*w4);
  /* #21: @9 = (@9+@10) */
  w9 += w10;
  /* #22: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #23: @11 = horzcat(@1, @7, @9) */
  rr=w11;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w9;
  /* #24: @11 = @11' */
  /* #25: @1 = (@5*@4) */
  w1  = (w5*w4);
  /* #26: @7 = (@8*@6) */
  w7  = (w8*w6);
  /* #27: @1 = (@1+@7) */
  w1 += w7;
  /* #28: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #29: @7 = 1 */
  w7 = 1.;
  /* #30: @9 = sq(@5) */
  w9 = casadi_sq( w5 );
  /* #31: @10 = sq(@6) */
  w10 = casadi_sq( w6 );
  /* #32: @9 = (@9+@10) */
  w9 += w10;
  /* #33: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #34: @7 = (@7-@9) */
  w7 -= w9;
  /* #35: @9 = (@4*@6) */
  w9  = (w4*w6);
  /* #36: @10 = (@8*@5) */
  w10  = (w8*w5);
  /* #37: @9 = (@9-@10) */
  w9 -= w10;
  /* #38: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #39: @12 = horzcat(@1, @7, @9) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w9;
  /* #40: @12 = @12' */
  /* #41: @1 = (@5*@6) */
  w1  = (w5*w6);
  /* #42: @7 = (@8*@4) */
  w7  = (w8*w4);
  /* #43: @1 = (@1-@7) */
  w1 -= w7;
  /* #44: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #45: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #46: @8 = (@8*@5) */
  w8 *= w5;
  /* #47: @6 = (@6+@8) */
  w6 += w8;
  /* #48: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #49: @8 = 1 */
  w8 = 1.;
  /* #50: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #51: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #52: @5 = (@5+@4) */
  w5 += w4;
  /* #53: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #54: @8 = (@8-@5) */
  w8 -= w5;
  /* #55: @13 = horzcat(@1, @6, @8) */
  rr=w13;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w8;
  /* #56: @13 = @13' */
  /* #57: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #58: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #59: @11 = @2[7:10] */
  for (rr=w11, ss=w2+7; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #60: @0 = mac(@15,@11,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #61: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #62: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #63: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #64: @6 = @3[1] */
  for (rr=(&w6), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #65: @8 = (-@6) */
  w8 = (- w6 );
  /* #66: @5 = @3[2] */
  for (rr=(&w5), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #67: @4 = (-@5) */
  w4 = (- w5 );
  /* #68: @7 = @3[3] */
  for (rr=(&w7), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #69: @9 = (-@7) */
  w9 = (- w7 );
  /* #70: @0 = horzcat(@8, @4, @9) */
  rr=w0;
  *rr++ = w8;
  *rr++ = w4;
  *rr++ = w9;
  /* #71: @0 = @0' */
  /* #72: @8 = @3[0] */
  for (rr=(&w8), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #73: @4 = (-@7) */
  w4 = (- w7 );
  /* #74: @11 = horzcat(@8, @4, @5) */
  rr=w11;
  *rr++ = w8;
  *rr++ = w4;
  *rr++ = w5;
  /* #75: @11 = @11' */
  /* #76: @4 = (-@6) */
  w4 = (- w6 );
  /* #77: @12 = horzcat(@7, @8, @4) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w4;
  /* #78: @12 = @12' */
  /* #79: @5 = (-@5) */
  w5 = (- w5 );
  /* #80: @13 = horzcat(@5, @6, @8) */
  rr=w13;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w8;
  /* #81: @13 = @13' */
  /* #82: @17 = horzcat(@0, @11, @12, @13) */
  rr=w17;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #83: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #84: @18 = (@1*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #85: @0 = @2[10:13] */
  for (rr=w0, ss=w2+10; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #86: @16 = mac(@18,@0,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w18+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*4]**tt++;
  /* #87: @1 = 50 */
  w1 = 50.;
  /* #88: @5 = 1 */
  w5 = 1.;
  /* #89: @6 = 0 */
  w6 = 0.;
  /* #90: @19 = @3' */
  casadi_copy(w3, 4, w19);
  /* #91: @6 = mac(@19,@3,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w19+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #92: @5 = (@5-@6) */
  w5 -= w6;
  /* #93: @1 = (@1*@5) */
  w1 *= w5;
  /* #94: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #95: @16 = (@16+@3) */
  for (i=0, rr=w16, cs=w3; i<4; ++i) (*rr++) += (*cs++);
  /* #96: output[0][1] = @16 */
  if (res[0]) casadi_copy(w16, 4, res[0]+3);
  /* #97: @20 = zeros(6x1) */
  casadi_clear(w20, 6);
  /* #98: @21 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 36, w21);
  /* #99: @1 = 2.6 */
  w1 = 2.6000000000000001e+00;
  /* #100: @5 = 14.9 */
  w5 = 1.4900000000000000e+01;
  /* #101: @6 = 5.82204 */
  w6 = 5.8220387755407756e+00;
  /* #102: @8 = 0.045 */
  w8 = 4.4999999999999998e-02;
  /* #103: @7 = @2[13] */
  for (rr=(&w7), ss=w2+13; ss!=w2+14; ss+=1) *rr++ = *ss;
  /* #104: @4 = 100 */
  w4 = 100.;
  /* #105: @7 = (@7/@4) */
  w7 /= w4;
  /* #106: @8 = (@8*@7) */
  w8 *= w7;
  /* #107: @6 = (@6*@8) */
  w6 *= w8;
  /* #108: @5 = (@5+@6) */
  w5 += w6;
  /* #109: @1 = (@1+@5) */
  w1 += w5;
  /* #110: @0 = vertcat(@1, @1, @1) */
  rr=w0;
  *rr++ = w1;
  *rr++ = w1;
  *rr++ = w1;
  /* #111: @0 = sparsity_cast(@0) */
  /* #112: @11 = 
  [[0.053789, 00, 00], 
   [00, 1.70314, 00], 
   [00, 00, 1.70314]] */
  casadi_copy(casadi_c1, 3, w11);
  /* #113: @15 = dense(@11) */
  casadi_densify(w11, casadi_s0, w15, 0);
  /* #114: @5 = 14.9 */
  w5 = 1.4900000000000000e+01;
  /* #115: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #116: @7 = 0 */
  w7 = 0.;
  /* #117: @11 = [-0.75, 0, 0.06] */
  casadi_copy(casadi_c2, 3, w11);
  /* #118: @12 = [0.74, 0, 0.06] */
  casadi_copy(casadi_c3, 3, w12);
  /* #119: @12 = (@11+@12) */
  for (i=0, rr=w12, cr=w11, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #120: @4 = @12[2] */
  for (rr=(&w4), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #121: @4 = (-@4) */
  w4 = (- w4 );
  /* #122: @9 = @12[1] */
  for (rr=(&w9), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #123: @13 = horzcat(@7, @4, @9) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #124: @13 = @13' */
  /* #125: @7 = @12[2] */
  for (rr=(&w7), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #126: @4 = 0 */
  w4 = 0.;
  /* #127: @9 = @12[0] */
  for (rr=(&w9), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #128: @9 = (-@9) */
  w9 = (- w9 );
  /* #129: @22 = horzcat(@7, @4, @9) */
  rr=w22;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #130: @22 = @22' */
  /* #131: @7 = @12[1] */
  for (rr=(&w7), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #132: @7 = (-@7) */
  w7 = (- w7 );
  /* #133: @4 = @12[0] */
  for (rr=(&w4), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #134: @9 = 0 */
  w9 = 0.;
  /* #135: @23 = horzcat(@7, @4, @9) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #136: @23 = @23' */
  /* #137: @24 = horzcat(@13, @22, @23) */
  rr=w24;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #138: @25 = @24' */
  for (i=0, rr=w25, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #139: @7 = 0 */
  w7 = 0.;
  /* #140: @4 = @12[2] */
  for (rr=(&w4), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #141: @4 = (-@4) */
  w4 = (- w4 );
  /* #142: @9 = @12[1] */
  for (rr=(&w9), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #143: @13 = horzcat(@7, @4, @9) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #144: @13 = @13' */
  /* #145: @7 = @12[2] */
  for (rr=(&w7), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #146: @4 = 0 */
  w4 = 0.;
  /* #147: @9 = @12[0] */
  for (rr=(&w9), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #148: @9 = (-@9) */
  w9 = (- w9 );
  /* #149: @22 = horzcat(@7, @4, @9) */
  rr=w22;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #150: @22 = @22' */
  /* #151: @7 = @12[1] */
  for (rr=(&w7), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #152: @7 = (-@7) */
  w7 = (- w7 );
  /* #153: @4 = @12[0] */
  for (rr=(&w4), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #154: @9 = 0 */
  w9 = 0.;
  /* #155: @23 = horzcat(@7, @4, @9) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #156: @23 = @23' */
  /* #157: @24 = horzcat(@13, @22, @23) */
  rr=w24;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #158: @26 = @24' */
  for (i=0, rr=w26, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #159: @14 = mac(@25,@26,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w25+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #160: @14 = (@5*@14) */
  for (i=0, rr=w14, cs=w14; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #161: @15 = (@15-@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++) -= (*cs++);
  /* #162: @5 = 0.00180625 */
  w5 = 1.8062500000000003e-03;
  /* #163: @7 = 0.5 */
  w7 = 5.0000000000000000e-01;
  /* #164: @7 = (@7*@6) */
  w7 *= w6;
  /* #165: @5 = (@5*@7) */
  w5 *= w7;
  /* #166: @7 = 0.0833333 */
  w7 = 8.3333333333333329e-02;
  /* #167: @7 = (@7*@6) */
  w7 *= w6;
  /* #168: @4 = 0.00541875 */
  w4 = 5.4187500000000008e-03;
  /* #169: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #170: @4 = (@4+@8) */
  w4 += w8;
  /* #171: @7 = (@7*@4) */
  w7 *= w4;
  /* #172: @13 = vertcat(@5, @7, @7) */
  rr=w13;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w7;
  /* #173: @13 = sparsity_cast(@13) */
  /* #174: @14 = dense(@13) */
  casadi_densify(w13, casadi_s0, w14, 0);
  /* #175: @25 = zeros(3x3) */
  casadi_clear(w25, 9);
  /* #176: @5 = 0 */
  w5 = 0.;
  /* #177: @13 = [0.404, 0, 0.0125] */
  casadi_copy(casadi_c4, 3, w13);
  /* #178: @13 = (@11+@13) */
  for (i=0, rr=w13, cr=w11, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #179: @7 = @13[2] */
  for (rr=(&w7), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #180: @7 = (-@7) */
  w7 = (- w7 );
  /* #181: @4 = @13[1] */
  for (rr=(&w4), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #182: @22 = horzcat(@5, @7, @4) */
  rr=w22;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #183: @22 = @22' */
  /* #184: @5 = @13[2] */
  for (rr=(&w5), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #185: @7 = 0 */
  w7 = 0.;
  /* #186: @4 = @13[0] */
  for (rr=(&w4), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #187: @4 = (-@4) */
  w4 = (- w4 );
  /* #188: @23 = horzcat(@5, @7, @4) */
  rr=w23;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #189: @23 = @23' */
  /* #190: @5 = @13[1] */
  for (rr=(&w5), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #191: @5 = (-@5) */
  w5 = (- w5 );
  /* #192: @7 = @13[0] */
  for (rr=(&w7), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #193: @4 = 0 */
  w4 = 0.;
  /* #194: @27 = horzcat(@5, @7, @4) */
  rr=w27;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #195: @27 = @27' */
  /* #196: @26 = horzcat(@22, @23, @27) */
  rr=w26;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #197: @24 = @26' */
  for (i=0, rr=w24, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #198: @5 = 0 */
  w5 = 0.;
  /* #199: @7 = @13[2] */
  for (rr=(&w7), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #200: @7 = (-@7) */
  w7 = (- w7 );
  /* #201: @4 = @13[1] */
  for (rr=(&w4), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #202: @22 = horzcat(@5, @7, @4) */
  rr=w22;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #203: @22 = @22' */
  /* #204: @5 = @13[2] */
  for (rr=(&w5), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #205: @7 = 0 */
  w7 = 0.;
  /* #206: @4 = @13[0] */
  for (rr=(&w4), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #207: @4 = (-@4) */
  w4 = (- w4 );
  /* #208: @23 = horzcat(@5, @7, @4) */
  rr=w23;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #209: @23 = @23' */
  /* #210: @5 = @13[1] */
  for (rr=(&w5), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #211: @5 = (-@5) */
  w5 = (- w5 );
  /* #212: @7 = @13[0] */
  for (rr=(&w7), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #213: @4 = 0 */
  w4 = 0.;
  /* #214: @27 = horzcat(@5, @7, @4) */
  rr=w27;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #215: @27 = @27' */
  /* #216: @26 = horzcat(@22, @23, @27) */
  rr=w26;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #217: @28 = @26' */
  for (i=0, rr=w28, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #218: @25 = mac(@24,@28,@25) */
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w24+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #219: @25 = (@6*@25) */
  for (i=0, rr=w25, cs=w25; i<9; ++i) (*rr++)  = (w6*(*cs++));
  /* #220: @14 = (@14-@25) */
  for (i=0, rr=w14, cs=w25; i<9; ++i) (*rr++) -= (*cs++);
  /* #221: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++) += (*cs++);
  /* #222: @22 = 
  [[0.00208, 00, 00], 
   [00, 0.0118146, 00], 
   [00, 00, 0.0118146]] */
  casadi_copy(casadi_c5, 3, w22);
  /* #223: @14 = dense(@22) */
  casadi_densify(w22, casadi_s0, w14, 0);
  /* #224: @5 = 2.6 */
  w5 = 2.6000000000000001e+00;
  /* #225: @25 = zeros(3x3) */
  casadi_clear(w25, 9);
  /* #226: @7 = 0 */
  w7 = 0.;
  /* #227: @22 = [0.7195, 0, 0.13] */
  casadi_copy(casadi_c6, 3, w22);
  /* #228: @22 = (@11+@22) */
  for (i=0, rr=w22, cr=w11, cs=w22; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #229: @4 = 0.223 */
  w4 = 2.2300000000000000e-01;
  /* #230: @8 = @2[14] */
  for (rr=(&w8), ss=w2+14; ss!=w2+15; ss+=1) *rr++ = *ss;
  /* #231: @9 = 100 */
  w9 = 100.;
  /* #232: @8 = (@8/@9) */
  w8 /= w9;
  /* #233: @4 = (@4*@8) */
  w4 *= w8;
  /* #234: @8 = 0 */
  w8 = 0.;
  /* #235: @9 = 0 */
  w9 = 0.;
  /* #236: @23 = vertcat(@4, @8, @9) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w8;
  *rr++ = w9;
  /* #237: @22 = (@22+@23) */
  for (i=0, rr=w22, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #238: @4 = @22[2] */
  for (rr=(&w4), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #239: @4 = (-@4) */
  w4 = (- w4 );
  /* #240: @8 = @22[1] */
  for (rr=(&w8), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #241: @23 = horzcat(@7, @4, @8) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #242: @23 = @23' */
  /* #243: @7 = @22[2] */
  for (rr=(&w7), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #244: @4 = 0 */
  w4 = 0.;
  /* #245: @8 = @22[0] */
  for (rr=(&w8), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #246: @8 = (-@8) */
  w8 = (- w8 );
  /* #247: @27 = horzcat(@7, @4, @8) */
  rr=w27;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #248: @27 = @27' */
  /* #249: @7 = @22[1] */
  for (rr=(&w7), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #250: @7 = (-@7) */
  w7 = (- w7 );
  /* #251: @4 = @22[0] */
  for (rr=(&w4), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #252: @8 = 0 */
  w8 = 0.;
  /* #253: @29 = horzcat(@7, @4, @8) */
  rr=w29;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #254: @29 = @29' */
  /* #255: @24 = horzcat(@23, @27, @29) */
  rr=w24;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  /* #256: @28 = @24' */
  for (i=0, rr=w28, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #257: @7 = 0 */
  w7 = 0.;
  /* #258: @4 = @22[2] */
  for (rr=(&w4), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #259: @4 = (-@4) */
  w4 = (- w4 );
  /* #260: @8 = @22[1] */
  for (rr=(&w8), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #261: @23 = horzcat(@7, @4, @8) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #262: @23 = @23' */
  /* #263: @7 = @22[2] */
  for (rr=(&w7), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #264: @4 = 0 */
  w4 = 0.;
  /* #265: @8 = @22[0] */
  for (rr=(&w8), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #266: @8 = (-@8) */
  w8 = (- w8 );
  /* #267: @27 = horzcat(@7, @4, @8) */
  rr=w27;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #268: @27 = @27' */
  /* #269: @7 = @22[1] */
  for (rr=(&w7), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #270: @7 = (-@7) */
  w7 = (- w7 );
  /* #271: @4 = @22[0] */
  for (rr=(&w4), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #272: @8 = 0 */
  w8 = 0.;
  /* #273: @29 = horzcat(@7, @4, @8) */
  rr=w29;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #274: @29 = @29' */
  /* #275: @24 = horzcat(@23, @27, @29) */
  rr=w24;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  /* #276: @26 = @24' */
  for (i=0, rr=w26, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #277: @25 = mac(@28,@26,@25) */
  for (i=0, rr=w25; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w28+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #278: @25 = (@5*@25) */
  for (i=0, rr=w25, cs=w25; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #279: @14 = (@14-@25) */
  for (i=0, rr=w14, cs=w25; i<9; ++i) (*rr++) -= (*cs++);
  /* #280: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++) += (*cs++);
  /* #281: @18 = diagcat(@0, @15) */
  rr=w18;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<9; ++i) *rr++ = *cs++;
  /* #282: @5 = 0.0298523 */
  w5 = 2.9852318056049005e-02;
  /* #283: @5 = (@5*@1) */
  w5 *= w1;
  /* #284: @7 = 0.943659 */
  w7 = 9.4365917249249198e-01;
  /* #285: @7 = (@7*@1) */
  w7 *= w1;
  /* #286: @4 = 0.943659 */
  w4 = 9.4365917249249198e-01;
  /* #287: @4 = (@4*@1) */
  w4 *= w1;
  /* #288: @8 = 0.3 */
  w8 = 2.9999999999999999e-01;
  /* #289: @9 = @15[0] */
  for (rr=(&w9), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #290: @8 = (@8*@9) */
  w8 *= w9;
  /* #291: @9 = 0.836375 */
  w9 = 8.3637530823391681e-01;
  /* #292: @10 = @15[4] */
  for (rr=(&w10), ss=w15+4; ss!=w15+5; ss+=1) *rr++ = *ss;
  /* #293: @9 = (@9*@10) */
  w9 *= w10;
  /* #294: @10 = 0.836375 */
  w10 = 8.3637530823391681e-01;
  /* #295: @30 = @15[4] */
  for (rr=(&w30), ss=w15+4; ss!=w15+5; ss+=1) *rr++ = *ss;
  /* #296: @10 = (@10*@30) */
  w10 *= w30;
  /* #297: @31 = vertcat(@5, @7, @4, @8, @9, @10) */
  rr=w31;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #298: @31 = sparsity_cast(@31) */
  /* #299: @17 = project(@31) */
  casadi_project(w31, casadi_s1, w17, casadi_s2, w);
  /* #300: @17 = (@18+@17) */
  for (i=0, rr=w17, cr=w18, cs=w17; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #301: @21 = (@17\@21) */
  rr = w21;
  ss = w17;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[9], r[9], beta[6], w[12];
    casadi_qr(casadi_s2, ss, w, casadi_s4, v, casadi_s5, r, beta, casadi_s3, casadi_s3);
    casadi_qr_solve(rr, 6, 0, casadi_s4, v, casadi_s5, r, beta, casadi_s3, casadi_s3, w);
  }
  /* #302: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #303: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #304: @5 = @2[16] */
  for (rr=(&w5), ss=w2+16; ss!=w2+17; ss+=1) *rr++ = *ss;
  /* #305: @7 = cos(@5) */
  w7 = cos( w5 );
  /* #306: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #307: @4 = 0 */
  w4 = 0.;
  /* #308: @23 = horzcat(@7, @5, @4) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w5;
  *rr++ = w4;
  /* #309: @23 = @23' */
  /* #310: @5 = (-@5) */
  w5 = (- w5 );
  /* #311: @4 = 0 */
  w4 = 0.;
  /* #312: @27 = horzcat(@5, @7, @4) */
  rr=w27;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #313: @27 = @27' */
  /* #314: @29 = [[0, 0, 1]] */
  casadi_copy(casadi_c7, 3, w29);
  /* #315: @29 = @29' */
  /* #316: @14 = horzcat(@23, @27, @29) */
  rr=w14;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  /* #317: @25 = @14' */
  for (i=0, rr=w25, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #318: @5 = @2[15] */
  for (rr=(&w5), ss=w2+15; ss!=w2+16; ss+=1) *rr++ = *ss;
  /* #319: @7 = cos(@5) */
  w7 = cos( w5 );
  /* #320: @4 = 0 */
  w4 = 0.;
  /* #321: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #322: @8 = (-@5) */
  w8 = (- w5 );
  /* #323: @23 = horzcat(@7, @4, @8) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #324: @23 = @23' */
  /* #325: @27 = [[0, 1, 0]] */
  casadi_copy(casadi_c8, 3, w27);
  /* #326: @27 = @27' */
  /* #327: @4 = 0 */
  w4 = 0.;
  /* #328: @29 = horzcat(@5, @4, @7) */
  rr=w29;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w7;
  /* #329: @29 = @29' */
  /* #330: @14 = horzcat(@23, @27, @29) */
  rr=w14;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<3; ++i) *rr++ = *cs++;
  /* #331: @28 = @14' */
  for (i=0, rr=w28, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #332: @15 = mac(@25,@28,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w25+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #333: @5 = 0 */
  w5 = 0.;
  /* #334: @32 = @2[17:19] */
  for (rr=w32, ss=w2+17; ss!=w2+19; ss+=1) *rr++ = *ss;
  /* #335: @4 = 60 */
  w4 = 60.;
  /* #336: @32 = (@32/@4) */
  for (i=0, rr=w32; i<2; ++i) (*rr++) /= w4;
  /* #337: @4 = @32[0] */
  for (rr=(&w4), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #338: @4 = sign(@4) */
  w4 = casadi_sign( w4 );
  /* #339: @5 = (@5<@4) */
  w5  = (w5<w4);
  /* #340: @4 = 0.394148 */
  w4 = 3.9414816000000014e-01;
  /* #341: @7 = 0.4566 */
  w7 = 4.5660000000000001e-01;
  /* #342: @8 = @32[0] */
  for (rr=(&w8), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #343: @8 = fabs(@8) */
  w8 = casadi_fabs( w8 );
  /* #344: @7 = (@7*@8) */
  w7 *= w8;
  /* #345: @8 = @32[0] */
  for (rr=(&w8), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #346: @7 = (@7*@8) */
  w7 *= w8;
  /* #347: @8 = -0.41737 */
  w8 = -4.1737032569360683e-01;
  /* #348: @9 = 0.944 */
  w9 = 9.4399999999999995e-01;
  /* #349: @10 = @2[7] */
  for (rr=(&w10), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #350: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #351: @30 = @2[8] */
  for (rr=(&w30), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #352: @30 = sq(@30) */
  w30 = casadi_sq( w30 );
  /* #353: @10 = (@10+@30) */
  w10 += w30;
  /* #354: @30 = @2[9] */
  for (rr=(&w30), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #355: @30 = sq(@30) */
  w30 = casadi_sq( w30 );
  /* #356: @10 = (@10+@30) */
  w10 += w30;
  /* #357: @10 = sqrt(@10) */
  w10 = sqrt( w10 );
  /* #358: @9 = (@9*@10) */
  w9 *= w10;
  /* #359: @10 = 0.14 */
  w10 = 1.4000000000000001e-01;
  /* #360: @10 = (@9/@10) */
  w10  = (w9/w10);
  /* #361: @8 = (@8*@10) */
  w8 *= w10;
  /* #362: @10 = @32[0] */
  for (rr=(&w10), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #363: @10 = fabs(@10) */
  w10 = casadi_fabs( w10 );
  /* #364: @8 = (@8*@10) */
  w8 *= w10;
  /* #365: @7 = (@7+@8) */
  w7 += w8;
  /* #366: @4 = (@4*@7) */
  w4 *= w7;
  /* #367: @4 = (@5?@4:0) */
  w4  = (w5?w4:0);
  /* #368: @5 = (!@5) */
  w5 = (! w5 );
  /* #369: @7 = 0.394148 */
  w7 = 3.9414816000000014e-01;
  /* #370: @8 = 0.4566 */
  w8 = 4.5660000000000001e-01;
  /* #371: @10 = @32[0] */
  for (rr=(&w10), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #372: @10 = fabs(@10) */
  w10 = casadi_fabs( w10 );
  /* #373: @8 = (@8*@10) */
  w8 *= w10;
  /* #374: @10 = @32[0] */
  for (rr=(&w10), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #375: @8 = (@8*@10) */
  w8 *= w10;
  /* #376: @7 = (@7*@8) */
  w7 *= w8;
  /* #377: @8 = 10 */
  w8 = 10.;
  /* #378: @7 = (@7/@8) */
  w7 /= w8;
  /* #379: @5 = (@5?@7:0) */
  w5  = (w5?w7:0);
  /* #380: @4 = (@4+@5) */
  w4 += w5;
  /* #381: @5 = 0 */
  w5 = 0.;
  /* #382: @7 = 0 */
  w7 = 0.;
  /* #383: @23 = vertcat(@4, @5, @7) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w7;
  /* #384: @0 = mac(@15,@23,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #385: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #386: @27 = [0.03, 0, 0] */
  casadi_copy(casadi_c9, 3, w27);
  /* #387: @23 = mac(@15,@27,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #388: @23 = (@23-@11) */
  for (i=0, rr=w23, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #389: @4 = @23[1] */
  for (rr=(&w4), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #390: @5 = @0[2] */
  for (rr=(&w5), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #391: @7 = (@4*@5) */
  w7  = (w4*w5);
  /* #392: @8 = @23[2] */
  for (rr=(&w8), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #393: @10 = @0[1] */
  for (rr=(&w10), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #394: @30 = (@8*@10) */
  w30  = (w8*w10);
  /* #395: @7 = (@7-@30) */
  w7 -= w30;
  /* #396: @30 = @0[0] */
  for (rr=(&w30), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #397: @8 = (@8*@30) */
  w8 *= w30;
  /* #398: @33 = @23[0] */
  for (rr=(&w33), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #399: @5 = (@33*@5) */
  w5  = (w33*w5);
  /* #400: @8 = (@8-@5) */
  w8 -= w5;
  /* #401: @33 = (@33*@10) */
  w33 *= w10;
  /* #402: @4 = (@4*@30) */
  w4 *= w30;
  /* #403: @33 = (@33-@4) */
  w33 -= w4;
  /* #404: @23 = vertcat(@7, @8, @33) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w33;
  /* #405: @7 = 0 */
  w7 = 0.;
  /* #406: @8 = @32[0] */
  for (rr=(&w8), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #407: @8 = sign(@8) */
  w8 = casadi_sign( w8 );
  /* #408: @7 = (@7<@8) */
  w7  = (w7<w8);
  /* #409: @8 = 0.0551807 */
  w8 = 5.5180742400000024e-02;
  /* #410: @33 = 0.07 */
  w33 = 7.0000000000000007e-02;
  /* #411: @4 = @32[0] */
  for (rr=(&w4), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #412: @4 = fabs(@4) */
  w4 = casadi_fabs( w4 );
  /* #413: @33 = (@33*@4) */
  w33 *= w4;
  /* #414: @4 = @32[0] */
  for (rr=(&w4), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #415: @33 = (@33*@4) */
  w33 *= w4;
  /* #416: @4 = -0.0585042 */
  w4 = -5.8504221954161655e-02;
  /* #417: @30 = 0.14 */
  w30 = 1.4000000000000001e-01;
  /* #418: @30 = (@9/@30) */
  w30  = (w9/w30);
  /* #419: @4 = (@4*@30) */
  w4 *= w30;
  /* #420: @30 = @32[0] */
  for (rr=(&w30), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #421: @30 = fabs(@30) */
  w30 = casadi_fabs( w30 );
  /* #422: @4 = (@4*@30) */
  w4 *= w30;
  /* #423: @33 = (@33+@4) */
  w33 += w4;
  /* #424: @8 = (@8*@33) */
  w8 *= w33;
  /* #425: @8 = (@7?@8:0) */
  w8  = (w7?w8:0);
  /* #426: @7 = (!@7) */
  w7 = (! w7 );
  /* #427: @33 = 0.00386265 */
  w33 = 3.8626519680000021e-03;
  /* #428: @4 = @32[0] */
  for (rr=(&w4), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #429: @4 = fabs(@4) */
  w4 = casadi_fabs( w4 );
  /* #430: @33 = (@33*@4) */
  w33 *= w4;
  /* #431: @4 = @32[0] */
  for (rr=(&w4), ss=w32+0; ss!=w32+1; ss+=1) *rr++ = *ss;
  /* #432: @33 = (@33*@4) */
  w33 *= w4;
  /* #433: @4 = 10 */
  w4 = 10.;
  /* #434: @33 = (@33/@4) */
  w33 /= w4;
  /* #435: @7 = (@7?@33:0) */
  w7  = (w7?w33:0);
  /* #436: @8 = (@8+@7) */
  w8 += w7;
  /* #437: @7 = 0 */
  w7 = 0.;
  /* #438: @33 = 0 */
  w33 = 0.;
  /* #439: @27 = vertcat(@8, @7, @33) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w33;
  /* #440: @23 = (@23+@27) */
  for (i=0, rr=w23, cs=w27; i<3; ++i) (*rr++) += (*cs++);
  /* #441: @34 = vertcat(@0, @23) */
  rr=w34;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #442: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #443: @8 = 0 */
  w8 = 0.;
  /* #444: @7 = @32[1] */
  for (rr=(&w7), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #445: @7 = sign(@7) */
  w7 = casadi_sign( w7 );
  /* #446: @8 = (@8<@7) */
  w8  = (w8<w7);
  /* #447: @7 = 0.394148 */
  w7 = 3.9414816000000014e-01;
  /* #448: @33 = 0.4566 */
  w33 = 4.5660000000000001e-01;
  /* #449: @4 = @32[1] */
  for (rr=(&w4), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #450: @4 = fabs(@4) */
  w4 = casadi_fabs( w4 );
  /* #451: @33 = (@33*@4) */
  w33 *= w4;
  /* #452: @4 = @32[1] */
  for (rr=(&w4), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #453: @33 = (@33*@4) */
  w33 *= w4;
  /* #454: @4 = -0.41737 */
  w4 = -4.1737032569360683e-01;
  /* #455: @30 = 0.14 */
  w30 = 1.4000000000000001e-01;
  /* #456: @30 = (@9/@30) */
  w30  = (w9/w30);
  /* #457: @4 = (@4*@30) */
  w4 *= w30;
  /* #458: @30 = @32[1] */
  for (rr=(&w30), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #459: @30 = fabs(@30) */
  w30 = casadi_fabs( w30 );
  /* #460: @4 = (@4*@30) */
  w4 *= w30;
  /* #461: @33 = (@33+@4) */
  w33 += w4;
  /* #462: @7 = (@7*@33) */
  w7 *= w33;
  /* #463: @7 = (@8?@7:0) */
  w7  = (w8?w7:0);
  /* #464: @8 = (!@8) */
  w8 = (! w8 );
  /* #465: @33 = 0.394148 */
  w33 = 3.9414816000000014e-01;
  /* #466: @4 = 0.4566 */
  w4 = 4.5660000000000001e-01;
  /* #467: @30 = @32[1] */
  for (rr=(&w30), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #468: @30 = fabs(@30) */
  w30 = casadi_fabs( w30 );
  /* #469: @4 = (@4*@30) */
  w4 *= w30;
  /* #470: @30 = @32[1] */
  for (rr=(&w30), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #471: @4 = (@4*@30) */
  w4 *= w30;
  /* #472: @33 = (@33*@4) */
  w33 *= w4;
  /* #473: @4 = 10 */
  w4 = 10.;
  /* #474: @33 = (@33/@4) */
  w33 /= w4;
  /* #475: @8 = (@8?@33:0) */
  w8  = (w8?w33:0);
  /* #476: @7 = (@7+@8) */
  w7 += w8;
  /* #477: @8 = 0 */
  w8 = 0.;
  /* #478: @33 = 0 */
  w33 = 0.;
  /* #479: @23 = vertcat(@7, @8, @33) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w33;
  /* #480: @0 = mac(@15,@23,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #481: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #482: @27 = [0.04, 0, 0] */
  casadi_copy(casadi_c10, 3, w27);
  /* #483: @23 = mac(@15,@27,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #484: @23 = (@23-@11) */
  for (i=0, rr=w23, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #485: @7 = @23[1] */
  for (rr=(&w7), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #486: @8 = @0[2] */
  for (rr=(&w8), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #487: @33 = (@7*@8) */
  w33  = (w7*w8);
  /* #488: @4 = @23[2] */
  for (rr=(&w4), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #489: @30 = @0[1] */
  for (rr=(&w30), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #490: @10 = (@4*@30) */
  w10  = (w4*w30);
  /* #491: @33 = (@33-@10) */
  w33 -= w10;
  /* #492: @10 = @0[0] */
  for (rr=(&w10), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #493: @4 = (@4*@10) */
  w4 *= w10;
  /* #494: @5 = @23[0] */
  for (rr=(&w5), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #495: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #496: @4 = (@4-@8) */
  w4 -= w8;
  /* #497: @5 = (@5*@30) */
  w5 *= w30;
  /* #498: @7 = (@7*@10) */
  w7 *= w10;
  /* #499: @5 = (@5-@7) */
  w5 -= w7;
  /* #500: @23 = vertcat(@33, @4, @5) */
  rr=w23;
  *rr++ = w33;
  *rr++ = w4;
  *rr++ = w5;
  /* #501: @33 = 0 */
  w33 = 0.;
  /* #502: @4 = @32[1] */
  for (rr=(&w4), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #503: @4 = sign(@4) */
  w4 = casadi_sign( w4 );
  /* #504: @33 = (@33<@4) */
  w33  = (w33<w4);
  /* #505: @4 = 0.0551807 */
  w4 = 5.5180742400000024e-02;
  /* #506: @5 = 0.07 */
  w5 = 7.0000000000000007e-02;
  /* #507: @7 = @32[1] */
  for (rr=(&w7), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #508: @7 = fabs(@7) */
  w7 = casadi_fabs( w7 );
  /* #509: @5 = (@5*@7) */
  w5 *= w7;
  /* #510: @7 = @32[1] */
  for (rr=(&w7), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #511: @5 = (@5*@7) */
  w5 *= w7;
  /* #512: @7 = -0.0585042 */
  w7 = -5.8504221954161655e-02;
  /* #513: @10 = 0.14 */
  w10 = 1.4000000000000001e-01;
  /* #514: @9 = (@9/@10) */
  w9 /= w10;
  /* #515: @7 = (@7*@9) */
  w7 *= w9;
  /* #516: @9 = @32[1] */
  for (rr=(&w9), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #517: @9 = fabs(@9) */
  w9 = casadi_fabs( w9 );
  /* #518: @7 = (@7*@9) */
  w7 *= w9;
  /* #519: @5 = (@5+@7) */
  w5 += w7;
  /* #520: @4 = (@4*@5) */
  w4 *= w5;
  /* #521: @4 = (@33?@4:0) */
  w4  = (w33?w4:0);
  /* #522: @33 = (!@33) */
  w33 = (! w33 );
  /* #523: @5 = 0.00386265 */
  w5 = 3.8626519680000021e-03;
  /* #524: @7 = @32[1] */
  for (rr=(&w7), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #525: @7 = fabs(@7) */
  w7 = casadi_fabs( w7 );
  /* #526: @5 = (@5*@7) */
  w5 *= w7;
  /* #527: @7 = @32[1] */
  for (rr=(&w7), ss=w32+1; ss!=w32+2; ss+=1) *rr++ = *ss;
  /* #528: @5 = (@5*@7) */
  w5 *= w7;
  /* #529: @7 = 10 */
  w7 = 10.;
  /* #530: @5 = (@5/@7) */
  w5 /= w7;
  /* #531: @33 = (@33?@5:0) */
  w33  = (w33?w5:0);
  /* #532: @4 = (@4+@33) */
  w4 += w33;
  /* #533: @4 = (-@4) */
  w4 = (- w4 );
  /* #534: @33 = 0 */
  w33 = 0.;
  /* #535: @5 = 0 */
  w5 = 0.;
  /* #536: @11 = vertcat(@4, @33, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #537: @23 = (@23+@11) */
  for (i=0, rr=w23, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #538: @35 = vertcat(@0, @23) */
  rr=w35;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #539: @34 = (@34+@35) */
  for (i=0, rr=w34, cs=w35; i<6; ++i) (*rr++) += (*cs++);
  /* #540: @35 = zeros(6x1) */
  casadi_clear(w35, 6);
  /* #541: @36 = zeros(6x6) */
  casadi_clear(w36, 36);
  /* #542: @4 = 0 */
  w4 = 0.;
  /* #543: @33 = 0.5 */
  w33 = 5.0000000000000000e-01;
  /* #544: @17 = @18' */
  casadi_trans(w18,casadi_s2, w17, casadi_s2, iw);
  /* #545: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #546: @18 = (@33*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w33*(*cs++));
  /* #547: @0 = @18[:3] */
  for (rr=w0, ss=w18+0; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #548: @0 = nonzeros(@0) */
  /* #549: @23 = @2[7:10] */
  for (rr=w23, ss=w2+7; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #550: @0 = (@0*@23) */
  for (i=0, rr=w0, cs=w23; i<3; ++i) (*rr++) *= (*cs++);
  /* #551: @33 = @0[2] */
  for (rr=(&w33), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #552: @33 = (-@33) */
  w33 = (- w33 );
  /* #553: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #554: @23 = horzcat(@4, @33, @5) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #555: @23 = @23' */
  /* #556: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #557: @33 = 0 */
  w33 = 0.;
  /* #558: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #559: @5 = (-@5) */
  w5 = (- w5 );
  /* #560: @11 = horzcat(@4, @33, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #561: @11 = @11' */
  /* #562: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #563: @4 = (-@4) */
  w4 = (- w4 );
  /* #564: @33 = @0[0] */
  for (rr=(&w33), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #565: @5 = 0 */
  w5 = 0.;
  /* #566: @27 = horzcat(@4, @33, @5) */
  rr=w27;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #567: @27 = @27' */
  /* #568: @15 = horzcat(@23, @11, @27) */
  rr=w15;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #569: @25 = @15' */
  for (i=0, rr=w25, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #570: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<9; ++i) *rr++ = (- *cs++ );
  /* #571: (@36[18, 19, 20, 24, 25, 26, 30, 31, 32] = @25) */
  for (cii=casadi_s6, rr=w36, ss=w25; cii!=casadi_s6+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #572: @4 = 0 */
  w4 = 0.;
  /* #573: @33 = @0[2] */
  for (rr=(&w33), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #574: @33 = (-@33) */
  w33 = (- w33 );
  /* #575: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #576: @23 = horzcat(@4, @33, @5) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #577: @23 = @23' */
  /* #578: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #579: @33 = 0 */
  w33 = 0.;
  /* #580: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #581: @5 = (-@5) */
  w5 = (- w5 );
  /* #582: @11 = horzcat(@4, @33, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #583: @11 = @11' */
  /* #584: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #585: @4 = (-@4) */
  w4 = (- w4 );
  /* #586: @33 = @0[0] */
  for (rr=(&w33), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #587: @5 = 0 */
  w5 = 0.;
  /* #588: @0 = horzcat(@4, @33, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #589: @0 = @0' */
  /* #590: @25 = horzcat(@23, @11, @0) */
  rr=w25;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  /* #591: @15 = @25' */
  for (i=0, rr=w15, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #592: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<9; ++i) *rr++ = (- *cs++ );
  /* #593: (@36[:18:6;3:6] = @15) */
  for (rr=w36+0, ss=w15; rr!=w36+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #594: @4 = 0 */
  w4 = 0.;
  /* #595: @23 = zeros(3x1) */
  casadi_clear(w23, 3);
  /* #596: @15 = @18[3:12] */
  for (rr=w15, ss=w18+3; ss!=w18+12; ss+=1) *rr++ = *ss;
  /* #597: @11 = @2[10:13] */
  for (rr=w11, ss=w2+10; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #598: @23 = mac(@15,@11,@23) */
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #599: @33 = @23[2] */
  for (rr=(&w33), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #600: @33 = (-@33) */
  w33 = (- w33 );
  /* #601: @5 = @23[1] */
  for (rr=(&w5), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #602: @11 = horzcat(@4, @33, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #603: @11 = @11' */
  /* #604: @4 = @23[2] */
  for (rr=(&w4), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #605: @33 = 0 */
  w33 = 0.;
  /* #606: @5 = @23[0] */
  for (rr=(&w5), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #607: @5 = (-@5) */
  w5 = (- w5 );
  /* #608: @0 = horzcat(@4, @33, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #609: @0 = @0' */
  /* #610: @4 = @23[1] */
  for (rr=(&w4), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #611: @4 = (-@4) */
  w4 = (- w4 );
  /* #612: @33 = @23[0] */
  for (rr=(&w33), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #613: @5 = 0 */
  w5 = 0.;
  /* #614: @23 = horzcat(@4, @33, @5) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #615: @23 = @23' */
  /* #616: @15 = horzcat(@11, @0, @23) */
  rr=w15;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  /* #617: @25 = @15' */
  for (i=0, rr=w25, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #618: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<9; ++i) *rr++ = (- *cs++ );
  /* #619: (@36[21, 22, 23, 27, 28, 29, 33, 34, 35] = @25) */
  for (cii=casadi_s7, rr=w36, ss=w25; cii!=casadi_s7+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #620: @37 = zeros(6x6) */
  casadi_clear(w37, 36);
  /* #621: @4 = 0 */
  w4 = 0.;
  /* #622: @33 = 0.5 */
  w33 = 5.0000000000000000e-01;
  /* #623: @38 = @31' */
  casadi_trans(w31,casadi_s1, w38, casadi_s1, iw);
  /* #624: @31 = (@31+@38) */
  for (i=0, rr=w31, cs=w38; i<6; ++i) (*rr++) += (*cs++);
  /* #625: @31 = (@33*@31) */
  for (i=0, rr=w31, cs=w31; i<6; ++i) (*rr++)  = (w33*(*cs++));
  /* #626: @11 = @31[:3] */
  for (rr=w11, ss=w31+0; ss!=w31+3; ss+=1) *rr++ = *ss;
  /* #627: @11 = nonzeros(@11) */
  /* #628: @0 = @2[7:10] */
  for (rr=w0, ss=w2+7; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #629: @11 = (@11*@0) */
  for (i=0, rr=w11, cs=w0; i<3; ++i) (*rr++) *= (*cs++);
  /* #630: @33 = @11[2] */
  for (rr=(&w33), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #631: @33 = (-@33) */
  w33 = (- w33 );
  /* #632: @5 = @11[1] */
  for (rr=(&w5), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #633: @0 = horzcat(@4, @33, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #634: @0 = @0' */
  /* #635: @4 = @11[2] */
  for (rr=(&w4), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #636: @33 = 0 */
  w33 = 0.;
  /* #637: @5 = @11[0] */
  for (rr=(&w5), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #638: @5 = (-@5) */
  w5 = (- w5 );
  /* #639: @23 = horzcat(@4, @33, @5) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #640: @23 = @23' */
  /* #641: @4 = @11[1] */
  for (rr=(&w4), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #642: @4 = (-@4) */
  w4 = (- w4 );
  /* #643: @33 = @11[0] */
  for (rr=(&w33), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #644: @5 = 0 */
  w5 = 0.;
  /* #645: @27 = horzcat(@4, @33, @5) */
  rr=w27;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #646: @27 = @27' */
  /* #647: @25 = horzcat(@0, @23, @27) */
  rr=w25;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #648: @15 = @25' */
  for (i=0, rr=w15, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #649: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<9; ++i) *rr++ = (- *cs++ );
  /* #650: (@37[18, 19, 20, 24, 25, 26, 30, 31, 32] = @15) */
  for (cii=casadi_s6, rr=w37, ss=w15; cii!=casadi_s6+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #651: @4 = 0 */
  w4 = 0.;
  /* #652: @33 = @11[2] */
  for (rr=(&w33), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #653: @33 = (-@33) */
  w33 = (- w33 );
  /* #654: @5 = @11[1] */
  for (rr=(&w5), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #655: @0 = horzcat(@4, @33, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #656: @0 = @0' */
  /* #657: @4 = @11[2] */
  for (rr=(&w4), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #658: @33 = 0 */
  w33 = 0.;
  /* #659: @5 = @11[0] */
  for (rr=(&w5), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #660: @5 = (-@5) */
  w5 = (- w5 );
  /* #661: @23 = horzcat(@4, @33, @5) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #662: @23 = @23' */
  /* #663: @4 = @11[1] */
  for (rr=(&w4), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #664: @4 = (-@4) */
  w4 = (- w4 );
  /* #665: @33 = @11[0] */
  for (rr=(&w33), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #666: @5 = 0 */
  w5 = 0.;
  /* #667: @11 = horzcat(@4, @33, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #668: @11 = @11' */
  /* #669: @15 = horzcat(@0, @23, @11) */
  rr=w15;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  /* #670: @25 = @15' */
  for (i=0, rr=w25, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #671: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<9; ++i) *rr++ = (- *cs++ );
  /* #672: (@37[:18:6;3:6] = @25) */
  for (rr=w37+0, ss=w25; rr!=w37+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #673: @4 = 0 */
  w4 = 0.;
  /* #674: @0 = @31[3:6] */
  for (rr=w0, ss=w31+3; ss!=w31+6; ss+=1) *rr++ = *ss;
  /* #675: @0 = nonzeros(@0) */
  /* #676: @23 = @2[10:13] */
  for (rr=w23, ss=w2+10; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #677: @0 = (@0*@23) */
  for (i=0, rr=w0, cs=w23; i<3; ++i) (*rr++) *= (*cs++);
  /* #678: @33 = @0[2] */
  for (rr=(&w33), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #679: @33 = (-@33) */
  w33 = (- w33 );
  /* #680: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #681: @23 = horzcat(@4, @33, @5) */
  rr=w23;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #682: @23 = @23' */
  /* #683: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #684: @33 = 0 */
  w33 = 0.;
  /* #685: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #686: @5 = (-@5) */
  w5 = (- w5 );
  /* #687: @11 = horzcat(@4, @33, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #688: @11 = @11' */
  /* #689: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #690: @4 = (-@4) */
  w4 = (- w4 );
  /* #691: @33 = @0[0] */
  for (rr=(&w33), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #692: @5 = 0 */
  w5 = 0.;
  /* #693: @0 = horzcat(@4, @33, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w33;
  *rr++ = w5;
  /* #694: @0 = @0' */
  /* #695: @25 = horzcat(@23, @11, @0) */
  rr=w25;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  /* #696: @15 = @25' */
  for (i=0, rr=w15, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #697: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<9; ++i) *rr++ = (- *cs++ );
  /* #698: (@37[21, 22, 23, 27, 28, 29, 33, 34, 35] = @15) */
  for (cii=casadi_s7, rr=w37, ss=w15; cii!=casadi_s7+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #699: @4 = 0 */
  w4 = 0.;
  /* #700: (@37[4] = @4) */
  for (rr=w37+4, ss=(&w4); rr!=w37+5; rr+=1) *rr = *ss++;
  /* #701: @4 = 0 */
  w4 = 0.;
  /* #702: (@37[24] = @4) */
  for (rr=w37+24, ss=(&w4); rr!=w37+25; rr+=1) *rr = *ss++;
  /* #703: @4 = 0 */
  w4 = 0.;
  /* #704: (@37[16] = @4) */
  for (rr=w37+16, ss=(&w4); rr!=w37+17; rr+=1) *rr = *ss++;
  /* #705: @4 = 0 */
  w4 = 0.;
  /* #706: (@37[26] = @4) */
  for (rr=w37+26, ss=(&w4); rr!=w37+27; rr+=1) *rr = *ss++;
  /* #707: @4 = 0 */
  w4 = 0.;
  /* #708: (@37[5] = @4) */
  for (rr=w37+5, ss=(&w4); rr!=w37+6; rr+=1) *rr = *ss++;
  /* #709: @4 = 0 */
  w4 = 0.;
  /* #710: (@37[30] = @4) */
  for (rr=w37+30, ss=(&w4); rr!=w37+31; rr+=1) *rr = *ss++;
  /* #711: @4 = 0 */
  w4 = 0.;
  /* #712: (@37[11] = @4) */
  for (rr=w37+11, ss=(&w4); rr!=w37+12; rr+=1) *rr = *ss++;
  /* #713: @4 = 0 */
  w4 = 0.;
  /* #714: (@37[31] = @4) */
  for (rr=w37+31, ss=(&w4); rr!=w37+32; rr+=1) *rr = *ss++;
  /* #715: @36 = (@36+@37) */
  for (i=0, rr=w36, cs=w37; i<36; ++i) (*rr++) += (*cs++);
  /* #716: @31 = @2[7:13] */
  for (rr=w31, ss=w2+7; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #717: @35 = mac(@36,@31,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w36+j, tt=w31+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #718: @34 = (@34-@35) */
  for (i=0, rr=w34, cs=w35; i<6; ++i) (*rr++) -= (*cs++);
  /* #719: @35 = zeros(6x1) */
  casadi_clear(w35, 6);
  /* #720: @36 = zeros(6x6) */
  casadi_clear(w36, 36);
  /* #721: @4 = 3 */
  w4 = 3.;
  /* #722: @33 = @2[7] */
  for (rr=(&w33), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #723: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #724: @4 = (@4*@33) */
  w4 *= w33;
  /* #725: (@36[0] = @4) */
  for (rr=w36+0, ss=(&w4); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #726: @4 = 50 */
  w4 = 50.;
  /* #727: @33 = @2[8] */
  for (rr=(&w33), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #728: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #729: @4 = (@4*@33) */
  w4 *= w33;
  /* #730: (@36[7] = @4) */
  for (rr=w36+7, ss=(&w4); rr!=w36+8; rr+=1) *rr = *ss++;
  /* #731: @4 = 50 */
  w4 = 50.;
  /* #732: @33 = @2[9] */
  for (rr=(&w33), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #733: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #734: @4 = (@4*@33) */
  w4 *= w33;
  /* #735: (@36[14] = @4) */
  for (rr=w36+14, ss=(&w4); rr!=w36+15; rr+=1) *rr = *ss++;
  /* #736: @4 = 40 */
  w4 = 40.;
  /* #737: @33 = @2[10] */
  for (rr=(&w33), ss=w2+10; ss!=w2+11; ss+=1) *rr++ = *ss;
  /* #738: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #739: @4 = (@4*@33) */
  w4 *= w33;
  /* #740: (@36[21] = @4) */
  for (rr=w36+21, ss=(&w4); rr!=w36+22; rr+=1) *rr = *ss++;
  /* #741: @4 = 200 */
  w4 = 200.;
  /* #742: @33 = @2[11] */
  for (rr=(&w33), ss=w2+11; ss!=w2+12; ss+=1) *rr++ = *ss;
  /* #743: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #744: @4 = (@4*@33) */
  w4 *= w33;
  /* #745: (@36[28] = @4) */
  for (rr=w36+28, ss=(&w4); rr!=w36+29; rr+=1) *rr = *ss++;
  /* #746: @4 = 10 */
  w4 = 10.;
  /* #747: @33 = @2[12] */
  for (rr=(&w33), ss=w2+12; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #748: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #749: @4 = (@4*@33) */
  w4 *= w33;
  /* #750: (@36[35] = @4) */
  for (rr=w36+35, ss=(&w4); rr!=w36+36; rr+=1) *rr = *ss++;
  /* #751: @4 = 0 */
  w4 = 0.;
  /* #752: (@36[4] = @4) */
  for (rr=w36+4, ss=(&w4); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #753: @4 = 0 */
  w4 = 0.;
  /* #754: (@36[5] = @4) */
  for (rr=w36+5, ss=(&w4); rr!=w36+6; rr+=1) *rr = *ss++;
  /* #755: @4 = 0 */
  w4 = 0.;
  /* #756: (@36[9] = @4) */
  for (rr=w36+9, ss=(&w4); rr!=w36+10; rr+=1) *rr = *ss++;
  /* #757: @4 = 5 */
  w4 = 5.;
  /* #758: @33 = @2[8] */
  for (rr=(&w33), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #759: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #760: @4 = (@4*@33) */
  w4 *= w33;
  /* #761: (@36[11] = @4) */
  for (rr=w36+11, ss=(&w4); rr!=w36+12; rr+=1) *rr = *ss++;
  /* #762: @4 = 0 */
  w4 = 0.;
  /* #763: (@36[15] = @4) */
  for (rr=w36+15, ss=(&w4); rr!=w36+16; rr+=1) *rr = *ss++;
  /* #764: @4 = -5 */
  w4 = -5.;
  /* #765: @33 = @2[9] */
  for (rr=(&w33), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #766: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #767: @4 = (@4*@33) */
  w4 *= w33;
  /* #768: (@36[16] = @4) */
  for (rr=w36+16, ss=(&w4); rr!=w36+17; rr+=1) *rr = *ss++;
  /* #769: @35 = mac(@36,@31,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w36+j, tt=w31+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #770: @34 = (@34-@35) */
  for (i=0, rr=w34, cs=w35; i<6; ++i) (*rr++) -= (*cs++);
  /* #771: @4 = 9.81 */
  w4 = 9.8100000000000005e+00;
  /* #772: @4 = (@4*@1) */
  w4 *= w1;
  /* #773: @33 = 172.96 */
  w33 = 1.7296006950873124e+02;
  /* #774: @33 = (@4-@33) */
  w33  = (w4-w33);
  /* #775: @16 = @2[3:7] */
  for (rr=w16, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #776: @5 = ||@16||_F */
  w5 = sqrt(casadi_dot(4, w16, w16));
  /* #777: @16 = (@16/@5) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w5;
  /* #778: @5 = @16[0] */
  for (rr=(&w5), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #779: @7 = @16[2] */
  for (rr=(&w7), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #780: @9 = (@5*@7) */
  w9  = (w5*w7);
  /* #781: @10 = @16[3] */
  for (rr=(&w10), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #782: @30 = @16[1] */
  for (rr=(&w30), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #783: @8 = (@10*@30) */
  w8  = (w10*w30);
  /* #784: @9 = (@9-@8) */
  w9 -= w8;
  /* #785: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #786: @9 = asin(@9) */
  w9 = asin( w9 );
  /* #787: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #788: @33 = (@33*@8) */
  w33 *= w8;
  /* #789: @39 = 172.96 */
  w39 = 1.7296006950873124e+02;
  /* #790: @39 = (@4-@39) */
  w39  = (w4-w39);
  /* #791: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #792: @39 = (@39*@9) */
  w39 *= w9;
  /* #793: @5 = (@5*@30) */
  w5 *= w30;
  /* #794: @10 = (@7*@10) */
  w10  = (w7*w10);
  /* #795: @5 = (@5+@10) */
  w5 += w10;
  /* #796: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #797: @10 = 1 */
  w10 = 1.;
  /* #798: @30 = sq(@30) */
  w30 = casadi_sq( w30 );
  /* #799: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #800: @30 = (@30+@7) */
  w30 += w7;
  /* #801: @30 = (2.*@30) */
  w30 = (2.* w30 );
  /* #802: @10 = (@10-@30) */
  w10 -= w30;
  /* #803: @5 = atan2(@5,@10) */
  w5  = atan2(w5,w10);
  /* #804: @10 = sin(@5) */
  w10 = sin( w5 );
  /* #805: @39 = (@39*@10) */
  w39 *= w10;
  /* #806: @39 = (-@39) */
  w39 = (- w39 );
  /* #807: @30 = 172.96 */
  w30 = 1.7296006950873124e+02;
  /* #808: @30 = (@4-@30) */
  w30  = (w4-w30);
  /* #809: @30 = (@30*@9) */
  w30 *= w9;
  /* #810: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #811: @30 = (@30*@5) */
  w30 *= w5;
  /* #812: @30 = (-@30) */
  w30 = (- w30 );
  /* #813: @7 = 14.9 */
  w7 = 1.4900000000000000e+01;
  /* #814: @7 = (@7/@1) */
  w7 /= w1;
  /* #815: @12 = (@7*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) (*rr++)  = (w7*(*cs++));
  /* #816: @6 = (@6/@1) */
  w6 /= w1;
  /* #817: @13 = (@6*@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #818: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #819: @6 = 2.6 */
  w6 = 2.6000000000000001e+00;
  /* #820: @6 = (@6/@1) */
  w6 /= w1;
  /* #821: @22 = (@6*@22) */
  for (i=0, rr=w22, cs=w22; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #822: @12 = (@12+@22) */
  for (i=0, rr=w12, cs=w22; i<3; ++i) (*rr++) += (*cs++);
  /* #823: @6 = @12[2] */
  for (rr=(&w6), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #824: @6 = (@6*@4) */
  w6 *= w4;
  /* #825: @6 = (@6*@9) */
  w6 *= w9;
  /* #826: @6 = (@6*@10) */
  w6 *= w10;
  /* #827: @1 = @12[1] */
  for (rr=(&w1), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #828: @1 = (@1*@4) */
  w1 *= w4;
  /* #829: @1 = (@1*@9) */
  w1 *= w9;
  /* #830: @1 = (@1*@5) */
  w1 *= w5;
  /* #831: @6 = (@6-@1) */
  w6 -= w1;
  /* #832: @1 = @12[2] */
  for (rr=(&w1), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #833: @1 = (@1*@4) */
  w1 *= w4;
  /* #834: @1 = (@1*@8) */
  w1 *= w8;
  /* #835: @7 = @12[0] */
  for (rr=(&w7), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #836: @7 = (@7*@4) */
  w7 *= w4;
  /* #837: @7 = (@7*@9) */
  w7 *= w9;
  /* #838: @7 = (@7*@5) */
  w7 *= w5;
  /* #839: @1 = (@1+@7) */
  w1 += w7;
  /* #840: @7 = @12[0] */
  for (rr=(&w7), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #841: @7 = (@7*@4) */
  w7 *= w4;
  /* #842: @7 = (@7*@9) */
  w7 *= w9;
  /* #843: @7 = (@7*@10) */
  w7 *= w10;
  /* #844: @7 = (-@7) */
  w7 = (- w7 );
  /* #845: @10 = @12[1] */
  for (rr=(&w10), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #846: @10 = (@10*@4) */
  w10 *= w4;
  /* #847: @10 = (@10*@8) */
  w10 *= w8;
  /* #848: @7 = (@7-@10) */
  w7 -= w10;
  /* #849: @35 = vertcat(@33, @39, @30, @6, @1, @7) */
  rr=w35;
  *rr++ = w33;
  *rr++ = w39;
  *rr++ = w30;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w7;
  /* #850: @34 = (@34-@35) */
  for (i=0, rr=w34, cs=w35; i<6; ++i) (*rr++) -= (*cs++);
  /* #851: @20 = mac(@21,@34,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w21+j, tt=w34+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #852: output[0][2] = @20 */
  if (res[0]) casadi_copy(w20, 6, res[0]+7);
  /* #853: @20 = input[1][0] */
  casadi_copy(arg[1], 6, w20);
  /* #854: @34 = @2[13:19] */
  for (rr=w34, ss=w2+13; ss!=w2+19; ss+=1) *rr++ = *ss;
  /* #855: @20 = (@20-@34) */
  for (i=0, rr=w20, cs=w34; i<6; ++i) (*rr++) -= (*cs++);
  /* #856: @33 = 0.02 */
  w33 = 2.0000000000000000e-02;
  /* #857: @20 = (@20/@33) */
  for (i=0, rr=w20; i<6; ++i) (*rr++) /= w33;
  /* #858: @33 = 10 */
  w33 = 10.;
  /* #859: @39 = @20[0] */
  for (rr=(&w39), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #860: @39 = fabs(@39) */
  w39 = casadi_fabs( w39 );
  /* #861: @33 = (@33<@39) */
  w33  = (w33<w39);
  /* #862: @39 = 10 */
  w39 = 10.;
  /* #863: @30 = @20[0] */
  for (rr=(&w30), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #864: @30 = sign(@30) */
  w30 = casadi_sign( w30 );
  /* #865: @39 = (@39*@30) */
  w39 *= w30;
  /* #866: @39 = (@33?@39:0) */
  w39  = (w33?w39:0);
  /* #867: @33 = (!@33) */
  w33 = (! w33 );
  /* #868: @30 = @20[0] */
  for (rr=(&w30), ss=w20+0; ss!=w20+1; ss+=1) *rr++ = *ss;
  /* #869: @33 = (@33?@30:0) */
  w33  = (w33?w30:0);
  /* #870: @39 = (@39+@33) */
  w39 += w33;
  /* #871: (@20[0] = @39) */
  for (rr=w20+0, ss=(&w39); rr!=w20+1; rr+=1) *rr = *ss++;
  /* #872: @39 = 15 */
  w39 = 15.;
  /* #873: @33 = @20[1] */
  for (rr=(&w33), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #874: @33 = fabs(@33) */
  w33 = casadi_fabs( w33 );
  /* #875: @39 = (@39<@33) */
  w39  = (w39<w33);
  /* #876: @33 = 15 */
  w33 = 15.;
  /* #877: @30 = @20[1] */
  for (rr=(&w30), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #878: @30 = sign(@30) */
  w30 = casadi_sign( w30 );
  /* #879: @33 = (@33*@30) */
  w33 *= w30;
  /* #880: @33 = (@39?@33:0) */
  w33  = (w39?w33:0);
  /* #881: @39 = (!@39) */
  w39 = (! w39 );
  /* #882: @30 = @20[1] */
  for (rr=(&w30), ss=w20+1; ss!=w20+2; ss+=1) *rr++ = *ss;
  /* #883: @39 = (@39?@30:0) */
  w39  = (w39?w30:0);
  /* #884: @33 = (@33+@39) */
  w33 += w39;
  /* #885: (@20[1] = @33) */
  for (rr=w20+1, ss=(&w33); rr!=w20+2; rr+=1) *rr = *ss++;
  /* #886: output[0][3] = @20 */
  if (res[0]) casadi_copy(w20, 6, res[0]+13);
  return 0;
}

/* SAM_equation_system_expl_ode_fun:(i0[19],i1[6],i2[0])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1;
  const casadi_real **arg1=arg+3;
  casadi_real *w0=w+290, *w1=w+309, *w2=w+315;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 19, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 6, w1);
  /* #2: @2 = x_dot(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: output[0][0] = @2 */
  casadi_copy(w2, 19, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real SAM_equation_system_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 334;
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 7*sizeof(casadi_int);
  if (sz_w) *sz_w = 334*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
