/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) SAM_equation_system_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_project CASADI_PREFIX(project)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {6, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[21] = {6, 6, 0, 1, 2, 3, 6, 9, 12, 0, 1, 2, 3, 4, 5, 3, 4, 5, 3, 4, 5};
static const casadi_int casadi_s3[6] = {0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[18] = {6, 6, 0, 1, 2, 3, 6, 8, 9, 0, 1, 2, 3, 4, 5, 4, 5, 5};
static const casadi_int casadi_s5[18] = {6, 6, 0, 1, 2, 3, 4, 6, 9, 0, 1, 2, 3, 3, 4, 3, 4, 5};
static const casadi_int casadi_s6[9] = {18, 19, 20, 24, 25, 26, 30, 31, 32};
static const casadi_int casadi_s7[9] = {21, 22, 23, 27, 28, 29, 33, 34, 35};
static const casadi_int casadi_s8[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s9[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s10[4] = {0, 1, 0, 0};
static const casadi_int casadi_s11[3] = {0, 0, 0};
static const casadi_int casadi_s12[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};

static const casadi_real casadi_c0[36] = {1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.};
static const casadi_real casadi_c1[3] = {5.3789000000000010e-02, 1.7031445000000001e+00, 1.7031445000000001e+00};
static const casadi_real casadi_c2[3] = {-7.5000000000000000e-01, 0., 5.9999999999999998e-02};
static const casadi_real casadi_c3[3] = {7.3999999999999999e-01, 0., 5.9999999999999998e-02};
static const casadi_real casadi_c4[3] = {4.0400000000000003e-01, 0., 1.2500000000000001e-02};
static const casadi_real casadi_c5[3] = {2.0800000000000003e-03, 1.1814616666666668e-02, 1.1814616666666668e-02};
static const casadi_real casadi_c6[3] = {7.1950000000000003e-01, 0., 1.3000000000000000e-01};
static const casadi_real casadi_c7[3] = {0., 0., 1.};
static const casadi_real casadi_c8[3] = {0., 1., 0.};
static const casadi_real casadi_c9[3] = {2.9999999999999999e-02, 0., 0.};
static const casadi_real casadi_c10[3] = {4.0000000000000001e-02, 0., 0.};

/* x_dot:(i0[13],i1[6])->(o0[13]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+6, w1, *w2=w+10, *w3=w+23, w4, w5, w6, w7, w8, w9, w10, *w11=w+34, *w12=w+37, *w13=w+40, *w14=w+43, *w15=w+52, *w16=w+61, *w17=w+65, *w18=w+77, *w19=w+89, *w20=w+93, *w21=w+99, *w22=w+135, *w23=w+141, *w24=w+144, *w25=w+147, *w26=w+156, *w27=w+165, *w28=w+174, *w29=w+177, *w30=w+186, w31, *w32=w+190, *w33=w+196, w34, *w35=w+199, *w36=w+205, *w37=w+241, *w38=w+277, w39;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = 1 */
  w1 = 1.;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 13, w2);
  /* #3: @3 = @2[3:7] */
  for (rr=w3, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #4: @4 = ||@3||_F */
  w4 = sqrt(casadi_dot(4, w3, w3));
  /* #5: @3 = (@3/@4) */
  for (i=0, rr=w3; i<4; ++i) (*rr++) /= w4;
  /* #6: @4 = @3[2] */
  for (rr=(&w4), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #7: @5 = sq(@4) */
  w5 = casadi_sq( w4 );
  /* #8: @6 = @3[3] */
  for (rr=(&w6), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #9: @7 = sq(@6) */
  w7 = casadi_sq( w6 );
  /* #10: @5 = (@5+@7) */
  w5 += w7;
  /* #11: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #12: @1 = (@1-@5) */
  w1 -= w5;
  /* #13: @5 = @3[1] */
  for (rr=(&w5), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #14: @7 = (@5*@4) */
  w7  = (w5*w4);
  /* #15: @8 = @3[0] */
  for (rr=(&w8), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #16: @9 = (@8*@6) */
  w9  = (w8*w6);
  /* #17: @7 = (@7-@9) */
  w7 -= w9;
  /* #18: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #19: @9 = (@5*@6) */
  w9  = (w5*w6);
  /* #20: @10 = (@8*@4) */
  w10  = (w8*w4);
  /* #21: @9 = (@9+@10) */
  w9 += w10;
  /* #22: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #23: @11 = horzcat(@1, @7, @9) */
  rr=w11;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w9;
  /* #24: @11 = @11' */
  /* #25: @1 = (@5*@4) */
  w1  = (w5*w4);
  /* #26: @7 = (@8*@6) */
  w7  = (w8*w6);
  /* #27: @1 = (@1+@7) */
  w1 += w7;
  /* #28: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #29: @7 = 1 */
  w7 = 1.;
  /* #30: @9 = sq(@5) */
  w9 = casadi_sq( w5 );
  /* #31: @10 = sq(@6) */
  w10 = casadi_sq( w6 );
  /* #32: @9 = (@9+@10) */
  w9 += w10;
  /* #33: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #34: @7 = (@7-@9) */
  w7 -= w9;
  /* #35: @9 = (@4*@6) */
  w9  = (w4*w6);
  /* #36: @10 = (@8*@5) */
  w10  = (w8*w5);
  /* #37: @9 = (@9-@10) */
  w9 -= w10;
  /* #38: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #39: @12 = horzcat(@1, @7, @9) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w7;
  *rr++ = w9;
  /* #40: @12 = @12' */
  /* #41: @1 = (@5*@6) */
  w1  = (w5*w6);
  /* #42: @7 = (@8*@4) */
  w7  = (w8*w4);
  /* #43: @1 = (@1-@7) */
  w1 -= w7;
  /* #44: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #45: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #46: @8 = (@8*@5) */
  w8 *= w5;
  /* #47: @6 = (@6+@8) */
  w6 += w8;
  /* #48: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #49: @8 = 1 */
  w8 = 1.;
  /* #50: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #51: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #52: @5 = (@5+@4) */
  w5 += w4;
  /* #53: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #54: @8 = (@8-@5) */
  w8 -= w5;
  /* #55: @13 = horzcat(@1, @6, @8) */
  rr=w13;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w8;
  /* #56: @13 = @13' */
  /* #57: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #58: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #59: @11 = @2[7:10] */
  for (rr=w11, ss=w2+7; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #60: @0 = mac(@15,@11,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #61: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #62: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #63: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #64: @6 = @3[1] */
  for (rr=(&w6), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #65: @8 = (-@6) */
  w8 = (- w6 );
  /* #66: @5 = @3[2] */
  for (rr=(&w5), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #67: @4 = (-@5) */
  w4 = (- w5 );
  /* #68: @7 = @3[3] */
  for (rr=(&w7), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #69: @9 = (-@7) */
  w9 = (- w7 );
  /* #70: @0 = horzcat(@8, @4, @9) */
  rr=w0;
  *rr++ = w8;
  *rr++ = w4;
  *rr++ = w9;
  /* #71: @0 = @0' */
  /* #72: @8 = @3[0] */
  for (rr=(&w8), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #73: @4 = (-@7) */
  w4 = (- w7 );
  /* #74: @11 = horzcat(@8, @4, @5) */
  rr=w11;
  *rr++ = w8;
  *rr++ = w4;
  *rr++ = w5;
  /* #75: @11 = @11' */
  /* #76: @4 = (-@6) */
  w4 = (- w6 );
  /* #77: @12 = horzcat(@7, @8, @4) */
  rr=w12;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w4;
  /* #78: @12 = @12' */
  /* #79: @5 = (-@5) */
  w5 = (- w5 );
  /* #80: @13 = horzcat(@5, @6, @8) */
  rr=w13;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w8;
  /* #81: @13 = @13' */
  /* #82: @17 = horzcat(@0, @11, @12, @13) */
  rr=w17;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #83: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #84: @18 = (@1*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w1*(*cs++));
  /* #85: @0 = @2[10:13] */
  for (rr=w0, ss=w2+10; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #86: @16 = mac(@18,@0,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w18+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*4]**tt++;
  /* #87: @1 = 50 */
  w1 = 50.;
  /* #88: @5 = 1 */
  w5 = 1.;
  /* #89: @6 = 0 */
  w6 = 0.;
  /* #90: @19 = @3' */
  casadi_copy(w3, 4, w19);
  /* #91: @6 = mac(@19,@3,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w19+j, tt=w3+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #92: @5 = (@5-@6) */
  w5 -= w6;
  /* #93: @1 = (@1*@5) */
  w1 *= w5;
  /* #94: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #95: @16 = (@16+@3) */
  for (i=0, rr=w16, cs=w3; i<4; ++i) (*rr++) += (*cs++);
  /* #96: output[0][1] = @16 */
  if (res[0]) casadi_copy(w16, 4, res[0]+3);
  /* #97: @20 = zeros(6x1) */
  casadi_clear(w20, 6);
  /* #98: @21 = 
  [[1, 0, 0, 0, 0, 0], 
   [0, 1, 0, 0, 0, 0], 
   [0, 0, 1, 0, 0, 0], 
   [0, 0, 0, 1, 0, 0], 
   [0, 0, 0, 0, 1, 0], 
   [0, 0, 0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 36, w21);
  /* #99: @1 = 2.6 */
  w1 = 2.6000000000000001e+00;
  /* #100: @5 = 14.9 */
  w5 = 1.4900000000000000e+01;
  /* #101: @6 = 5.82204 */
  w6 = 5.8220387755407756e+00;
  /* #102: @8 = 0.045 */
  w8 = 4.4999999999999998e-02;
  /* #103: @22 = input[1][0] */
  casadi_copy(arg[1], 6, w22);
  /* #104: @7 = @22[0] */
  for (rr=(&w7), ss=w22+0; ss!=w22+1; ss+=1) *rr++ = *ss;
  /* #105: @4 = 100 */
  w4 = 100.;
  /* #106: @7 = (@7/@4) */
  w7 /= w4;
  /* #107: @8 = (@8*@7) */
  w8 *= w7;
  /* #108: @6 = (@6*@8) */
  w6 *= w8;
  /* #109: @5 = (@5+@6) */
  w5 += w6;
  /* #110: @1 = (@1+@5) */
  w1 += w5;
  /* #111: @0 = vertcat(@1, @1, @1) */
  rr=w0;
  *rr++ = w1;
  *rr++ = w1;
  *rr++ = w1;
  /* #112: @0 = sparsity_cast(@0) */
  /* #113: @11 = 
  [[0.053789, 00, 00], 
   [00, 1.70314, 00], 
   [00, 00, 1.70314]] */
  casadi_copy(casadi_c1, 3, w11);
  /* #114: @15 = dense(@11) */
  casadi_densify(w11, casadi_s0, w15, 0);
  /* #115: @5 = 14.9 */
  w5 = 1.4900000000000000e+01;
  /* #116: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #117: @7 = 0 */
  w7 = 0.;
  /* #118: @11 = [-0.75, 0, 0.06] */
  casadi_copy(casadi_c2, 3, w11);
  /* #119: @12 = [0.74, 0, 0.06] */
  casadi_copy(casadi_c3, 3, w12);
  /* #120: @12 = (@11+@12) */
  for (i=0, rr=w12, cr=w11, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #121: @4 = @12[2] */
  for (rr=(&w4), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #122: @4 = (-@4) */
  w4 = (- w4 );
  /* #123: @9 = @12[1] */
  for (rr=(&w9), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #124: @13 = horzcat(@7, @4, @9) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #125: @13 = @13' */
  /* #126: @7 = @12[2] */
  for (rr=(&w7), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #127: @4 = 0 */
  w4 = 0.;
  /* #128: @9 = @12[0] */
  for (rr=(&w9), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #129: @9 = (-@9) */
  w9 = (- w9 );
  /* #130: @23 = horzcat(@7, @4, @9) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #131: @23 = @23' */
  /* #132: @7 = @12[1] */
  for (rr=(&w7), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #133: @7 = (-@7) */
  w7 = (- w7 );
  /* #134: @4 = @12[0] */
  for (rr=(&w4), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #135: @9 = 0 */
  w9 = 0.;
  /* #136: @24 = horzcat(@7, @4, @9) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #137: @24 = @24' */
  /* #138: @25 = horzcat(@13, @23, @24) */
  rr=w25;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #139: @26 = @25' */
  for (i=0, rr=w26, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #140: @7 = 0 */
  w7 = 0.;
  /* #141: @4 = @12[2] */
  for (rr=(&w4), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #142: @4 = (-@4) */
  w4 = (- w4 );
  /* #143: @9 = @12[1] */
  for (rr=(&w9), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #144: @13 = horzcat(@7, @4, @9) */
  rr=w13;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #145: @13 = @13' */
  /* #146: @7 = @12[2] */
  for (rr=(&w7), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #147: @4 = 0 */
  w4 = 0.;
  /* #148: @9 = @12[0] */
  for (rr=(&w9), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #149: @9 = (-@9) */
  w9 = (- w9 );
  /* #150: @23 = horzcat(@7, @4, @9) */
  rr=w23;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #151: @23 = @23' */
  /* #152: @7 = @12[1] */
  for (rr=(&w7), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #153: @7 = (-@7) */
  w7 = (- w7 );
  /* #154: @4 = @12[0] */
  for (rr=(&w4), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #155: @9 = 0 */
  w9 = 0.;
  /* #156: @24 = horzcat(@7, @4, @9) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w9;
  /* #157: @24 = @24' */
  /* #158: @25 = horzcat(@13, @23, @24) */
  rr=w25;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #159: @27 = @25' */
  for (i=0, rr=w27, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #160: @14 = mac(@26,@27,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #161: @14 = (@5*@14) */
  for (i=0, rr=w14, cs=w14; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #162: @15 = (@15-@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++) -= (*cs++);
  /* #163: @5 = 0.00180625 */
  w5 = 1.8062500000000003e-03;
  /* #164: @7 = 0.5 */
  w7 = 5.0000000000000000e-01;
  /* #165: @7 = (@7*@6) */
  w7 *= w6;
  /* #166: @5 = (@5*@7) */
  w5 *= w7;
  /* #167: @7 = 0.0833333 */
  w7 = 8.3333333333333329e-02;
  /* #168: @7 = (@7*@6) */
  w7 *= w6;
  /* #169: @4 = 0.00541875 */
  w4 = 5.4187500000000008e-03;
  /* #170: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #171: @4 = (@4+@8) */
  w4 += w8;
  /* #172: @7 = (@7*@4) */
  w7 *= w4;
  /* #173: @13 = vertcat(@5, @7, @7) */
  rr=w13;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w7;
  /* #174: @13 = sparsity_cast(@13) */
  /* #175: @14 = dense(@13) */
  casadi_densify(w13, casadi_s0, w14, 0);
  /* #176: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #177: @5 = 0 */
  w5 = 0.;
  /* #178: @13 = [0.404, 0, 0.0125] */
  casadi_copy(casadi_c4, 3, w13);
  /* #179: @13 = (@11+@13) */
  for (i=0, rr=w13, cr=w11, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #180: @7 = @13[2] */
  for (rr=(&w7), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #181: @7 = (-@7) */
  w7 = (- w7 );
  /* #182: @4 = @13[1] */
  for (rr=(&w4), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #183: @23 = horzcat(@5, @7, @4) */
  rr=w23;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #184: @23 = @23' */
  /* #185: @5 = @13[2] */
  for (rr=(&w5), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #186: @7 = 0 */
  w7 = 0.;
  /* #187: @4 = @13[0] */
  for (rr=(&w4), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #188: @4 = (-@4) */
  w4 = (- w4 );
  /* #189: @24 = horzcat(@5, @7, @4) */
  rr=w24;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #190: @24 = @24' */
  /* #191: @5 = @13[1] */
  for (rr=(&w5), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #192: @5 = (-@5) */
  w5 = (- w5 );
  /* #193: @7 = @13[0] */
  for (rr=(&w7), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #194: @4 = 0 */
  w4 = 0.;
  /* #195: @28 = horzcat(@5, @7, @4) */
  rr=w28;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #196: @28 = @28' */
  /* #197: @27 = horzcat(@23, @24, @28) */
  rr=w27;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #198: @25 = @27' */
  for (i=0, rr=w25, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #199: @5 = 0 */
  w5 = 0.;
  /* #200: @7 = @13[2] */
  for (rr=(&w7), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #201: @7 = (-@7) */
  w7 = (- w7 );
  /* #202: @4 = @13[1] */
  for (rr=(&w4), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #203: @23 = horzcat(@5, @7, @4) */
  rr=w23;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #204: @23 = @23' */
  /* #205: @5 = @13[2] */
  for (rr=(&w5), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #206: @7 = 0 */
  w7 = 0.;
  /* #207: @4 = @13[0] */
  for (rr=(&w4), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #208: @4 = (-@4) */
  w4 = (- w4 );
  /* #209: @24 = horzcat(@5, @7, @4) */
  rr=w24;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #210: @24 = @24' */
  /* #211: @5 = @13[1] */
  for (rr=(&w5), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #212: @5 = (-@5) */
  w5 = (- w5 );
  /* #213: @7 = @13[0] */
  for (rr=(&w7), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #214: @4 = 0 */
  w4 = 0.;
  /* #215: @28 = horzcat(@5, @7, @4) */
  rr=w28;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #216: @28 = @28' */
  /* #217: @27 = horzcat(@23, @24, @28) */
  rr=w27;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #218: @29 = @27' */
  for (i=0, rr=w29, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #219: @26 = mac(@25,@29,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w25+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #220: @26 = (@6*@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) (*rr++)  = (w6*(*cs++));
  /* #221: @14 = (@14-@26) */
  for (i=0, rr=w14, cs=w26; i<9; ++i) (*rr++) -= (*cs++);
  /* #222: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++) += (*cs++);
  /* #223: @23 = 
  [[0.00208, 00, 00], 
   [00, 0.0118146, 00], 
   [00, 00, 0.0118146]] */
  casadi_copy(casadi_c5, 3, w23);
  /* #224: @14 = dense(@23) */
  casadi_densify(w23, casadi_s0, w14, 0);
  /* #225: @5 = 2.6 */
  w5 = 2.6000000000000001e+00;
  /* #226: @26 = zeros(3x3) */
  casadi_clear(w26, 9);
  /* #227: @7 = 0 */
  w7 = 0.;
  /* #228: @23 = [0.7195, 0, 0.13] */
  casadi_copy(casadi_c6, 3, w23);
  /* #229: @23 = (@11+@23) */
  for (i=0, rr=w23, cr=w11, cs=w23; i<3; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #230: @4 = 0.223 */
  w4 = 2.2300000000000000e-01;
  /* #231: @8 = @22[1] */
  for (rr=(&w8), ss=w22+1; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #232: @9 = 100 */
  w9 = 100.;
  /* #233: @8 = (@8/@9) */
  w8 /= w9;
  /* #234: @4 = (@4*@8) */
  w4 *= w8;
  /* #235: @8 = 0 */
  w8 = 0.;
  /* #236: @9 = 0 */
  w9 = 0.;
  /* #237: @24 = vertcat(@4, @8, @9) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w8;
  *rr++ = w9;
  /* #238: @23 = (@23+@24) */
  for (i=0, rr=w23, cs=w24; i<3; ++i) (*rr++) += (*cs++);
  /* #239: @4 = @23[2] */
  for (rr=(&w4), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #240: @4 = (-@4) */
  w4 = (- w4 );
  /* #241: @8 = @23[1] */
  for (rr=(&w8), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #242: @24 = horzcat(@7, @4, @8) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #243: @24 = @24' */
  /* #244: @7 = @23[2] */
  for (rr=(&w7), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #245: @4 = 0 */
  w4 = 0.;
  /* #246: @8 = @23[0] */
  for (rr=(&w8), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #247: @8 = (-@8) */
  w8 = (- w8 );
  /* #248: @28 = horzcat(@7, @4, @8) */
  rr=w28;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #249: @28 = @28' */
  /* #250: @7 = @23[1] */
  for (rr=(&w7), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #251: @7 = (-@7) */
  w7 = (- w7 );
  /* #252: @4 = @23[0] */
  for (rr=(&w4), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #253: @8 = 0 */
  w8 = 0.;
  /* #254: @30 = horzcat(@7, @4, @8) */
  rr=w30;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #255: @30 = @30' */
  /* #256: @25 = horzcat(@24, @28, @30) */
  rr=w25;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #257: @29 = @25' */
  for (i=0, rr=w29, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #258: @7 = 0 */
  w7 = 0.;
  /* #259: @4 = @23[2] */
  for (rr=(&w4), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #260: @4 = (-@4) */
  w4 = (- w4 );
  /* #261: @8 = @23[1] */
  for (rr=(&w8), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #262: @24 = horzcat(@7, @4, @8) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #263: @24 = @24' */
  /* #264: @7 = @23[2] */
  for (rr=(&w7), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #265: @4 = 0 */
  w4 = 0.;
  /* #266: @8 = @23[0] */
  for (rr=(&w8), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #267: @8 = (-@8) */
  w8 = (- w8 );
  /* #268: @28 = horzcat(@7, @4, @8) */
  rr=w28;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #269: @28 = @28' */
  /* #270: @7 = @23[1] */
  for (rr=(&w7), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #271: @7 = (-@7) */
  w7 = (- w7 );
  /* #272: @4 = @23[0] */
  for (rr=(&w4), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #273: @8 = 0 */
  w8 = 0.;
  /* #274: @30 = horzcat(@7, @4, @8) */
  rr=w30;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #275: @30 = @30' */
  /* #276: @25 = horzcat(@24, @28, @30) */
  rr=w25;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #277: @27 = @25' */
  for (i=0, rr=w27, cs=w25; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #278: @26 = mac(@29,@27,@26) */
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #279: @26 = (@5*@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #280: @14 = (@14-@26) */
  for (i=0, rr=w14, cs=w26; i<9; ++i) (*rr++) -= (*cs++);
  /* #281: @15 = (@15+@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++) += (*cs++);
  /* #282: @18 = diagcat(@0, @15) */
  rr=w18;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<9; ++i) *rr++ = *cs++;
  /* #283: @5 = 0.0298523 */
  w5 = 2.9852318056049005e-02;
  /* #284: @5 = (@5*@1) */
  w5 *= w1;
  /* #285: @7 = 0.943659 */
  w7 = 9.4365917249249198e-01;
  /* #286: @7 = (@7*@1) */
  w7 *= w1;
  /* #287: @4 = 0.943659 */
  w4 = 9.4365917249249198e-01;
  /* #288: @4 = (@4*@1) */
  w4 *= w1;
  /* #289: @8 = 0.3 */
  w8 = 2.9999999999999999e-01;
  /* #290: @9 = @15[0] */
  for (rr=(&w9), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #291: @8 = (@8*@9) */
  w8 *= w9;
  /* #292: @9 = 0.836375 */
  w9 = 8.3637530823391681e-01;
  /* #293: @10 = @15[4] */
  for (rr=(&w10), ss=w15+4; ss!=w15+5; ss+=1) *rr++ = *ss;
  /* #294: @9 = (@9*@10) */
  w9 *= w10;
  /* #295: @10 = 0.836375 */
  w10 = 8.3637530823391681e-01;
  /* #296: @31 = @15[4] */
  for (rr=(&w31), ss=w15+4; ss!=w15+5; ss+=1) *rr++ = *ss;
  /* #297: @10 = (@10*@31) */
  w10 *= w31;
  /* #298: @32 = vertcat(@5, @7, @4, @8, @9, @10) */
  rr=w32;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  /* #299: @32 = sparsity_cast(@32) */
  /* #300: @17 = project(@32) */
  casadi_project(w32, casadi_s1, w17, casadi_s2, w);
  /* #301: @17 = (@18+@17) */
  for (i=0, rr=w17, cr=w18, cs=w17; i<12; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #302: @21 = (@17\@21) */
  rr = w21;
  ss = w17;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[9], r[9], beta[6], w[12];
    casadi_qr(casadi_s2, ss, w, casadi_s4, v, casadi_s5, r, beta, casadi_s3, casadi_s3);
    casadi_qr_solve(rr, 6, 0, casadi_s4, v, casadi_s5, r, beta, casadi_s3, casadi_s3, w);
  }
  /* #303: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #304: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #305: @5 = @22[3] */
  for (rr=(&w5), ss=w22+3; ss!=w22+4; ss+=1) *rr++ = *ss;
  /* #306: @7 = cos(@5) */
  w7 = cos( w5 );
  /* #307: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #308: @4 = 0 */
  w4 = 0.;
  /* #309: @24 = horzcat(@7, @5, @4) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w5;
  *rr++ = w4;
  /* #310: @24 = @24' */
  /* #311: @5 = (-@5) */
  w5 = (- w5 );
  /* #312: @4 = 0 */
  w4 = 0.;
  /* #313: @28 = horzcat(@5, @7, @4) */
  rr=w28;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w4;
  /* #314: @28 = @28' */
  /* #315: @30 = [[0, 0, 1]] */
  casadi_copy(casadi_c7, 3, w30);
  /* #316: @30 = @30' */
  /* #317: @14 = horzcat(@24, @28, @30) */
  rr=w14;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #318: @26 = @14' */
  for (i=0, rr=w26, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #319: @5 = @22[2] */
  for (rr=(&w5), ss=w22+2; ss!=w22+3; ss+=1) *rr++ = *ss;
  /* #320: @7 = cos(@5) */
  w7 = cos( w5 );
  /* #321: @4 = 0 */
  w4 = 0.;
  /* #322: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #323: @8 = (-@5) */
  w8 = (- w5 );
  /* #324: @24 = horzcat(@7, @4, @8) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w4;
  *rr++ = w8;
  /* #325: @24 = @24' */
  /* #326: @28 = [[0, 1, 0]] */
  casadi_copy(casadi_c8, 3, w28);
  /* #327: @28 = @28' */
  /* #328: @4 = 0 */
  w4 = 0.;
  /* #329: @30 = horzcat(@5, @4, @7) */
  rr=w30;
  *rr++ = w5;
  *rr++ = w4;
  *rr++ = w7;
  /* #330: @30 = @30' */
  /* #331: @14 = horzcat(@24, @28, @30) */
  rr=w14;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  /* #332: @29 = @14' */
  for (i=0, rr=w29, cs=w14; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #333: @15 = mac(@26,@29,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #334: @5 = 0 */
  w5 = 0.;
  /* #335: @33 = @22[4:6] */
  for (rr=w33, ss=w22+4; ss!=w22+6; ss+=1) *rr++ = *ss;
  /* #336: @4 = 60 */
  w4 = 60.;
  /* #337: @33 = (@33/@4) */
  for (i=0, rr=w33; i<2; ++i) (*rr++) /= w4;
  /* #338: @4 = @33[0] */
  for (rr=(&w4), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #339: @4 = sign(@4) */
  w4 = casadi_sign( w4 );
  /* #340: @5 = (@5<@4) */
  w5  = (w5<w4);
  /* #341: @4 = 0.394148 */
  w4 = 3.9414816000000014e-01;
  /* #342: @7 = 0.4566 */
  w7 = 4.5660000000000001e-01;
  /* #343: @8 = @33[0] */
  for (rr=(&w8), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #344: @8 = fabs(@8) */
  w8 = casadi_fabs( w8 );
  /* #345: @7 = (@7*@8) */
  w7 *= w8;
  /* #346: @8 = @33[0] */
  for (rr=(&w8), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #347: @7 = (@7*@8) */
  w7 *= w8;
  /* #348: @8 = -0.41737 */
  w8 = -4.1737032569360683e-01;
  /* #349: @9 = 0.944 */
  w9 = 9.4399999999999995e-01;
  /* #350: @10 = @2[7] */
  for (rr=(&w10), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #351: @10 = sq(@10) */
  w10 = casadi_sq( w10 );
  /* #352: @31 = @2[8] */
  for (rr=(&w31), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #353: @31 = sq(@31) */
  w31 = casadi_sq( w31 );
  /* #354: @10 = (@10+@31) */
  w10 += w31;
  /* #355: @31 = @2[9] */
  for (rr=(&w31), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #356: @31 = sq(@31) */
  w31 = casadi_sq( w31 );
  /* #357: @10 = (@10+@31) */
  w10 += w31;
  /* #358: @10 = sqrt(@10) */
  w10 = sqrt( w10 );
  /* #359: @9 = (@9*@10) */
  w9 *= w10;
  /* #360: @10 = 0.14 */
  w10 = 1.4000000000000001e-01;
  /* #361: @10 = (@9/@10) */
  w10  = (w9/w10);
  /* #362: @8 = (@8*@10) */
  w8 *= w10;
  /* #363: @10 = @33[0] */
  for (rr=(&w10), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #364: @10 = fabs(@10) */
  w10 = casadi_fabs( w10 );
  /* #365: @8 = (@8*@10) */
  w8 *= w10;
  /* #366: @7 = (@7+@8) */
  w7 += w8;
  /* #367: @4 = (@4*@7) */
  w4 *= w7;
  /* #368: @4 = (@5?@4:0) */
  w4  = (w5?w4:0);
  /* #369: @5 = (!@5) */
  w5 = (! w5 );
  /* #370: @7 = 0.394148 */
  w7 = 3.9414816000000014e-01;
  /* #371: @8 = 0.4566 */
  w8 = 4.5660000000000001e-01;
  /* #372: @10 = @33[0] */
  for (rr=(&w10), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #373: @10 = fabs(@10) */
  w10 = casadi_fabs( w10 );
  /* #374: @8 = (@8*@10) */
  w8 *= w10;
  /* #375: @10 = @33[0] */
  for (rr=(&w10), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #376: @8 = (@8*@10) */
  w8 *= w10;
  /* #377: @7 = (@7*@8) */
  w7 *= w8;
  /* #378: @8 = 10 */
  w8 = 10.;
  /* #379: @7 = (@7/@8) */
  w7 /= w8;
  /* #380: @5 = (@5?@7:0) */
  w5  = (w5?w7:0);
  /* #381: @4 = (@4+@5) */
  w4 += w5;
  /* #382: @5 = 0 */
  w5 = 0.;
  /* #383: @7 = 0 */
  w7 = 0.;
  /* #384: @24 = vertcat(@4, @5, @7) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w7;
  /* #385: @0 = mac(@15,@24,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #386: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #387: @28 = [0.03, 0, 0] */
  casadi_copy(casadi_c9, 3, w28);
  /* #388: @24 = mac(@15,@28,@24) */
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #389: @24 = (@24-@11) */
  for (i=0, rr=w24, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #390: @4 = @24[1] */
  for (rr=(&w4), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #391: @5 = @0[2] */
  for (rr=(&w5), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #392: @7 = (@4*@5) */
  w7  = (w4*w5);
  /* #393: @8 = @24[2] */
  for (rr=(&w8), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #394: @10 = @0[1] */
  for (rr=(&w10), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #395: @31 = (@8*@10) */
  w31  = (w8*w10);
  /* #396: @7 = (@7-@31) */
  w7 -= w31;
  /* #397: @31 = @0[0] */
  for (rr=(&w31), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #398: @8 = (@8*@31) */
  w8 *= w31;
  /* #399: @34 = @24[0] */
  for (rr=(&w34), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #400: @5 = (@34*@5) */
  w5  = (w34*w5);
  /* #401: @8 = (@8-@5) */
  w8 -= w5;
  /* #402: @34 = (@34*@10) */
  w34 *= w10;
  /* #403: @4 = (@4*@31) */
  w4 *= w31;
  /* #404: @34 = (@34-@4) */
  w34 -= w4;
  /* #405: @24 = vertcat(@7, @8, @34) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w34;
  /* #406: @7 = 0 */
  w7 = 0.;
  /* #407: @8 = @33[0] */
  for (rr=(&w8), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #408: @8 = sign(@8) */
  w8 = casadi_sign( w8 );
  /* #409: @7 = (@7<@8) */
  w7  = (w7<w8);
  /* #410: @8 = 0.0551807 */
  w8 = 5.5180742400000024e-02;
  /* #411: @34 = 0.07 */
  w34 = 7.0000000000000007e-02;
  /* #412: @4 = @33[0] */
  for (rr=(&w4), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #413: @4 = fabs(@4) */
  w4 = casadi_fabs( w4 );
  /* #414: @34 = (@34*@4) */
  w34 *= w4;
  /* #415: @4 = @33[0] */
  for (rr=(&w4), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #416: @34 = (@34*@4) */
  w34 *= w4;
  /* #417: @4 = -0.0585042 */
  w4 = -5.8504221954161655e-02;
  /* #418: @31 = 0.14 */
  w31 = 1.4000000000000001e-01;
  /* #419: @31 = (@9/@31) */
  w31  = (w9/w31);
  /* #420: @4 = (@4*@31) */
  w4 *= w31;
  /* #421: @31 = @33[0] */
  for (rr=(&w31), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #422: @31 = fabs(@31) */
  w31 = casadi_fabs( w31 );
  /* #423: @4 = (@4*@31) */
  w4 *= w31;
  /* #424: @34 = (@34+@4) */
  w34 += w4;
  /* #425: @8 = (@8*@34) */
  w8 *= w34;
  /* #426: @8 = (@7?@8:0) */
  w8  = (w7?w8:0);
  /* #427: @7 = (!@7) */
  w7 = (! w7 );
  /* #428: @34 = 0.00386265 */
  w34 = 3.8626519680000021e-03;
  /* #429: @4 = @33[0] */
  for (rr=(&w4), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #430: @4 = fabs(@4) */
  w4 = casadi_fabs( w4 );
  /* #431: @34 = (@34*@4) */
  w34 *= w4;
  /* #432: @4 = @33[0] */
  for (rr=(&w4), ss=w33+0; ss!=w33+1; ss+=1) *rr++ = *ss;
  /* #433: @34 = (@34*@4) */
  w34 *= w4;
  /* #434: @4 = 10 */
  w4 = 10.;
  /* #435: @34 = (@34/@4) */
  w34 /= w4;
  /* #436: @7 = (@7?@34:0) */
  w7  = (w7?w34:0);
  /* #437: @8 = (@8+@7) */
  w8 += w7;
  /* #438: @7 = 0 */
  w7 = 0.;
  /* #439: @34 = 0 */
  w34 = 0.;
  /* #440: @28 = vertcat(@8, @7, @34) */
  rr=w28;
  *rr++ = w8;
  *rr++ = w7;
  *rr++ = w34;
  /* #441: @24 = (@24+@28) */
  for (i=0, rr=w24, cs=w28; i<3; ++i) (*rr++) += (*cs++);
  /* #442: @22 = vertcat(@0, @24) */
  rr=w22;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #443: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #444: @8 = 0 */
  w8 = 0.;
  /* #445: @7 = @33[1] */
  for (rr=(&w7), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #446: @7 = sign(@7) */
  w7 = casadi_sign( w7 );
  /* #447: @8 = (@8<@7) */
  w8  = (w8<w7);
  /* #448: @7 = 0.394148 */
  w7 = 3.9414816000000014e-01;
  /* #449: @34 = 0.4566 */
  w34 = 4.5660000000000001e-01;
  /* #450: @4 = @33[1] */
  for (rr=(&w4), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #451: @4 = fabs(@4) */
  w4 = casadi_fabs( w4 );
  /* #452: @34 = (@34*@4) */
  w34 *= w4;
  /* #453: @4 = @33[1] */
  for (rr=(&w4), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #454: @34 = (@34*@4) */
  w34 *= w4;
  /* #455: @4 = -0.41737 */
  w4 = -4.1737032569360683e-01;
  /* #456: @31 = 0.14 */
  w31 = 1.4000000000000001e-01;
  /* #457: @31 = (@9/@31) */
  w31  = (w9/w31);
  /* #458: @4 = (@4*@31) */
  w4 *= w31;
  /* #459: @31 = @33[1] */
  for (rr=(&w31), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #460: @31 = fabs(@31) */
  w31 = casadi_fabs( w31 );
  /* #461: @4 = (@4*@31) */
  w4 *= w31;
  /* #462: @34 = (@34+@4) */
  w34 += w4;
  /* #463: @7 = (@7*@34) */
  w7 *= w34;
  /* #464: @7 = (@8?@7:0) */
  w7  = (w8?w7:0);
  /* #465: @8 = (!@8) */
  w8 = (! w8 );
  /* #466: @34 = 0.394148 */
  w34 = 3.9414816000000014e-01;
  /* #467: @4 = 0.4566 */
  w4 = 4.5660000000000001e-01;
  /* #468: @31 = @33[1] */
  for (rr=(&w31), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #469: @31 = fabs(@31) */
  w31 = casadi_fabs( w31 );
  /* #470: @4 = (@4*@31) */
  w4 *= w31;
  /* #471: @31 = @33[1] */
  for (rr=(&w31), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #472: @4 = (@4*@31) */
  w4 *= w31;
  /* #473: @34 = (@34*@4) */
  w34 *= w4;
  /* #474: @4 = 10 */
  w4 = 10.;
  /* #475: @34 = (@34/@4) */
  w34 /= w4;
  /* #476: @8 = (@8?@34:0) */
  w8  = (w8?w34:0);
  /* #477: @7 = (@7+@8) */
  w7 += w8;
  /* #478: @8 = 0 */
  w8 = 0.;
  /* #479: @34 = 0 */
  w34 = 0.;
  /* #480: @24 = vertcat(@7, @8, @34) */
  rr=w24;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w34;
  /* #481: @0 = mac(@15,@24,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #482: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #483: @28 = [0.04, 0, 0] */
  casadi_copy(casadi_c10, 3, w28);
  /* #484: @24 = mac(@15,@28,@24) */
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w28+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #485: @24 = (@24-@11) */
  for (i=0, rr=w24, cs=w11; i<3; ++i) (*rr++) -= (*cs++);
  /* #486: @7 = @24[1] */
  for (rr=(&w7), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #487: @8 = @0[2] */
  for (rr=(&w8), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #488: @34 = (@7*@8) */
  w34  = (w7*w8);
  /* #489: @4 = @24[2] */
  for (rr=(&w4), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #490: @31 = @0[1] */
  for (rr=(&w31), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #491: @10 = (@4*@31) */
  w10  = (w4*w31);
  /* #492: @34 = (@34-@10) */
  w34 -= w10;
  /* #493: @10 = @0[0] */
  for (rr=(&w10), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #494: @4 = (@4*@10) */
  w4 *= w10;
  /* #495: @5 = @24[0] */
  for (rr=(&w5), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #496: @8 = (@5*@8) */
  w8  = (w5*w8);
  /* #497: @4 = (@4-@8) */
  w4 -= w8;
  /* #498: @5 = (@5*@31) */
  w5 *= w31;
  /* #499: @7 = (@7*@10) */
  w7 *= w10;
  /* #500: @5 = (@5-@7) */
  w5 -= w7;
  /* #501: @24 = vertcat(@34, @4, @5) */
  rr=w24;
  *rr++ = w34;
  *rr++ = w4;
  *rr++ = w5;
  /* #502: @34 = 0 */
  w34 = 0.;
  /* #503: @4 = @33[1] */
  for (rr=(&w4), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #504: @4 = sign(@4) */
  w4 = casadi_sign( w4 );
  /* #505: @34 = (@34<@4) */
  w34  = (w34<w4);
  /* #506: @4 = 0.0551807 */
  w4 = 5.5180742400000024e-02;
  /* #507: @5 = 0.07 */
  w5 = 7.0000000000000007e-02;
  /* #508: @7 = @33[1] */
  for (rr=(&w7), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #509: @7 = fabs(@7) */
  w7 = casadi_fabs( w7 );
  /* #510: @5 = (@5*@7) */
  w5 *= w7;
  /* #511: @7 = @33[1] */
  for (rr=(&w7), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #512: @5 = (@5*@7) */
  w5 *= w7;
  /* #513: @7 = -0.0585042 */
  w7 = -5.8504221954161655e-02;
  /* #514: @10 = 0.14 */
  w10 = 1.4000000000000001e-01;
  /* #515: @9 = (@9/@10) */
  w9 /= w10;
  /* #516: @7 = (@7*@9) */
  w7 *= w9;
  /* #517: @9 = @33[1] */
  for (rr=(&w9), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #518: @9 = fabs(@9) */
  w9 = casadi_fabs( w9 );
  /* #519: @7 = (@7*@9) */
  w7 *= w9;
  /* #520: @5 = (@5+@7) */
  w5 += w7;
  /* #521: @4 = (@4*@5) */
  w4 *= w5;
  /* #522: @4 = (@34?@4:0) */
  w4  = (w34?w4:0);
  /* #523: @34 = (!@34) */
  w34 = (! w34 );
  /* #524: @5 = 0.00386265 */
  w5 = 3.8626519680000021e-03;
  /* #525: @7 = @33[1] */
  for (rr=(&w7), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #526: @7 = fabs(@7) */
  w7 = casadi_fabs( w7 );
  /* #527: @5 = (@5*@7) */
  w5 *= w7;
  /* #528: @7 = @33[1] */
  for (rr=(&w7), ss=w33+1; ss!=w33+2; ss+=1) *rr++ = *ss;
  /* #529: @5 = (@5*@7) */
  w5 *= w7;
  /* #530: @7 = 10 */
  w7 = 10.;
  /* #531: @5 = (@5/@7) */
  w5 /= w7;
  /* #532: @34 = (@34?@5:0) */
  w34  = (w34?w5:0);
  /* #533: @4 = (@4+@34) */
  w4 += w34;
  /* #534: @4 = (-@4) */
  w4 = (- w4 );
  /* #535: @34 = 0 */
  w34 = 0.;
  /* #536: @5 = 0 */
  w5 = 0.;
  /* #537: @11 = vertcat(@4, @34, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #538: @24 = (@24+@11) */
  for (i=0, rr=w24, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #539: @35 = vertcat(@0, @24) */
  rr=w35;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #540: @22 = (@22+@35) */
  for (i=0, rr=w22, cs=w35; i<6; ++i) (*rr++) += (*cs++);
  /* #541: @35 = zeros(6x1) */
  casadi_clear(w35, 6);
  /* #542: @36 = zeros(6x6) */
  casadi_clear(w36, 36);
  /* #543: @4 = 0 */
  w4 = 0.;
  /* #544: @34 = 0.5 */
  w34 = 5.0000000000000000e-01;
  /* #545: @17 = @18' */
  casadi_trans(w18,casadi_s2, w17, casadi_s2, iw);
  /* #546: @18 = (@18+@17) */
  for (i=0, rr=w18, cs=w17; i<12; ++i) (*rr++) += (*cs++);
  /* #547: @18 = (@34*@18) */
  for (i=0, rr=w18, cs=w18; i<12; ++i) (*rr++)  = (w34*(*cs++));
  /* #548: @0 = @18[:3] */
  for (rr=w0, ss=w18+0; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #549: @0 = nonzeros(@0) */
  /* #550: @24 = @2[7:10] */
  for (rr=w24, ss=w2+7; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #551: @0 = (@0*@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) *= (*cs++);
  /* #552: @34 = @0[2] */
  for (rr=(&w34), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #553: @34 = (-@34) */
  w34 = (- w34 );
  /* #554: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #555: @24 = horzcat(@4, @34, @5) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #556: @24 = @24' */
  /* #557: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #558: @34 = 0 */
  w34 = 0.;
  /* #559: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #560: @5 = (-@5) */
  w5 = (- w5 );
  /* #561: @11 = horzcat(@4, @34, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #562: @11 = @11' */
  /* #563: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #564: @4 = (-@4) */
  w4 = (- w4 );
  /* #565: @34 = @0[0] */
  for (rr=(&w34), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #566: @5 = 0 */
  w5 = 0.;
  /* #567: @28 = horzcat(@4, @34, @5) */
  rr=w28;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #568: @28 = @28' */
  /* #569: @15 = horzcat(@24, @11, @28) */
  rr=w15;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #570: @26 = @15' */
  for (i=0, rr=w26, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #571: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #572: (@36[18, 19, 20, 24, 25, 26, 30, 31, 32] = @26) */
  for (cii=casadi_s6, rr=w36, ss=w26; cii!=casadi_s6+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #573: @4 = 0 */
  w4 = 0.;
  /* #574: @34 = @0[2] */
  for (rr=(&w34), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #575: @34 = (-@34) */
  w34 = (- w34 );
  /* #576: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #577: @24 = horzcat(@4, @34, @5) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #578: @24 = @24' */
  /* #579: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #580: @34 = 0 */
  w34 = 0.;
  /* #581: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #582: @5 = (-@5) */
  w5 = (- w5 );
  /* #583: @11 = horzcat(@4, @34, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #584: @11 = @11' */
  /* #585: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #586: @4 = (-@4) */
  w4 = (- w4 );
  /* #587: @34 = @0[0] */
  for (rr=(&w34), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #588: @5 = 0 */
  w5 = 0.;
  /* #589: @0 = horzcat(@4, @34, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #590: @0 = @0' */
  /* #591: @26 = horzcat(@24, @11, @0) */
  rr=w26;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  /* #592: @15 = @26' */
  for (i=0, rr=w15, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #593: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<9; ++i) *rr++ = (- *cs++ );
  /* #594: (@36[:18:6;3:6] = @15) */
  for (rr=w36+0, ss=w15; rr!=w36+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #595: @4 = 0 */
  w4 = 0.;
  /* #596: @24 = zeros(3x1) */
  casadi_clear(w24, 3);
  /* #597: @15 = @18[3:12] */
  for (rr=w15, ss=w18+3; ss!=w18+12; ss+=1) *rr++ = *ss;
  /* #598: @11 = @2[10:13] */
  for (rr=w11, ss=w2+10; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #599: @24 = mac(@15,@11,@24) */
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #600: @34 = @24[2] */
  for (rr=(&w34), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #601: @34 = (-@34) */
  w34 = (- w34 );
  /* #602: @5 = @24[1] */
  for (rr=(&w5), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #603: @11 = horzcat(@4, @34, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #604: @11 = @11' */
  /* #605: @4 = @24[2] */
  for (rr=(&w4), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #606: @34 = 0 */
  w34 = 0.;
  /* #607: @5 = @24[0] */
  for (rr=(&w5), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #608: @5 = (-@5) */
  w5 = (- w5 );
  /* #609: @0 = horzcat(@4, @34, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #610: @0 = @0' */
  /* #611: @4 = @24[1] */
  for (rr=(&w4), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #612: @4 = (-@4) */
  w4 = (- w4 );
  /* #613: @34 = @24[0] */
  for (rr=(&w34), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #614: @5 = 0 */
  w5 = 0.;
  /* #615: @24 = horzcat(@4, @34, @5) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #616: @24 = @24' */
  /* #617: @15 = horzcat(@11, @0, @24) */
  rr=w15;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #618: @26 = @15' */
  for (i=0, rr=w26, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #619: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #620: (@36[21, 22, 23, 27, 28, 29, 33, 34, 35] = @26) */
  for (cii=casadi_s7, rr=w36, ss=w26; cii!=casadi_s7+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #621: @37 = zeros(6x6) */
  casadi_clear(w37, 36);
  /* #622: @4 = 0 */
  w4 = 0.;
  /* #623: @34 = 0.5 */
  w34 = 5.0000000000000000e-01;
  /* #624: @38 = @32' */
  casadi_trans(w32,casadi_s1, w38, casadi_s1, iw);
  /* #625: @32 = (@32+@38) */
  for (i=0, rr=w32, cs=w38; i<6; ++i) (*rr++) += (*cs++);
  /* #626: @32 = (@34*@32) */
  for (i=0, rr=w32, cs=w32; i<6; ++i) (*rr++)  = (w34*(*cs++));
  /* #627: @11 = @32[:3] */
  for (rr=w11, ss=w32+0; ss!=w32+3; ss+=1) *rr++ = *ss;
  /* #628: @11 = nonzeros(@11) */
  /* #629: @0 = @2[7:10] */
  for (rr=w0, ss=w2+7; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #630: @11 = (@11*@0) */
  for (i=0, rr=w11, cs=w0; i<3; ++i) (*rr++) *= (*cs++);
  /* #631: @34 = @11[2] */
  for (rr=(&w34), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #632: @34 = (-@34) */
  w34 = (- w34 );
  /* #633: @5 = @11[1] */
  for (rr=(&w5), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #634: @0 = horzcat(@4, @34, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #635: @0 = @0' */
  /* #636: @4 = @11[2] */
  for (rr=(&w4), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #637: @34 = 0 */
  w34 = 0.;
  /* #638: @5 = @11[0] */
  for (rr=(&w5), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #639: @5 = (-@5) */
  w5 = (- w5 );
  /* #640: @24 = horzcat(@4, @34, @5) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #641: @24 = @24' */
  /* #642: @4 = @11[1] */
  for (rr=(&w4), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #643: @4 = (-@4) */
  w4 = (- w4 );
  /* #644: @34 = @11[0] */
  for (rr=(&w34), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #645: @5 = 0 */
  w5 = 0.;
  /* #646: @28 = horzcat(@4, @34, @5) */
  rr=w28;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #647: @28 = @28' */
  /* #648: @26 = horzcat(@0, @24, @28) */
  rr=w26;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #649: @15 = @26' */
  for (i=0, rr=w15, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #650: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<9; ++i) *rr++ = (- *cs++ );
  /* #651: (@37[18, 19, 20, 24, 25, 26, 30, 31, 32] = @15) */
  for (cii=casadi_s6, rr=w37, ss=w15; cii!=casadi_s6+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #652: @4 = 0 */
  w4 = 0.;
  /* #653: @34 = @11[2] */
  for (rr=(&w34), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #654: @34 = (-@34) */
  w34 = (- w34 );
  /* #655: @5 = @11[1] */
  for (rr=(&w5), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #656: @0 = horzcat(@4, @34, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #657: @0 = @0' */
  /* #658: @4 = @11[2] */
  for (rr=(&w4), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #659: @34 = 0 */
  w34 = 0.;
  /* #660: @5 = @11[0] */
  for (rr=(&w5), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #661: @5 = (-@5) */
  w5 = (- w5 );
  /* #662: @24 = horzcat(@4, @34, @5) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #663: @24 = @24' */
  /* #664: @4 = @11[1] */
  for (rr=(&w4), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #665: @4 = (-@4) */
  w4 = (- w4 );
  /* #666: @34 = @11[0] */
  for (rr=(&w34), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #667: @5 = 0 */
  w5 = 0.;
  /* #668: @11 = horzcat(@4, @34, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #669: @11 = @11' */
  /* #670: @15 = horzcat(@0, @24, @11) */
  rr=w15;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  /* #671: @26 = @15' */
  for (i=0, rr=w26, cs=w15; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #672: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<9; ++i) *rr++ = (- *cs++ );
  /* #673: (@37[:18:6;3:6] = @26) */
  for (rr=w37+0, ss=w26; rr!=w37+18; rr+=6) for (tt=rr+3; tt!=rr+6; tt+=1) *tt = *ss++;
  /* #674: @4 = 0 */
  w4 = 0.;
  /* #675: @0 = @32[3:6] */
  for (rr=w0, ss=w32+3; ss!=w32+6; ss+=1) *rr++ = *ss;
  /* #676: @0 = nonzeros(@0) */
  /* #677: @24 = @2[10:13] */
  for (rr=w24, ss=w2+10; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #678: @0 = (@0*@24) */
  for (i=0, rr=w0, cs=w24; i<3; ++i) (*rr++) *= (*cs++);
  /* #679: @34 = @0[2] */
  for (rr=(&w34), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #680: @34 = (-@34) */
  w34 = (- w34 );
  /* #681: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #682: @24 = horzcat(@4, @34, @5) */
  rr=w24;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #683: @24 = @24' */
  /* #684: @4 = @0[2] */
  for (rr=(&w4), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #685: @34 = 0 */
  w34 = 0.;
  /* #686: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #687: @5 = (-@5) */
  w5 = (- w5 );
  /* #688: @11 = horzcat(@4, @34, @5) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #689: @11 = @11' */
  /* #690: @4 = @0[1] */
  for (rr=(&w4), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #691: @4 = (-@4) */
  w4 = (- w4 );
  /* #692: @34 = @0[0] */
  for (rr=(&w34), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #693: @5 = 0 */
  w5 = 0.;
  /* #694: @0 = horzcat(@4, @34, @5) */
  rr=w0;
  *rr++ = w4;
  *rr++ = w34;
  *rr++ = w5;
  /* #695: @0 = @0' */
  /* #696: @26 = horzcat(@24, @11, @0) */
  rr=w26;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  /* #697: @15 = @26' */
  for (i=0, rr=w15, cs=w26; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #698: @15 = (-@15) */
  for (i=0, rr=w15, cs=w15; i<9; ++i) *rr++ = (- *cs++ );
  /* #699: (@37[21, 22, 23, 27, 28, 29, 33, 34, 35] = @15) */
  for (cii=casadi_s7, rr=w37, ss=w15; cii!=casadi_s7+9; ++cii, ++ss) rr[*cii] = *ss;
  /* #700: @4 = 0 */
  w4 = 0.;
  /* #701: (@37[4] = @4) */
  for (rr=w37+4, ss=(&w4); rr!=w37+5; rr+=1) *rr = *ss++;
  /* #702: @4 = 0 */
  w4 = 0.;
  /* #703: (@37[24] = @4) */
  for (rr=w37+24, ss=(&w4); rr!=w37+25; rr+=1) *rr = *ss++;
  /* #704: @4 = 0 */
  w4 = 0.;
  /* #705: (@37[16] = @4) */
  for (rr=w37+16, ss=(&w4); rr!=w37+17; rr+=1) *rr = *ss++;
  /* #706: @4 = 0 */
  w4 = 0.;
  /* #707: (@37[26] = @4) */
  for (rr=w37+26, ss=(&w4); rr!=w37+27; rr+=1) *rr = *ss++;
  /* #708: @4 = 0 */
  w4 = 0.;
  /* #709: (@37[5] = @4) */
  for (rr=w37+5, ss=(&w4); rr!=w37+6; rr+=1) *rr = *ss++;
  /* #710: @4 = 0 */
  w4 = 0.;
  /* #711: (@37[30] = @4) */
  for (rr=w37+30, ss=(&w4); rr!=w37+31; rr+=1) *rr = *ss++;
  /* #712: @4 = 0 */
  w4 = 0.;
  /* #713: (@37[11] = @4) */
  for (rr=w37+11, ss=(&w4); rr!=w37+12; rr+=1) *rr = *ss++;
  /* #714: @4 = 0 */
  w4 = 0.;
  /* #715: (@37[31] = @4) */
  for (rr=w37+31, ss=(&w4); rr!=w37+32; rr+=1) *rr = *ss++;
  /* #716: @36 = (@36+@37) */
  for (i=0, rr=w36, cs=w37; i<36; ++i) (*rr++) += (*cs++);
  /* #717: @32 = @2[7:13] */
  for (rr=w32, ss=w2+7; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #718: @35 = mac(@36,@32,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w36+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #719: @22 = (@22-@35) */
  for (i=0, rr=w22, cs=w35; i<6; ++i) (*rr++) -= (*cs++);
  /* #720: @35 = zeros(6x1) */
  casadi_clear(w35, 6);
  /* #721: @36 = zeros(6x6) */
  casadi_clear(w36, 36);
  /* #722: @4 = 3 */
  w4 = 3.;
  /* #723: @34 = @2[7] */
  for (rr=(&w34), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #724: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #725: @4 = (@4*@34) */
  w4 *= w34;
  /* #726: (@36[0] = @4) */
  for (rr=w36+0, ss=(&w4); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #727: @4 = 50 */
  w4 = 50.;
  /* #728: @34 = @2[8] */
  for (rr=(&w34), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #729: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #730: @4 = (@4*@34) */
  w4 *= w34;
  /* #731: (@36[7] = @4) */
  for (rr=w36+7, ss=(&w4); rr!=w36+8; rr+=1) *rr = *ss++;
  /* #732: @4 = 50 */
  w4 = 50.;
  /* #733: @34 = @2[9] */
  for (rr=(&w34), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #734: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #735: @4 = (@4*@34) */
  w4 *= w34;
  /* #736: (@36[14] = @4) */
  for (rr=w36+14, ss=(&w4); rr!=w36+15; rr+=1) *rr = *ss++;
  /* #737: @4 = 40 */
  w4 = 40.;
  /* #738: @34 = @2[10] */
  for (rr=(&w34), ss=w2+10; ss!=w2+11; ss+=1) *rr++ = *ss;
  /* #739: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #740: @4 = (@4*@34) */
  w4 *= w34;
  /* #741: (@36[21] = @4) */
  for (rr=w36+21, ss=(&w4); rr!=w36+22; rr+=1) *rr = *ss++;
  /* #742: @4 = 200 */
  w4 = 200.;
  /* #743: @34 = @2[11] */
  for (rr=(&w34), ss=w2+11; ss!=w2+12; ss+=1) *rr++ = *ss;
  /* #744: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #745: @4 = (@4*@34) */
  w4 *= w34;
  /* #746: (@36[28] = @4) */
  for (rr=w36+28, ss=(&w4); rr!=w36+29; rr+=1) *rr = *ss++;
  /* #747: @4 = 10 */
  w4 = 10.;
  /* #748: @34 = @2[12] */
  for (rr=(&w34), ss=w2+12; ss!=w2+13; ss+=1) *rr++ = *ss;
  /* #749: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #750: @4 = (@4*@34) */
  w4 *= w34;
  /* #751: (@36[35] = @4) */
  for (rr=w36+35, ss=(&w4); rr!=w36+36; rr+=1) *rr = *ss++;
  /* #752: @4 = 0 */
  w4 = 0.;
  /* #753: (@36[4] = @4) */
  for (rr=w36+4, ss=(&w4); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #754: @4 = 0 */
  w4 = 0.;
  /* #755: (@36[5] = @4) */
  for (rr=w36+5, ss=(&w4); rr!=w36+6; rr+=1) *rr = *ss++;
  /* #756: @4 = 0 */
  w4 = 0.;
  /* #757: (@36[9] = @4) */
  for (rr=w36+9, ss=(&w4); rr!=w36+10; rr+=1) *rr = *ss++;
  /* #758: @4 = 5 */
  w4 = 5.;
  /* #759: @34 = @2[8] */
  for (rr=(&w34), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #760: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #761: @4 = (@4*@34) */
  w4 *= w34;
  /* #762: (@36[11] = @4) */
  for (rr=w36+11, ss=(&w4); rr!=w36+12; rr+=1) *rr = *ss++;
  /* #763: @4 = 0 */
  w4 = 0.;
  /* #764: (@36[15] = @4) */
  for (rr=w36+15, ss=(&w4); rr!=w36+16; rr+=1) *rr = *ss++;
  /* #765: @4 = -5 */
  w4 = -5.;
  /* #766: @34 = @2[9] */
  for (rr=(&w34), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #767: @34 = fabs(@34) */
  w34 = casadi_fabs( w34 );
  /* #768: @4 = (@4*@34) */
  w4 *= w34;
  /* #769: (@36[16] = @4) */
  for (rr=w36+16, ss=(&w4); rr!=w36+17; rr+=1) *rr = *ss++;
  /* #770: @35 = mac(@36,@32,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w36+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #771: @22 = (@22-@35) */
  for (i=0, rr=w22, cs=w35; i<6; ++i) (*rr++) -= (*cs++);
  /* #772: @4 = 9.81 */
  w4 = 9.8100000000000005e+00;
  /* #773: @4 = (@4*@1) */
  w4 *= w1;
  /* #774: @34 = 172.96 */
  w34 = 1.7296006950873124e+02;
  /* #775: @34 = (@4-@34) */
  w34  = (w4-w34);
  /* #776: @16 = @2[3:7] */
  for (rr=w16, ss=w2+3; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #777: @5 = ||@16||_F */
  w5 = sqrt(casadi_dot(4, w16, w16));
  /* #778: @16 = (@16/@5) */
  for (i=0, rr=w16; i<4; ++i) (*rr++) /= w5;
  /* #779: @5 = @16[0] */
  for (rr=(&w5), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #780: @7 = @16[2] */
  for (rr=(&w7), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #781: @9 = (@5*@7) */
  w9  = (w5*w7);
  /* #782: @10 = @16[3] */
  for (rr=(&w10), ss=w16+3; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #783: @31 = @16[1] */
  for (rr=(&w31), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #784: @8 = (@10*@31) */
  w8  = (w10*w31);
  /* #785: @9 = (@9-@8) */
  w9 -= w8;
  /* #786: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #787: @9 = asin(@9) */
  w9 = asin( w9 );
  /* #788: @8 = sin(@9) */
  w8 = sin( w9 );
  /* #789: @34 = (@34*@8) */
  w34 *= w8;
  /* #790: @39 = 172.96 */
  w39 = 1.7296006950873124e+02;
  /* #791: @39 = (@4-@39) */
  w39  = (w4-w39);
  /* #792: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #793: @39 = (@39*@9) */
  w39 *= w9;
  /* #794: @5 = (@5*@31) */
  w5 *= w31;
  /* #795: @10 = (@7*@10) */
  w10  = (w7*w10);
  /* #796: @5 = (@5+@10) */
  w5 += w10;
  /* #797: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #798: @10 = 1 */
  w10 = 1.;
  /* #799: @31 = sq(@31) */
  w31 = casadi_sq( w31 );
  /* #800: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #801: @31 = (@31+@7) */
  w31 += w7;
  /* #802: @31 = (2.*@31) */
  w31 = (2.* w31 );
  /* #803: @10 = (@10-@31) */
  w10 -= w31;
  /* #804: @5 = atan2(@5,@10) */
  w5  = atan2(w5,w10);
  /* #805: @10 = sin(@5) */
  w10 = sin( w5 );
  /* #806: @39 = (@39*@10) */
  w39 *= w10;
  /* #807: @39 = (-@39) */
  w39 = (- w39 );
  /* #808: @31 = 172.96 */
  w31 = 1.7296006950873124e+02;
  /* #809: @31 = (@4-@31) */
  w31  = (w4-w31);
  /* #810: @31 = (@31*@9) */
  w31 *= w9;
  /* #811: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #812: @31 = (@31*@5) */
  w31 *= w5;
  /* #813: @31 = (-@31) */
  w31 = (- w31 );
  /* #814: @7 = 14.9 */
  w7 = 1.4900000000000000e+01;
  /* #815: @7 = (@7/@1) */
  w7 /= w1;
  /* #816: @12 = (@7*@12) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) (*rr++)  = (w7*(*cs++));
  /* #817: @6 = (@6/@1) */
  w6 /= w1;
  /* #818: @13 = (@6*@13) */
  for (i=0, rr=w13, cs=w13; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #819: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<3; ++i) (*rr++) += (*cs++);
  /* #820: @6 = 2.6 */
  w6 = 2.6000000000000001e+00;
  /* #821: @6 = (@6/@1) */
  w6 /= w1;
  /* #822: @23 = (@6*@23) */
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #823: @12 = (@12+@23) */
  for (i=0, rr=w12, cs=w23; i<3; ++i) (*rr++) += (*cs++);
  /* #824: @6 = @12[2] */
  for (rr=(&w6), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #825: @6 = (@6*@4) */
  w6 *= w4;
  /* #826: @6 = (@6*@9) */
  w6 *= w9;
  /* #827: @6 = (@6*@10) */
  w6 *= w10;
  /* #828: @1 = @12[1] */
  for (rr=(&w1), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #829: @1 = (@1*@4) */
  w1 *= w4;
  /* #830: @1 = (@1*@9) */
  w1 *= w9;
  /* #831: @1 = (@1*@5) */
  w1 *= w5;
  /* #832: @6 = (@6-@1) */
  w6 -= w1;
  /* #833: @1 = @12[2] */
  for (rr=(&w1), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #834: @1 = (@1*@4) */
  w1 *= w4;
  /* #835: @1 = (@1*@8) */
  w1 *= w8;
  /* #836: @7 = @12[0] */
  for (rr=(&w7), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #837: @7 = (@7*@4) */
  w7 *= w4;
  /* #838: @7 = (@7*@9) */
  w7 *= w9;
  /* #839: @7 = (@7*@5) */
  w7 *= w5;
  /* #840: @1 = (@1+@7) */
  w1 += w7;
  /* #841: @7 = @12[0] */
  for (rr=(&w7), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #842: @7 = (@7*@4) */
  w7 *= w4;
  /* #843: @7 = (@7*@9) */
  w7 *= w9;
  /* #844: @7 = (@7*@10) */
  w7 *= w10;
  /* #845: @7 = (-@7) */
  w7 = (- w7 );
  /* #846: @10 = @12[1] */
  for (rr=(&w10), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #847: @10 = (@10*@4) */
  w10 *= w4;
  /* #848: @10 = (@10*@8) */
  w10 *= w8;
  /* #849: @7 = (@7-@10) */
  w7 -= w10;
  /* #850: @35 = vertcat(@34, @39, @31, @6, @1, @7) */
  rr=w35;
  *rr++ = w34;
  *rr++ = w39;
  *rr++ = w31;
  *rr++ = w6;
  *rr++ = w1;
  *rr++ = w7;
  /* #851: @22 = (@22-@35) */
  for (i=0, rr=w22, cs=w35; i<6; ++i) (*rr++) -= (*cs++);
  /* #852: @20 = mac(@21,@22,@20) */
  for (i=0, rr=w20; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w21+j, tt=w22+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #853: output[0][2] = @20 */
  if (res[0]) casadi_copy(w20, 6, res[0]+7);
  return 0;
}

/* SAM_equation_system_impl_dae_fun:(i0[19],i1[19],i2[6],i3[0],i4[],i5[25])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+6, *cs;
  casadi_real *w0=w+284, *w1=w+303, *w2=w+322, *w3=w+335, *w4=w+341;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 19, w0);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 19, w1);
  /* #2: @2 = @1[:13] */
  for (rr=w2, ss=w1+0; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #3: @3 = @1[13:19] */
  for (rr=w3, ss=w1+13; ss!=w1+19; ss+=1) *rr++ = *ss;
  /* #4: @4 = x_dot(@2, @3) */
  arg1[0]=w2;
  arg1[1]=w3;
  res1[0]=w4;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #5: @3 = input[2][0] */
  casadi_copy(arg[2], 6, w3);
  /* #6: @1 = vertcat(@4, @3) */
  rr=w1;
  for (i=0, cs=w4; i<13; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<6; ++i) *rr++ = *cs++;
  /* #7: @0 = (@0-@1) */
  for (i=0, rr=w0, cs=w1; i<19; ++i) (*rr++) -= (*cs++);
  /* #8: output[0][0] = @0 */
  casadi_copy(w0, 19, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void SAM_equation_system_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int SAM_equation_system_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real SAM_equation_system_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* SAM_equation_system_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    case 4: return casadi_s11;
    case 5: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* SAM_equation_system_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 7;
  if (sz_w) *sz_w = 354;
  return 0;
}

CASADI_SYMBOL_EXPORT int SAM_equation_system_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 7*sizeof(casadi_int);
  if (sz_w) *sz_w = 354*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
